# Code generated by testgen. DO NOT EDIT.

variable "cids" {
  type    = set(string)
  default = null
}

variable "description" {
  type    = string
  default = null
}

variable "name" {
  type    = string
  default = null
}

resource "crowdstrike_cid_group" "test" {
  cids        = var.cids
  description = var.description
  name        = var.name
}
