package mlfilepathexclusion

import (
	"context"
	"fmt"
	"strings"

	"github.com/crowdstrike/gofalcon/falcon/client"
	"github.com/crowdstrike/gofalcon/falcon/client/ml_exclusions"
	"github.com/crowdstrike/gofalcon/falcon/models"
	"github.com/crowdstrike/terraform-provider-crowdstrike/internal/clientoverrides"
	"github.com/crowdstrike/terraform-provider-crowdstrike/internal/config"
	fwvalidators "github.com/crowdstrike/terraform-provider-crowdstrike/internal/framework/validators"
	"github.com/crowdstrike/terraform-provider-crowdstrike/internal/scopes"
	"github.com/crowdstrike/terraform-provider-crowdstrike/internal/tferrors"
	"github.com/crowdstrike/terraform-provider-crowdstrike/internal/utils"
	"github.com/hashicorp/terraform-plugin-framework-timetypes/timetypes"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

var (
	_ datasource.DataSource              = &mlFilePathExclusionDataSource{}
	_ datasource.DataSourceWithConfigure = &mlFilePathExclusionDataSource{}
)

var mlFilePathExclusionDataSourceScopes = []scopes.Scope{{Name: "Machine Learning Exclusions", Read: true}}

type mlFilePathExclusionDataSource struct {
	client *client.CrowdStrikeAPISpecification
}

func NewMLFilePathExclusionDataSource() datasource.DataSource {
	return &mlFilePathExclusionDataSource{}
}

func (d *mlFilePathExclusionDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_ml_file_path_exclusion"
}

func (d *mlFilePathExclusionDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	providerConfig, ok := req.ProviderData.(config.ProviderConfig)
	if !ok {
		resp.Diagnostics.AddError("Unexpected Data Source Configure Type", fmt.Sprintf("Expected config.ProviderConfig, got: %T. Please report this issue to the provider developers.", req.ProviderData))
		return
	}
	d.client = providerConfig.Client
}

func (d *mlFilePathExclusionDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: utils.MarkdownDescription("Endpoint Security", "Looks up a single ML file path exclusion by ID or exact pattern. The lookup fails if no object or multiple objects match. Use an ID to disambiguate matches.", mlFilePathExclusionDataSourceScopes),
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "Unique identifier. Specify exactly one of `id` or `pattern`.",
				Optional:            true,
				Validators:          []validator.String{fwvalidators.StringNotWhitespace(), stringvalidator.ExactlyOneOf(path.MatchRoot("id"), path.MatchRoot("pattern"))},
			},
			"pattern": schema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "Exact, case-sensitive file path pattern, including any literal wildcard characters. Specify exactly one of `id` or `pattern`.",
				Optional:            true,
				Validators:          []validator.String{fwvalidators.StringNotWhitespace()},
			},
			"host_groups": schema.SetAttribute{
				Computed:            true,
				MarkdownDescription: "The set of host group IDs this exclusion applies to. Contains `all` when applied globally.",
				ElementType:         types.StringType,
			},
			"exclude_detections": schema.BoolAttribute{
				Computed:            true,
				MarkdownDescription: "Whether to exclude matching files from machine learning detections and preventions.",
			},
			"exclude_uploads": schema.BoolAttribute{
				Computed:            true,
				MarkdownDescription: "Whether to exclude matching files from cloud extraction/uploads.",
			},
			"comment": schema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "Always null: Falcon does not return the comment on reads.",
			},
			"regexp_value": schema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "The regular expression representation of `pattern` generated by Falcon.",
			},
			"value_hash": schema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "The hash of the configured exclusion pattern value.",
			},
			"applied_globally": schema.BoolAttribute{
				Computed:            true,
				MarkdownDescription: "Whether Falcon reports this exclusion as globally applied.",
			},
			"last_modified": schema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "The timestamp when the exclusion was last modified.",
				CustomType:          timetypes.RFC3339Type{},
			},
			"modified_by": schema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "The user who last modified the exclusion.",
			},
			"created_on": schema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "The timestamp when the exclusion was created.",
				CustomType:          timetypes.RFC3339Type{},
			},
			"created_by": schema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "The user who created the exclusion.",
			},
			"last_updated": schema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "Always null: the last Terraform update timestamp belongs to resource state and is not returned by Falcon.",
			},
		},
	}
}

func (d *mlFilePathExclusionDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var data mlFilePathExclusionResourceModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}
	result, diags := d.lookup(ctx, data.ID.ValueString(), data.Pattern.ValueString())
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}
	resp.Diagnostics.Append(data.wrap(ctx, result)...)
	if resp.Diagnostics.HasError() {
		return
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (d *mlFilePathExclusionDataSource) get(ctx context.Context, ids []string) ([]*models.ExclusionsExclusionV1, diag.Diagnostics) {
	var diags diag.Diagnostics
	params := ml_exclusions.NewGetMLExclusionsV1ParamsWithContext(ctx).WithIds(ids)
	response, err := d.client.MlExclusions.GetMLExclusionsV1(params, clientoverrides.DecodeExclusionsGroups)
	if err != nil {
		diags.Append(tferrors.NewDiagnosticFromAPIError(tferrors.Read, err, mlFilePathExclusionDataSourceScopes))
		return nil, diags
	}
	if response == nil || response.Payload == nil {
		diags.Append(tferrors.NewEmptyResponseError(tferrors.Read))
		return nil, diags
	}
	if diagnostic := tferrors.NewDiagnosticFromPayloadErrors(tferrors.Read, response.Payload.Errors); diagnostic != nil {
		diags.Append(diagnostic)
		return nil, diags
	}
	return response.Payload.Resources, diags
}

func (d *mlFilePathExclusionDataSource) lookup(ctx context.Context, id, pattern string) (*models.ExclusionsExclusionV1, diag.Diagnostics) {
	var diags diag.Diagnostics
	if id != "" {
		results, readDiags := d.get(ctx, []string{id})
		diags.Append(readDiags...)
		if diags.HasError() {
			return nil, diags
		}
		for _, result := range results {
			if result != nil && result.ID != nil && *result.ID == id {
				return result, diags
			}
		}
		diags.Append(tferrors.NewNotFoundError(fmt.Sprintf("No ML file path exclusion found with ID %q.", id)))
		return nil, diags
	}

	escaped := strings.NewReplacer(`\`, `\\`, `'`, `\'`).Replace(pattern)
	filter := fmt.Sprintf("value:'%s'", escaped)
	const limit int64 = 100
	var offset int64
	var match *models.ExclusionsExclusionV1
	seen := map[string]bool{}
	for {
		params := ml_exclusions.NewQueryMLExclusionsV1ParamsWithContext(ctx).WithFilter(&filter).WithLimit(utils.Addr(limit)).WithOffset(&offset)
		response, err := d.client.MlExclusions.QueryMLExclusionsV1(params)
		if err != nil {
			diags.Append(tferrors.NewDiagnosticFromAPIError(tferrors.Read, err, mlFilePathExclusionDataSourceScopes))
			return nil, diags
		}
		if response == nil || response.Payload == nil {
			diags.Append(tferrors.NewEmptyResponseError(tferrors.Read))
			return nil, diags
		}
		payload := response.Payload
		if diagnostic := tferrors.NewDiagnosticFromPayloadErrors(tferrors.Read, payload.Errors); diagnostic != nil {
			diags.Append(diagnostic)
			return nil, diags
		}
		ids := []string{}
		for _, candidateID := range payload.Resources {
			if candidateID != "" && !seen[candidateID] {
				seen[candidateID] = true
				ids = append(ids, candidateID)
			}
		}
		if len(ids) > 0 {
			results, readDiags := d.get(ctx, ids)
			diags.Append(readDiags...)
			if diags.HasError() {
				return nil, diags
			}
			returned := map[string]bool{}
			for _, result := range results {
				if result == nil || result.ID == nil {
					continue
				}
				returned[*result.ID] = true
				if result.Value == nil || *result.Value != pattern {
					continue
				}
				if match != nil && *match.ID != *result.ID {
					diags.AddError("Ambiguous ML file path exclusion lookup", "More than one ML file path exclusion matches the exact pattern. Specify an ID instead.")
					return nil, diags
				}
				match = result
			}
			for _, candidateID := range ids {
				if !returned[candidateID] {
					diags.AddError("Incomplete ML file path exclusion lookup", "An exclusion returned by the query could not be retrieved. Retry the lookup.")
					return nil, diags
				}
			}
		}
		offset += int64(len(payload.Resources))
		if payload.Meta != nil && payload.Meta.Pagination != nil && payload.Meta.Pagination.Total != nil {
			if offset >= *payload.Meta.Pagination.Total {
				break
			}
		} else if int64(len(payload.Resources)) < limit {
			break
		}
		if len(ids) == 0 {
			diags.AddError("Incomplete ML file path exclusion lookup", "The API pagination did not advance. Retry the lookup.")
			return nil, diags
		}
	}
	if match == nil {
		diags.Append(tferrors.NewNotFoundError(fmt.Sprintf("No ML file path exclusion found with exact pattern %q.", pattern)))
	}
	return match, diags
}
