// Code generated by testgen. DO NOT EDIT.

package contentupdatepolicy_test

import (
	"testing"

	"github.com/crowdstrike/terraform-provider-crowdstrike/internal/acctest"
	contentupdatepolicy "github.com/crowdstrike/terraform-provider-crowdstrike/internal/content_update_policy"
	"github.com/hashicorp/terraform-plugin-testing/config"
	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
	"github.com/hashicorp/terraform-plugin-testing/knownvalue"
	"github.com/hashicorp/terraform-plugin-testing/plancheck"
	"github.com/hashicorp/terraform-plugin-testing/statecheck"
	"github.com/hashicorp/terraform-plugin-testing/tfjsonpath"
)

func TestAccContentPolicyResource_basic(t *testing.T) {
	rName := acctest.RandomResourceName()
	resourceName := "crowdstrike_content_update_policy.test"

	resource.ParallelTest(t, resource.TestCase{
		PreCheck:                 func() { acctest.PreCheck(t) },
		ProtoV6ProviderFactories: acctest.ProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			{
				ConfigDirectory: config.StaticDirectory("testdata/content_update_policy"),
				ConfigVariables: config.Variables{
					"description":              config.StringVariable(rName),
					"name":                     config.StringVariable(rName),
					"rapid_response":           config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("ga")}),
					"sensor_operations":        config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("ga")}),
					"system_critical":          config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("ga")}),
					"vulnerability_management": config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("ga")}),
				},
				ConfigStateChecks: []statecheck.StateCheck{
					statecheck.ExpectKnownValue(resourceName, tfjsonpath.New("id"), knownvalue.NotNull()),
					statecheck.ExpectKnownValue(resourceName, tfjsonpath.New("last_updated"), knownvalue.NotNull()),
				},
			},
			{
				ConfigDirectory: config.StaticDirectory("testdata/content_update_policy"),
				ConfigVariables: config.Variables{
					"description":              config.StringVariable(rName),
					"name":                     config.StringVariable(rName),
					"rapid_response":           config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("ga")}),
					"sensor_operations":        config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("ga")}),
					"system_critical":          config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("ga")}),
					"vulnerability_management": config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("ga")}),
				},
				ResourceName:            resourceName,
				ImportState:             true,
				ImportStateVerify:       true,
				ImportStateVerifyIgnore: []string{"last_updated"},
			},
		},
	})
}

func TestAccContentPolicyResource_disappears(t *testing.T) {
	rName := acctest.RandomResourceName()
	resourceName := "crowdstrike_content_update_policy.test"

	resource.ParallelTest(t, resource.TestCase{
		PreCheck:                 func() { acctest.PreCheck(t) },
		ProtoV6ProviderFactories: acctest.ProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			{
				ConfigDirectory: config.StaticDirectory("testdata/content_update_policy"),
				ConfigVariables: config.Variables{
					"description":              config.StringVariable(rName),
					"name":                     config.StringVariable(rName),
					"rapid_response":           config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("ga")}),
					"sensor_operations":        config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("ga")}),
					"system_critical":          config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("ga")}),
					"vulnerability_management": config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("ga")}),
				},
				ConfigStateChecks: []statecheck.StateCheck{
					acctest.ResourceDisappears(contentupdatepolicy.NewContentPolicyResource, resourceName),
				},
				ExpectNonEmptyPlan: true,
				ConfigPlanChecks: resource.ConfigPlanChecks{
					PostApplyPostRefresh: []plancheck.PlanCheck{
						plancheck.ExpectResourceAction(resourceName, plancheck.ResourceActionCreate),
					},
				},
			},
		},
	})
}

func TestAccContentPolicyResource_description(t *testing.T) {
	rName := acctest.RandomResourceName()
	resourceName := "crowdstrike_content_update_policy.test"

	resource.ParallelTest(t, resource.TestCase{
		PreCheck:                 func() { acctest.PreCheck(t) },
		ProtoV6ProviderFactories: acctest.ProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			{
				ConfigDirectory: config.StaticDirectory("testdata/content_update_policy"),
				ConfigVariables: config.Variables{
					"description":              config.StringVariable(rName),
					"name":                     config.StringVariable(rName),
					"rapid_response":           config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("ga")}),
					"sensor_operations":        config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("ga")}),
					"system_critical":          config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("ga")}),
					"vulnerability_management": config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("ga")}),
				},
				ConfigStateChecks: []statecheck.StateCheck{
					statecheck.ExpectKnownValue(resourceName, tfjsonpath.New("description"), knownvalue.StringExact(rName)),
				},
			},
			{
				ConfigDirectory: config.StaticDirectory("testdata/content_update_policy"),
				ConfigVariables: config.Variables{
					"description":              config.StringVariable(rName + "-updated"),
					"name":                     config.StringVariable(rName),
					"rapid_response":           config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("ga")}),
					"sensor_operations":        config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("ga")}),
					"system_critical":          config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("ga")}),
					"vulnerability_management": config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("ga")}),
				},
				ConfigPlanChecks: resource.ConfigPlanChecks{
					PreApply: []plancheck.PlanCheck{
						plancheck.ExpectResourceAction(resourceName, plancheck.ResourceActionUpdate),
					},
				},
				ConfigStateChecks: []statecheck.StateCheck{
					statecheck.ExpectKnownValue(resourceName, tfjsonpath.New("description"), knownvalue.StringExact(rName+"-updated")),
				},
			},
			{
				ConfigDirectory: config.StaticDirectory("testdata/content_update_policy"),
				ConfigVariables: config.Variables{
					"description":              config.StringVariable(rName + "-updated"),
					"name":                     config.StringVariable(rName),
					"rapid_response":           config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("ga")}),
					"sensor_operations":        config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("ga")}),
					"system_critical":          config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("ga")}),
					"vulnerability_management": config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("ga")}),
				},
				ResourceName:            resourceName,
				ImportState:             true,
				ImportStateVerify:       true,
				ImportStateVerifyIgnore: []string{"last_updated"},
			},
		},
	})
}

func TestAccContentPolicyResource_enabled(t *testing.T) {
	rName := acctest.RandomResourceName()
	resourceName := "crowdstrike_content_update_policy.test"

	resource.ParallelTest(t, resource.TestCase{
		PreCheck:                 func() { acctest.PreCheck(t) },
		ProtoV6ProviderFactories: acctest.ProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			{
				ConfigDirectory: config.StaticDirectory("testdata/content_update_policy"),
				ConfigVariables: config.Variables{
					"description":              config.StringVariable(rName),
					"enabled":                  config.BoolVariable(true),
					"name":                     config.StringVariable(rName),
					"rapid_response":           config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("ga")}),
					"sensor_operations":        config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("ga")}),
					"system_critical":          config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("ga")}),
					"vulnerability_management": config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("ga")}),
				},
				ConfigStateChecks: []statecheck.StateCheck{
					statecheck.ExpectKnownValue(resourceName, tfjsonpath.New("enabled"), knownvalue.Bool(true)),
				},
			},
			{
				ConfigDirectory: config.StaticDirectory("testdata/content_update_policy"),
				ConfigVariables: config.Variables{
					"description":              config.StringVariable(rName),
					"enabled":                  config.BoolVariable(false),
					"name":                     config.StringVariable(rName),
					"rapid_response":           config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("ga")}),
					"sensor_operations":        config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("ga")}),
					"system_critical":          config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("ga")}),
					"vulnerability_management": config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("ga")}),
				},
				ConfigPlanChecks: resource.ConfigPlanChecks{
					PreApply: []plancheck.PlanCheck{
						plancheck.ExpectResourceAction(resourceName, plancheck.ResourceActionUpdate),
					},
				},
				ConfigStateChecks: []statecheck.StateCheck{
					statecheck.ExpectKnownValue(resourceName, tfjsonpath.New("enabled"), knownvalue.Bool(false)),
				},
			},
			{
				ConfigDirectory: config.StaticDirectory("testdata/content_update_policy"),
				ConfigVariables: config.Variables{
					"description":              config.StringVariable(rName),
					"name":                     config.StringVariable(rName),
					"rapid_response":           config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("ga")}),
					"sensor_operations":        config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("ga")}),
					"system_critical":          config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("ga")}),
					"vulnerability_management": config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("ga")}),
				},
				ConfigPlanChecks: resource.ConfigPlanChecks{
					PreApply: []plancheck.PlanCheck{
						plancheck.ExpectResourceAction(resourceName, plancheck.ResourceActionUpdate),
					},
				},
				ConfigStateChecks: []statecheck.StateCheck{
					statecheck.ExpectKnownValue(resourceName, tfjsonpath.New("enabled"), knownvalue.Bool(true)),
				},
			},
			{
				ConfigDirectory: config.StaticDirectory("testdata/content_update_policy"),
				ConfigVariables: config.Variables{
					"description":              config.StringVariable(rName),
					"name":                     config.StringVariable(rName),
					"rapid_response":           config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("ga")}),
					"sensor_operations":        config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("ga")}),
					"system_critical":          config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("ga")}),
					"vulnerability_management": config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("ga")}),
				},
				ResourceName:            resourceName,
				ImportState:             true,
				ImportStateVerify:       true,
				ImportStateVerifyIgnore: []string{"last_updated"},
			},
		},
	})
}

func TestAccContentPolicyResource_hostGroups(t *testing.T) {
	t.Skip("testgen: references to other resources are not supported yet")
}

func TestAccContentPolicyResource_name(t *testing.T) {
	rName := acctest.RandomResourceName()
	resourceName := "crowdstrike_content_update_policy.test"

	resource.ParallelTest(t, resource.TestCase{
		PreCheck:                 func() { acctest.PreCheck(t) },
		ProtoV6ProviderFactories: acctest.ProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			{
				ConfigDirectory: config.StaticDirectory("testdata/content_update_policy"),
				ConfigVariables: config.Variables{
					"description":              config.StringVariable(rName),
					"name":                     config.StringVariable(rName),
					"rapid_response":           config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("ga")}),
					"sensor_operations":        config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("ga")}),
					"system_critical":          config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("ga")}),
					"vulnerability_management": config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("ga")}),
				},
				ConfigStateChecks: []statecheck.StateCheck{
					statecheck.ExpectKnownValue(resourceName, tfjsonpath.New("name"), knownvalue.StringExact(rName)),
				},
			},
			{
				ConfigDirectory: config.StaticDirectory("testdata/content_update_policy"),
				ConfigVariables: config.Variables{
					"description":              config.StringVariable(rName),
					"name":                     config.StringVariable(rName + "-updated"),
					"rapid_response":           config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("ga")}),
					"sensor_operations":        config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("ga")}),
					"system_critical":          config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("ga")}),
					"vulnerability_management": config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("ga")}),
				},
				ConfigPlanChecks: resource.ConfigPlanChecks{
					PreApply: []plancheck.PlanCheck{
						plancheck.ExpectResourceAction(resourceName, plancheck.ResourceActionUpdate),
					},
				},
				ConfigStateChecks: []statecheck.StateCheck{
					statecheck.ExpectKnownValue(resourceName, tfjsonpath.New("name"), knownvalue.StringExact(rName+"-updated")),
				},
			},
			{
				ConfigDirectory: config.StaticDirectory("testdata/content_update_policy"),
				ConfigVariables: config.Variables{
					"description":              config.StringVariable(rName),
					"name":                     config.StringVariable(rName + "-updated"),
					"rapid_response":           config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("ga")}),
					"sensor_operations":        config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("ga")}),
					"system_critical":          config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("ga")}),
					"vulnerability_management": config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("ga")}),
				},
				ResourceName:            resourceName,
				ImportState:             true,
				ImportStateVerify:       true,
				ImportStateVerifyIgnore: []string{"last_updated"},
			},
		},
	})
}

func TestAccContentPolicyResource_rapidResponse(t *testing.T) {
	rName := acctest.RandomResourceName()
	resourceName := "crowdstrike_content_update_policy.test"

	resource.ParallelTest(t, resource.TestCase{
		PreCheck:                 func() { acctest.PreCheck(t) },
		ProtoV6ProviderFactories: acctest.ProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			{
				ConfigDirectory: config.StaticDirectory("testdata/content_update_policy"),
				ConfigVariables: config.Variables{
					"description":              config.StringVariable(rName),
					"name":                     config.StringVariable(rName),
					"rapid_response":           config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("ga")}),
					"sensor_operations":        config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("ga")}),
					"system_critical":          config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("ga")}),
					"vulnerability_management": config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("ga")}),
				},
				ConfigStateChecks: []statecheck.StateCheck{
					statecheck.ExpectKnownValue(resourceName, tfjsonpath.New("rapid_response"), knownvalue.ObjectPartial(map[string]knownvalue.Check{"ring_assignment": knownvalue.StringExact("ga")})),
				},
			},
			{
				ConfigDirectory: config.StaticDirectory("testdata/content_update_policy"),
				ConfigVariables: config.Variables{
					"description":              config.StringVariable(rName),
					"name":                     config.StringVariable(rName),
					"rapid_response":           config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("ea")}),
					"sensor_operations":        config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("ga")}),
					"system_critical":          config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("ga")}),
					"vulnerability_management": config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("ga")}),
				},
				ConfigPlanChecks: resource.ConfigPlanChecks{
					PreApply: []plancheck.PlanCheck{
						plancheck.ExpectResourceAction(resourceName, plancheck.ResourceActionUpdate),
					},
				},
				ConfigStateChecks: []statecheck.StateCheck{
					statecheck.ExpectKnownValue(resourceName, tfjsonpath.New("rapid_response"), knownvalue.ObjectPartial(map[string]knownvalue.Check{"ring_assignment": knownvalue.StringExact("ea")})),
				},
			},
			{
				ConfigDirectory: config.StaticDirectory("testdata/content_update_policy"),
				ConfigVariables: config.Variables{
					"description":              config.StringVariable(rName),
					"name":                     config.StringVariable(rName),
					"rapid_response":           config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("pause")}),
					"sensor_operations":        config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("ga")}),
					"system_critical":          config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("ga")}),
					"vulnerability_management": config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("ga")}),
				},
				ConfigPlanChecks: resource.ConfigPlanChecks{
					PreApply: []plancheck.PlanCheck{
						plancheck.ExpectResourceAction(resourceName, plancheck.ResourceActionUpdate),
					},
				},
				ConfigStateChecks: []statecheck.StateCheck{
					statecheck.ExpectKnownValue(resourceName, tfjsonpath.New("rapid_response"), knownvalue.ObjectPartial(map[string]knownvalue.Check{"ring_assignment": knownvalue.StringExact("pause")})),
				},
			},
			{
				ConfigDirectory: config.StaticDirectory("testdata/content_update_policy"),
				ConfigVariables: config.Variables{
					"description":              config.StringVariable(rName),
					"name":                     config.StringVariable(rName),
					"rapid_response":           config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("pause")}),
					"sensor_operations":        config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("ga")}),
					"system_critical":          config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("ga")}),
					"vulnerability_management": config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("ga")}),
				},
				ResourceName:            resourceName,
				ImportState:             true,
				ImportStateVerify:       true,
				ImportStateVerifyIgnore: []string{"last_updated"},
			},
		},
	})
}

func TestAccContentPolicyResource_rapidResponseDelayHours(t *testing.T) {
	rName := acctest.RandomResourceName()
	resourceName := "crowdstrike_content_update_policy.test"

	resource.ParallelTest(t, resource.TestCase{
		PreCheck:                 func() { acctest.PreCheck(t) },
		ProtoV6ProviderFactories: acctest.ProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			{
				ConfigDirectory: config.StaticDirectory("testdata/content_update_policy"),
				ConfigVariables: config.Variables{
					"description":              config.StringVariable(rName),
					"name":                     config.StringVariable(rName),
					"rapid_response":           config.ObjectVariable(map[string]config.Variable{"delay_hours": config.IntegerVariable(0), "ring_assignment": config.StringVariable("ga")}),
					"sensor_operations":        config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("ga")}),
					"system_critical":          config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("ga")}),
					"vulnerability_management": config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("ga")}),
				},
				ConfigStateChecks: []statecheck.StateCheck{
					statecheck.ExpectKnownValue(resourceName, tfjsonpath.New("rapid_response").AtMapKey("delay_hours"), knownvalue.Int64Exact(0)),
				},
			},
			{
				ConfigDirectory: config.StaticDirectory("testdata/content_update_policy"),
				ConfigVariables: config.Variables{
					"description":              config.StringVariable(rName),
					"name":                     config.StringVariable(rName),
					"rapid_response":           config.ObjectVariable(map[string]config.Variable{"delay_hours": config.IntegerVariable(1), "ring_assignment": config.StringVariable("ga")}),
					"sensor_operations":        config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("ga")}),
					"system_critical":          config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("ga")}),
					"vulnerability_management": config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("ga")}),
				},
				ConfigPlanChecks: resource.ConfigPlanChecks{
					PreApply: []plancheck.PlanCheck{
						plancheck.ExpectResourceAction(resourceName, plancheck.ResourceActionUpdate),
					},
				},
				ConfigStateChecks: []statecheck.StateCheck{
					statecheck.ExpectKnownValue(resourceName, tfjsonpath.New("rapid_response").AtMapKey("delay_hours"), knownvalue.Int64Exact(1)),
				},
			},
			{
				ConfigDirectory: config.StaticDirectory("testdata/content_update_policy"),
				ConfigVariables: config.Variables{
					"description":              config.StringVariable(rName),
					"name":                     config.StringVariable(rName),
					"rapid_response":           config.ObjectVariable(map[string]config.Variable{"delay_hours": config.IntegerVariable(2), "ring_assignment": config.StringVariable("ga")}),
					"sensor_operations":        config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("ga")}),
					"system_critical":          config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("ga")}),
					"vulnerability_management": config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("ga")}),
				},
				ConfigPlanChecks: resource.ConfigPlanChecks{
					PreApply: []plancheck.PlanCheck{
						plancheck.ExpectResourceAction(resourceName, plancheck.ResourceActionUpdate),
					},
				},
				ConfigStateChecks: []statecheck.StateCheck{
					statecheck.ExpectKnownValue(resourceName, tfjsonpath.New("rapid_response").AtMapKey("delay_hours"), knownvalue.Int64Exact(2)),
				},
			},
			{
				ConfigDirectory: config.StaticDirectory("testdata/content_update_policy"),
				ConfigVariables: config.Variables{
					"description":              config.StringVariable(rName),
					"name":                     config.StringVariable(rName),
					"rapid_response":           config.ObjectVariable(map[string]config.Variable{"delay_hours": config.IntegerVariable(4), "ring_assignment": config.StringVariable("ga")}),
					"sensor_operations":        config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("ga")}),
					"system_critical":          config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("ga")}),
					"vulnerability_management": config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("ga")}),
				},
				ConfigPlanChecks: resource.ConfigPlanChecks{
					PreApply: []plancheck.PlanCheck{
						plancheck.ExpectResourceAction(resourceName, plancheck.ResourceActionUpdate),
					},
				},
				ConfigStateChecks: []statecheck.StateCheck{
					statecheck.ExpectKnownValue(resourceName, tfjsonpath.New("rapid_response").AtMapKey("delay_hours"), knownvalue.Int64Exact(4)),
				},
			},
			{
				ConfigDirectory: config.StaticDirectory("testdata/content_update_policy"),
				ConfigVariables: config.Variables{
					"description":              config.StringVariable(rName),
					"name":                     config.StringVariable(rName),
					"rapid_response":           config.ObjectVariable(map[string]config.Variable{"delay_hours": config.IntegerVariable(8), "ring_assignment": config.StringVariable("ga")}),
					"sensor_operations":        config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("ga")}),
					"system_critical":          config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("ga")}),
					"vulnerability_management": config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("ga")}),
				},
				ConfigPlanChecks: resource.ConfigPlanChecks{
					PreApply: []plancheck.PlanCheck{
						plancheck.ExpectResourceAction(resourceName, plancheck.ResourceActionUpdate),
					},
				},
				ConfigStateChecks: []statecheck.StateCheck{
					statecheck.ExpectKnownValue(resourceName, tfjsonpath.New("rapid_response").AtMapKey("delay_hours"), knownvalue.Int64Exact(8)),
				},
			},
			{
				ConfigDirectory: config.StaticDirectory("testdata/content_update_policy"),
				ConfigVariables: config.Variables{
					"description":              config.StringVariable(rName),
					"name":                     config.StringVariable(rName),
					"rapid_response":           config.ObjectVariable(map[string]config.Variable{"delay_hours": config.IntegerVariable(12), "ring_assignment": config.StringVariable("ga")}),
					"sensor_operations":        config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("ga")}),
					"system_critical":          config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("ga")}),
					"vulnerability_management": config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("ga")}),
				},
				ConfigPlanChecks: resource.ConfigPlanChecks{
					PreApply: []plancheck.PlanCheck{
						plancheck.ExpectResourceAction(resourceName, plancheck.ResourceActionUpdate),
					},
				},
				ConfigStateChecks: []statecheck.StateCheck{
					statecheck.ExpectKnownValue(resourceName, tfjsonpath.New("rapid_response").AtMapKey("delay_hours"), knownvalue.Int64Exact(12)),
				},
			},
			{
				ConfigDirectory: config.StaticDirectory("testdata/content_update_policy"),
				ConfigVariables: config.Variables{
					"description":              config.StringVariable(rName),
					"name":                     config.StringVariable(rName),
					"rapid_response":           config.ObjectVariable(map[string]config.Variable{"delay_hours": config.IntegerVariable(24), "ring_assignment": config.StringVariable("ga")}),
					"sensor_operations":        config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("ga")}),
					"system_critical":          config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("ga")}),
					"vulnerability_management": config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("ga")}),
				},
				ConfigPlanChecks: resource.ConfigPlanChecks{
					PreApply: []plancheck.PlanCheck{
						plancheck.ExpectResourceAction(resourceName, plancheck.ResourceActionUpdate),
					},
				},
				ConfigStateChecks: []statecheck.StateCheck{
					statecheck.ExpectKnownValue(resourceName, tfjsonpath.New("rapid_response").AtMapKey("delay_hours"), knownvalue.Int64Exact(24)),
				},
			},
			{
				ConfigDirectory: config.StaticDirectory("testdata/content_update_policy"),
				ConfigVariables: config.Variables{
					"description":              config.StringVariable(rName),
					"name":                     config.StringVariable(rName),
					"rapid_response":           config.ObjectVariable(map[string]config.Variable{"delay_hours": config.IntegerVariable(48), "ring_assignment": config.StringVariable("ga")}),
					"sensor_operations":        config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("ga")}),
					"system_critical":          config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("ga")}),
					"vulnerability_management": config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("ga")}),
				},
				ConfigPlanChecks: resource.ConfigPlanChecks{
					PreApply: []plancheck.PlanCheck{
						plancheck.ExpectResourceAction(resourceName, plancheck.ResourceActionUpdate),
					},
				},
				ConfigStateChecks: []statecheck.StateCheck{
					statecheck.ExpectKnownValue(resourceName, tfjsonpath.New("rapid_response").AtMapKey("delay_hours"), knownvalue.Int64Exact(48)),
				},
			},
			{
				ConfigDirectory: config.StaticDirectory("testdata/content_update_policy"),
				ConfigVariables: config.Variables{
					"description":              config.StringVariable(rName),
					"name":                     config.StringVariable(rName),
					"rapid_response":           config.ObjectVariable(map[string]config.Variable{"delay_hours": config.IntegerVariable(72), "ring_assignment": config.StringVariable("ga")}),
					"sensor_operations":        config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("ga")}),
					"system_critical":          config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("ga")}),
					"vulnerability_management": config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("ga")}),
				},
				ConfigPlanChecks: resource.ConfigPlanChecks{
					PreApply: []plancheck.PlanCheck{
						plancheck.ExpectResourceAction(resourceName, plancheck.ResourceActionUpdate),
					},
				},
				ConfigStateChecks: []statecheck.StateCheck{
					statecheck.ExpectKnownValue(resourceName, tfjsonpath.New("rapid_response").AtMapKey("delay_hours"), knownvalue.Int64Exact(72)),
				},
			},
			{
				ConfigDirectory: config.StaticDirectory("testdata/content_update_policy"),
				ConfigVariables: config.Variables{
					"description":              config.StringVariable(rName),
					"name":                     config.StringVariable(rName),
					"rapid_response":           config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("ga")}),
					"sensor_operations":        config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("ga")}),
					"system_critical":          config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("ga")}),
					"vulnerability_management": config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("ga")}),
				},
				ConfigPlanChecks: resource.ConfigPlanChecks{
					PreApply: []plancheck.PlanCheck{
						plancheck.ExpectResourceAction(resourceName, plancheck.ResourceActionUpdate),
					},
				},
				ConfigStateChecks: []statecheck.StateCheck{
					statecheck.ExpectKnownValue(resourceName, tfjsonpath.New("rapid_response").AtMapKey("delay_hours"), knownvalue.Null()),
				},
			},
			{
				ConfigDirectory: config.StaticDirectory("testdata/content_update_policy"),
				ConfigVariables: config.Variables{
					"description":              config.StringVariable(rName),
					"name":                     config.StringVariable(rName),
					"rapid_response":           config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("ga")}),
					"sensor_operations":        config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("ga")}),
					"system_critical":          config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("ga")}),
					"vulnerability_management": config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("ga")}),
				},
				ResourceName:            resourceName,
				ImportState:             true,
				ImportStateVerify:       true,
				ImportStateVerifyIgnore: []string{"last_updated"},
			},
		},
	})
}

func TestAccContentPolicyResource_rapidResponsePinnedContentVersion(t *testing.T) {
	t.Skip("testgen: pinned content versions must exist in the tenant; values from the environment are not supported yet")
}

func TestAccContentPolicyResource_sensorOperations(t *testing.T) {
	rName := acctest.RandomResourceName()
	resourceName := "crowdstrike_content_update_policy.test"

	resource.ParallelTest(t, resource.TestCase{
		PreCheck:                 func() { acctest.PreCheck(t) },
		ProtoV6ProviderFactories: acctest.ProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			{
				ConfigDirectory: config.StaticDirectory("testdata/content_update_policy"),
				ConfigVariables: config.Variables{
					"description":              config.StringVariable(rName),
					"name":                     config.StringVariable(rName),
					"rapid_response":           config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("ga")}),
					"sensor_operations":        config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("ga")}),
					"system_critical":          config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("ga")}),
					"vulnerability_management": config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("ga")}),
				},
				ConfigStateChecks: []statecheck.StateCheck{
					statecheck.ExpectKnownValue(resourceName, tfjsonpath.New("sensor_operations"), knownvalue.ObjectPartial(map[string]knownvalue.Check{"ring_assignment": knownvalue.StringExact("ga")})),
				},
			},
			{
				ConfigDirectory: config.StaticDirectory("testdata/content_update_policy"),
				ConfigVariables: config.Variables{
					"description":              config.StringVariable(rName),
					"name":                     config.StringVariable(rName),
					"rapid_response":           config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("ga")}),
					"sensor_operations":        config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("ea")}),
					"system_critical":          config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("ga")}),
					"vulnerability_management": config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("ga")}),
				},
				ConfigPlanChecks: resource.ConfigPlanChecks{
					PreApply: []plancheck.PlanCheck{
						plancheck.ExpectResourceAction(resourceName, plancheck.ResourceActionUpdate),
					},
				},
				ConfigStateChecks: []statecheck.StateCheck{
					statecheck.ExpectKnownValue(resourceName, tfjsonpath.New("sensor_operations"), knownvalue.ObjectPartial(map[string]knownvalue.Check{"ring_assignment": knownvalue.StringExact("ea")})),
				},
			},
			{
				ConfigDirectory: config.StaticDirectory("testdata/content_update_policy"),
				ConfigVariables: config.Variables{
					"description":              config.StringVariable(rName),
					"name":                     config.StringVariable(rName),
					"rapid_response":           config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("ga")}),
					"sensor_operations":        config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("pause")}),
					"system_critical":          config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("ga")}),
					"vulnerability_management": config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("ga")}),
				},
				ConfigPlanChecks: resource.ConfigPlanChecks{
					PreApply: []plancheck.PlanCheck{
						plancheck.ExpectResourceAction(resourceName, plancheck.ResourceActionUpdate),
					},
				},
				ConfigStateChecks: []statecheck.StateCheck{
					statecheck.ExpectKnownValue(resourceName, tfjsonpath.New("sensor_operations"), knownvalue.ObjectPartial(map[string]knownvalue.Check{"ring_assignment": knownvalue.StringExact("pause")})),
				},
			},
			{
				ConfigDirectory: config.StaticDirectory("testdata/content_update_policy"),
				ConfigVariables: config.Variables{
					"description":              config.StringVariable(rName),
					"name":                     config.StringVariable(rName),
					"rapid_response":           config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("ga")}),
					"sensor_operations":        config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("pause")}),
					"system_critical":          config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("ga")}),
					"vulnerability_management": config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("ga")}),
				},
				ResourceName:            resourceName,
				ImportState:             true,
				ImportStateVerify:       true,
				ImportStateVerifyIgnore: []string{"last_updated"},
			},
		},
	})
}

func TestAccContentPolicyResource_sensorOperationsDelayHours(t *testing.T) {
	rName := acctest.RandomResourceName()
	resourceName := "crowdstrike_content_update_policy.test"

	resource.ParallelTest(t, resource.TestCase{
		PreCheck:                 func() { acctest.PreCheck(t) },
		ProtoV6ProviderFactories: acctest.ProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			{
				ConfigDirectory: config.StaticDirectory("testdata/content_update_policy"),
				ConfigVariables: config.Variables{
					"description":              config.StringVariable(rName),
					"name":                     config.StringVariable(rName),
					"rapid_response":           config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("ga")}),
					"sensor_operations":        config.ObjectVariable(map[string]config.Variable{"delay_hours": config.IntegerVariable(0), "ring_assignment": config.StringVariable("ga")}),
					"system_critical":          config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("ga")}),
					"vulnerability_management": config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("ga")}),
				},
				ConfigStateChecks: []statecheck.StateCheck{
					statecheck.ExpectKnownValue(resourceName, tfjsonpath.New("sensor_operations").AtMapKey("delay_hours"), knownvalue.Int64Exact(0)),
				},
			},
			{
				ConfigDirectory: config.StaticDirectory("testdata/content_update_policy"),
				ConfigVariables: config.Variables{
					"description":              config.StringVariable(rName),
					"name":                     config.StringVariable(rName),
					"rapid_response":           config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("ga")}),
					"sensor_operations":        config.ObjectVariable(map[string]config.Variable{"delay_hours": config.IntegerVariable(1), "ring_assignment": config.StringVariable("ga")}),
					"system_critical":          config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("ga")}),
					"vulnerability_management": config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("ga")}),
				},
				ConfigPlanChecks: resource.ConfigPlanChecks{
					PreApply: []plancheck.PlanCheck{
						plancheck.ExpectResourceAction(resourceName, plancheck.ResourceActionUpdate),
					},
				},
				ConfigStateChecks: []statecheck.StateCheck{
					statecheck.ExpectKnownValue(resourceName, tfjsonpath.New("sensor_operations").AtMapKey("delay_hours"), knownvalue.Int64Exact(1)),
				},
			},
			{
				ConfigDirectory: config.StaticDirectory("testdata/content_update_policy"),
				ConfigVariables: config.Variables{
					"description":              config.StringVariable(rName),
					"name":                     config.StringVariable(rName),
					"rapid_response":           config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("ga")}),
					"sensor_operations":        config.ObjectVariable(map[string]config.Variable{"delay_hours": config.IntegerVariable(2), "ring_assignment": config.StringVariable("ga")}),
					"system_critical":          config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("ga")}),
					"vulnerability_management": config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("ga")}),
				},
				ConfigPlanChecks: resource.ConfigPlanChecks{
					PreApply: []plancheck.PlanCheck{
						plancheck.ExpectResourceAction(resourceName, plancheck.ResourceActionUpdate),
					},
				},
				ConfigStateChecks: []statecheck.StateCheck{
					statecheck.ExpectKnownValue(resourceName, tfjsonpath.New("sensor_operations").AtMapKey("delay_hours"), knownvalue.Int64Exact(2)),
				},
			},
			{
				ConfigDirectory: config.StaticDirectory("testdata/content_update_policy"),
				ConfigVariables: config.Variables{
					"description":              config.StringVariable(rName),
					"name":                     config.StringVariable(rName),
					"rapid_response":           config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("ga")}),
					"sensor_operations":        config.ObjectVariable(map[string]config.Variable{"delay_hours": config.IntegerVariable(4), "ring_assignment": config.StringVariable("ga")}),
					"system_critical":          config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("ga")}),
					"vulnerability_management": config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("ga")}),
				},
				ConfigPlanChecks: resource.ConfigPlanChecks{
					PreApply: []plancheck.PlanCheck{
						plancheck.ExpectResourceAction(resourceName, plancheck.ResourceActionUpdate),
					},
				},
				ConfigStateChecks: []statecheck.StateCheck{
					statecheck.ExpectKnownValue(resourceName, tfjsonpath.New("sensor_operations").AtMapKey("delay_hours"), knownvalue.Int64Exact(4)),
				},
			},
			{
				ConfigDirectory: config.StaticDirectory("testdata/content_update_policy"),
				ConfigVariables: config.Variables{
					"description":              config.StringVariable(rName),
					"name":                     config.StringVariable(rName),
					"rapid_response":           config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("ga")}),
					"sensor_operations":        config.ObjectVariable(map[string]config.Variable{"delay_hours": config.IntegerVariable(8), "ring_assignment": config.StringVariable("ga")}),
					"system_critical":          config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("ga")}),
					"vulnerability_management": config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("ga")}),
				},
				ConfigPlanChecks: resource.ConfigPlanChecks{
					PreApply: []plancheck.PlanCheck{
						plancheck.ExpectResourceAction(resourceName, plancheck.ResourceActionUpdate),
					},
				},
				ConfigStateChecks: []statecheck.StateCheck{
					statecheck.ExpectKnownValue(resourceName, tfjsonpath.New("sensor_operations").AtMapKey("delay_hours"), knownvalue.Int64Exact(8)),
				},
			},
			{
				ConfigDirectory: config.StaticDirectory("testdata/content_update_policy"),
				ConfigVariables: config.Variables{
					"description":              config.StringVariable(rName),
					"name":                     config.StringVariable(rName),
					"rapid_response":           config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("ga")}),
					"sensor_operations":        config.ObjectVariable(map[string]config.Variable{"delay_hours": config.IntegerVariable(12), "ring_assignment": config.StringVariable("ga")}),
					"system_critical":          config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("ga")}),
					"vulnerability_management": config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("ga")}),
				},
				ConfigPlanChecks: resource.ConfigPlanChecks{
					PreApply: []plancheck.PlanCheck{
						plancheck.ExpectResourceAction(resourceName, plancheck.ResourceActionUpdate),
					},
				},
				ConfigStateChecks: []statecheck.StateCheck{
					statecheck.ExpectKnownValue(resourceName, tfjsonpath.New("sensor_operations").AtMapKey("delay_hours"), knownvalue.Int64Exact(12)),
				},
			},
			{
				ConfigDirectory: config.StaticDirectory("testdata/content_update_policy"),
				ConfigVariables: config.Variables{
					"description":              config.StringVariable(rName),
					"name":                     config.StringVariable(rName),
					"rapid_response":           config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("ga")}),
					"sensor_operations":        config.ObjectVariable(map[string]config.Variable{"delay_hours": config.IntegerVariable(24), "ring_assignment": config.StringVariable("ga")}),
					"system_critical":          config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("ga")}),
					"vulnerability_management": config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("ga")}),
				},
				ConfigPlanChecks: resource.ConfigPlanChecks{
					PreApply: []plancheck.PlanCheck{
						plancheck.ExpectResourceAction(resourceName, plancheck.ResourceActionUpdate),
					},
				},
				ConfigStateChecks: []statecheck.StateCheck{
					statecheck.ExpectKnownValue(resourceName, tfjsonpath.New("sensor_operations").AtMapKey("delay_hours"), knownvalue.Int64Exact(24)),
				},
			},
			{
				ConfigDirectory: config.StaticDirectory("testdata/content_update_policy"),
				ConfigVariables: config.Variables{
					"description":              config.StringVariable(rName),
					"name":                     config.StringVariable(rName),
					"rapid_response":           config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("ga")}),
					"sensor_operations":        config.ObjectVariable(map[string]config.Variable{"delay_hours": config.IntegerVariable(48), "ring_assignment": config.StringVariable("ga")}),
					"system_critical":          config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("ga")}),
					"vulnerability_management": config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("ga")}),
				},
				ConfigPlanChecks: resource.ConfigPlanChecks{
					PreApply: []plancheck.PlanCheck{
						plancheck.ExpectResourceAction(resourceName, plancheck.ResourceActionUpdate),
					},
				},
				ConfigStateChecks: []statecheck.StateCheck{
					statecheck.ExpectKnownValue(resourceName, tfjsonpath.New("sensor_operations").AtMapKey("delay_hours"), knownvalue.Int64Exact(48)),
				},
			},
			{
				ConfigDirectory: config.StaticDirectory("testdata/content_update_policy"),
				ConfigVariables: config.Variables{
					"description":              config.StringVariable(rName),
					"name":                     config.StringVariable(rName),
					"rapid_response":           config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("ga")}),
					"sensor_operations":        config.ObjectVariable(map[string]config.Variable{"delay_hours": config.IntegerVariable(72), "ring_assignment": config.StringVariable("ga")}),
					"system_critical":          config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("ga")}),
					"vulnerability_management": config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("ga")}),
				},
				ConfigPlanChecks: resource.ConfigPlanChecks{
					PreApply: []plancheck.PlanCheck{
						plancheck.ExpectResourceAction(resourceName, plancheck.ResourceActionUpdate),
					},
				},
				ConfigStateChecks: []statecheck.StateCheck{
					statecheck.ExpectKnownValue(resourceName, tfjsonpath.New("sensor_operations").AtMapKey("delay_hours"), knownvalue.Int64Exact(72)),
				},
			},
			{
				ConfigDirectory: config.StaticDirectory("testdata/content_update_policy"),
				ConfigVariables: config.Variables{
					"description":              config.StringVariable(rName),
					"name":                     config.StringVariable(rName),
					"rapid_response":           config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("ga")}),
					"sensor_operations":        config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("ga")}),
					"system_critical":          config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("ga")}),
					"vulnerability_management": config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("ga")}),
				},
				ConfigPlanChecks: resource.ConfigPlanChecks{
					PreApply: []plancheck.PlanCheck{
						plancheck.ExpectResourceAction(resourceName, plancheck.ResourceActionUpdate),
					},
				},
				ConfigStateChecks: []statecheck.StateCheck{
					statecheck.ExpectKnownValue(resourceName, tfjsonpath.New("sensor_operations").AtMapKey("delay_hours"), knownvalue.Null()),
				},
			},
			{
				ConfigDirectory: config.StaticDirectory("testdata/content_update_policy"),
				ConfigVariables: config.Variables{
					"description":              config.StringVariable(rName),
					"name":                     config.StringVariable(rName),
					"rapid_response":           config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("ga")}),
					"sensor_operations":        config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("ga")}),
					"system_critical":          config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("ga")}),
					"vulnerability_management": config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("ga")}),
				},
				ResourceName:            resourceName,
				ImportState:             true,
				ImportStateVerify:       true,
				ImportStateVerifyIgnore: []string{"last_updated"},
			},
		},
	})
}

func TestAccContentPolicyResource_sensorOperationsPinnedContentVersion(t *testing.T) {
	t.Skip("testgen: pinned content versions must exist in the tenant; values from the environment are not supported yet")
}

func TestAccContentPolicyResource_systemCritical(t *testing.T) {
	rName := acctest.RandomResourceName()
	resourceName := "crowdstrike_content_update_policy.test"

	resource.ParallelTest(t, resource.TestCase{
		PreCheck:                 func() { acctest.PreCheck(t) },
		ProtoV6ProviderFactories: acctest.ProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			{
				ConfigDirectory: config.StaticDirectory("testdata/content_update_policy"),
				ConfigVariables: config.Variables{
					"description":              config.StringVariable(rName),
					"name":                     config.StringVariable(rName),
					"rapid_response":           config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("ga")}),
					"sensor_operations":        config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("ga")}),
					"system_critical":          config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("ga")}),
					"vulnerability_management": config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("ga")}),
				},
				ConfigStateChecks: []statecheck.StateCheck{
					statecheck.ExpectKnownValue(resourceName, tfjsonpath.New("system_critical"), knownvalue.ObjectPartial(map[string]knownvalue.Check{"ring_assignment": knownvalue.StringExact("ga")})),
				},
			},
			{
				ConfigDirectory: config.StaticDirectory("testdata/content_update_policy"),
				ConfigVariables: config.Variables{
					"description":              config.StringVariable(rName),
					"name":                     config.StringVariable(rName),
					"rapid_response":           config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("ga")}),
					"sensor_operations":        config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("ga")}),
					"system_critical":          config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("ea")}),
					"vulnerability_management": config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("ga")}),
				},
				ConfigPlanChecks: resource.ConfigPlanChecks{
					PreApply: []plancheck.PlanCheck{
						plancheck.ExpectResourceAction(resourceName, plancheck.ResourceActionUpdate),
					},
				},
				ConfigStateChecks: []statecheck.StateCheck{
					statecheck.ExpectKnownValue(resourceName, tfjsonpath.New("system_critical"), knownvalue.ObjectPartial(map[string]knownvalue.Check{"ring_assignment": knownvalue.StringExact("ea")})),
				},
			},
			{
				ConfigDirectory: config.StaticDirectory("testdata/content_update_policy"),
				ConfigVariables: config.Variables{
					"description":              config.StringVariable(rName),
					"name":                     config.StringVariable(rName),
					"rapid_response":           config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("ga")}),
					"sensor_operations":        config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("ga")}),
					"system_critical":          config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("ea")}),
					"vulnerability_management": config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("ga")}),
				},
				ResourceName:            resourceName,
				ImportState:             true,
				ImportStateVerify:       true,
				ImportStateVerifyIgnore: []string{"last_updated"},
			},
		},
	})
}

func TestAccContentPolicyResource_systemCriticalDelayHours(t *testing.T) {
	rName := acctest.RandomResourceName()
	resourceName := "crowdstrike_content_update_policy.test"

	resource.ParallelTest(t, resource.TestCase{
		PreCheck:                 func() { acctest.PreCheck(t) },
		ProtoV6ProviderFactories: acctest.ProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			{
				ConfigDirectory: config.StaticDirectory("testdata/content_update_policy"),
				ConfigVariables: config.Variables{
					"description":              config.StringVariable(rName),
					"name":                     config.StringVariable(rName),
					"rapid_response":           config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("ga")}),
					"sensor_operations":        config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("ga")}),
					"system_critical":          config.ObjectVariable(map[string]config.Variable{"delay_hours": config.IntegerVariable(0), "ring_assignment": config.StringVariable("ga")}),
					"vulnerability_management": config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("ga")}),
				},
				ConfigStateChecks: []statecheck.StateCheck{
					statecheck.ExpectKnownValue(resourceName, tfjsonpath.New("system_critical").AtMapKey("delay_hours"), knownvalue.Int64Exact(0)),
				},
			},
			{
				ConfigDirectory: config.StaticDirectory("testdata/content_update_policy"),
				ConfigVariables: config.Variables{
					"description":              config.StringVariable(rName),
					"name":                     config.StringVariable(rName),
					"rapid_response":           config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("ga")}),
					"sensor_operations":        config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("ga")}),
					"system_critical":          config.ObjectVariable(map[string]config.Variable{"delay_hours": config.IntegerVariable(1), "ring_assignment": config.StringVariable("ga")}),
					"vulnerability_management": config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("ga")}),
				},
				ConfigPlanChecks: resource.ConfigPlanChecks{
					PreApply: []plancheck.PlanCheck{
						plancheck.ExpectResourceAction(resourceName, plancheck.ResourceActionUpdate),
					},
				},
				ConfigStateChecks: []statecheck.StateCheck{
					statecheck.ExpectKnownValue(resourceName, tfjsonpath.New("system_critical").AtMapKey("delay_hours"), knownvalue.Int64Exact(1)),
				},
			},
			{
				ConfigDirectory: config.StaticDirectory("testdata/content_update_policy"),
				ConfigVariables: config.Variables{
					"description":              config.StringVariable(rName),
					"name":                     config.StringVariable(rName),
					"rapid_response":           config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("ga")}),
					"sensor_operations":        config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("ga")}),
					"system_critical":          config.ObjectVariable(map[string]config.Variable{"delay_hours": config.IntegerVariable(2), "ring_assignment": config.StringVariable("ga")}),
					"vulnerability_management": config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("ga")}),
				},
				ConfigPlanChecks: resource.ConfigPlanChecks{
					PreApply: []plancheck.PlanCheck{
						plancheck.ExpectResourceAction(resourceName, plancheck.ResourceActionUpdate),
					},
				},
				ConfigStateChecks: []statecheck.StateCheck{
					statecheck.ExpectKnownValue(resourceName, tfjsonpath.New("system_critical").AtMapKey("delay_hours"), knownvalue.Int64Exact(2)),
				},
			},
			{
				ConfigDirectory: config.StaticDirectory("testdata/content_update_policy"),
				ConfigVariables: config.Variables{
					"description":              config.StringVariable(rName),
					"name":                     config.StringVariable(rName),
					"rapid_response":           config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("ga")}),
					"sensor_operations":        config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("ga")}),
					"system_critical":          config.ObjectVariable(map[string]config.Variable{"delay_hours": config.IntegerVariable(4), "ring_assignment": config.StringVariable("ga")}),
					"vulnerability_management": config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("ga")}),
				},
				ConfigPlanChecks: resource.ConfigPlanChecks{
					PreApply: []plancheck.PlanCheck{
						plancheck.ExpectResourceAction(resourceName, plancheck.ResourceActionUpdate),
					},
				},
				ConfigStateChecks: []statecheck.StateCheck{
					statecheck.ExpectKnownValue(resourceName, tfjsonpath.New("system_critical").AtMapKey("delay_hours"), knownvalue.Int64Exact(4)),
				},
			},
			{
				ConfigDirectory: config.StaticDirectory("testdata/content_update_policy"),
				ConfigVariables: config.Variables{
					"description":              config.StringVariable(rName),
					"name":                     config.StringVariable(rName),
					"rapid_response":           config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("ga")}),
					"sensor_operations":        config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("ga")}),
					"system_critical":          config.ObjectVariable(map[string]config.Variable{"delay_hours": config.IntegerVariable(8), "ring_assignment": config.StringVariable("ga")}),
					"vulnerability_management": config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("ga")}),
				},
				ConfigPlanChecks: resource.ConfigPlanChecks{
					PreApply: []plancheck.PlanCheck{
						plancheck.ExpectResourceAction(resourceName, plancheck.ResourceActionUpdate),
					},
				},
				ConfigStateChecks: []statecheck.StateCheck{
					statecheck.ExpectKnownValue(resourceName, tfjsonpath.New("system_critical").AtMapKey("delay_hours"), knownvalue.Int64Exact(8)),
				},
			},
			{
				ConfigDirectory: config.StaticDirectory("testdata/content_update_policy"),
				ConfigVariables: config.Variables{
					"description":              config.StringVariable(rName),
					"name":                     config.StringVariable(rName),
					"rapid_response":           config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("ga")}),
					"sensor_operations":        config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("ga")}),
					"system_critical":          config.ObjectVariable(map[string]config.Variable{"delay_hours": config.IntegerVariable(12), "ring_assignment": config.StringVariable("ga")}),
					"vulnerability_management": config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("ga")}),
				},
				ConfigPlanChecks: resource.ConfigPlanChecks{
					PreApply: []plancheck.PlanCheck{
						plancheck.ExpectResourceAction(resourceName, plancheck.ResourceActionUpdate),
					},
				},
				ConfigStateChecks: []statecheck.StateCheck{
					statecheck.ExpectKnownValue(resourceName, tfjsonpath.New("system_critical").AtMapKey("delay_hours"), knownvalue.Int64Exact(12)),
				},
			},
			{
				ConfigDirectory: config.StaticDirectory("testdata/content_update_policy"),
				ConfigVariables: config.Variables{
					"description":              config.StringVariable(rName),
					"name":                     config.StringVariable(rName),
					"rapid_response":           config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("ga")}),
					"sensor_operations":        config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("ga")}),
					"system_critical":          config.ObjectVariable(map[string]config.Variable{"delay_hours": config.IntegerVariable(24), "ring_assignment": config.StringVariable("ga")}),
					"vulnerability_management": config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("ga")}),
				},
				ConfigPlanChecks: resource.ConfigPlanChecks{
					PreApply: []plancheck.PlanCheck{
						plancheck.ExpectResourceAction(resourceName, plancheck.ResourceActionUpdate),
					},
				},
				ConfigStateChecks: []statecheck.StateCheck{
					statecheck.ExpectKnownValue(resourceName, tfjsonpath.New("system_critical").AtMapKey("delay_hours"), knownvalue.Int64Exact(24)),
				},
			},
			{
				ConfigDirectory: config.StaticDirectory("testdata/content_update_policy"),
				ConfigVariables: config.Variables{
					"description":              config.StringVariable(rName),
					"name":                     config.StringVariable(rName),
					"rapid_response":           config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("ga")}),
					"sensor_operations":        config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("ga")}),
					"system_critical":          config.ObjectVariable(map[string]config.Variable{"delay_hours": config.IntegerVariable(48), "ring_assignment": config.StringVariable("ga")}),
					"vulnerability_management": config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("ga")}),
				},
				ConfigPlanChecks: resource.ConfigPlanChecks{
					PreApply: []plancheck.PlanCheck{
						plancheck.ExpectResourceAction(resourceName, plancheck.ResourceActionUpdate),
					},
				},
				ConfigStateChecks: []statecheck.StateCheck{
					statecheck.ExpectKnownValue(resourceName, tfjsonpath.New("system_critical").AtMapKey("delay_hours"), knownvalue.Int64Exact(48)),
				},
			},
			{
				ConfigDirectory: config.StaticDirectory("testdata/content_update_policy"),
				ConfigVariables: config.Variables{
					"description":              config.StringVariable(rName),
					"name":                     config.StringVariable(rName),
					"rapid_response":           config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("ga")}),
					"sensor_operations":        config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("ga")}),
					"system_critical":          config.ObjectVariable(map[string]config.Variable{"delay_hours": config.IntegerVariable(72), "ring_assignment": config.StringVariable("ga")}),
					"vulnerability_management": config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("ga")}),
				},
				ConfigPlanChecks: resource.ConfigPlanChecks{
					PreApply: []plancheck.PlanCheck{
						plancheck.ExpectResourceAction(resourceName, plancheck.ResourceActionUpdate),
					},
				},
				ConfigStateChecks: []statecheck.StateCheck{
					statecheck.ExpectKnownValue(resourceName, tfjsonpath.New("system_critical").AtMapKey("delay_hours"), knownvalue.Int64Exact(72)),
				},
			},
			{
				ConfigDirectory: config.StaticDirectory("testdata/content_update_policy"),
				ConfigVariables: config.Variables{
					"description":              config.StringVariable(rName),
					"name":                     config.StringVariable(rName),
					"rapid_response":           config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("ga")}),
					"sensor_operations":        config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("ga")}),
					"system_critical":          config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("ga")}),
					"vulnerability_management": config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("ga")}),
				},
				ConfigPlanChecks: resource.ConfigPlanChecks{
					PreApply: []plancheck.PlanCheck{
						plancheck.ExpectResourceAction(resourceName, plancheck.ResourceActionUpdate),
					},
				},
				ConfigStateChecks: []statecheck.StateCheck{
					statecheck.ExpectKnownValue(resourceName, tfjsonpath.New("system_critical").AtMapKey("delay_hours"), knownvalue.Null()),
				},
			},
			{
				ConfigDirectory: config.StaticDirectory("testdata/content_update_policy"),
				ConfigVariables: config.Variables{
					"description":              config.StringVariable(rName),
					"name":                     config.StringVariable(rName),
					"rapid_response":           config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("ga")}),
					"sensor_operations":        config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("ga")}),
					"system_critical":          config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("ga")}),
					"vulnerability_management": config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("ga")}),
				},
				ResourceName:            resourceName,
				ImportState:             true,
				ImportStateVerify:       true,
				ImportStateVerifyIgnore: []string{"last_updated"},
			},
		},
	})
}

func TestAccContentPolicyResource_systemCriticalPinnedContentVersion(t *testing.T) {
	t.Skip("testgen: pinned content versions must exist in the tenant; values from the environment are not supported yet")
}

func TestAccContentPolicyResource_vulnerabilityManagement(t *testing.T) {
	rName := acctest.RandomResourceName()
	resourceName := "crowdstrike_content_update_policy.test"

	resource.ParallelTest(t, resource.TestCase{
		PreCheck:                 func() { acctest.PreCheck(t) },
		ProtoV6ProviderFactories: acctest.ProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			{
				ConfigDirectory: config.StaticDirectory("testdata/content_update_policy"),
				ConfigVariables: config.Variables{
					"description":              config.StringVariable(rName),
					"name":                     config.StringVariable(rName),
					"rapid_response":           config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("ga")}),
					"sensor_operations":        config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("ga")}),
					"system_critical":          config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("ga")}),
					"vulnerability_management": config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("ga")}),
				},
				ConfigStateChecks: []statecheck.StateCheck{
					statecheck.ExpectKnownValue(resourceName, tfjsonpath.New("vulnerability_management"), knownvalue.ObjectPartial(map[string]knownvalue.Check{"ring_assignment": knownvalue.StringExact("ga")})),
				},
			},
			{
				ConfigDirectory: config.StaticDirectory("testdata/content_update_policy"),
				ConfigVariables: config.Variables{
					"description":              config.StringVariable(rName),
					"name":                     config.StringVariable(rName),
					"rapid_response":           config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("ga")}),
					"sensor_operations":        config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("ga")}),
					"system_critical":          config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("ga")}),
					"vulnerability_management": config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("ea")}),
				},
				ConfigPlanChecks: resource.ConfigPlanChecks{
					PreApply: []plancheck.PlanCheck{
						plancheck.ExpectResourceAction(resourceName, plancheck.ResourceActionUpdate),
					},
				},
				ConfigStateChecks: []statecheck.StateCheck{
					statecheck.ExpectKnownValue(resourceName, tfjsonpath.New("vulnerability_management"), knownvalue.ObjectPartial(map[string]knownvalue.Check{"ring_assignment": knownvalue.StringExact("ea")})),
				},
			},
			{
				ConfigDirectory: config.StaticDirectory("testdata/content_update_policy"),
				ConfigVariables: config.Variables{
					"description":              config.StringVariable(rName),
					"name":                     config.StringVariable(rName),
					"rapid_response":           config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("ga")}),
					"sensor_operations":        config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("ga")}),
					"system_critical":          config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("ga")}),
					"vulnerability_management": config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("pause")}),
				},
				ConfigPlanChecks: resource.ConfigPlanChecks{
					PreApply: []plancheck.PlanCheck{
						plancheck.ExpectResourceAction(resourceName, plancheck.ResourceActionUpdate),
					},
				},
				ConfigStateChecks: []statecheck.StateCheck{
					statecheck.ExpectKnownValue(resourceName, tfjsonpath.New("vulnerability_management"), knownvalue.ObjectPartial(map[string]knownvalue.Check{"ring_assignment": knownvalue.StringExact("pause")})),
				},
			},
			{
				ConfigDirectory: config.StaticDirectory("testdata/content_update_policy"),
				ConfigVariables: config.Variables{
					"description":              config.StringVariable(rName),
					"name":                     config.StringVariable(rName),
					"rapid_response":           config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("ga")}),
					"sensor_operations":        config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("ga")}),
					"system_critical":          config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("ga")}),
					"vulnerability_management": config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("pause")}),
				},
				ResourceName:            resourceName,
				ImportState:             true,
				ImportStateVerify:       true,
				ImportStateVerifyIgnore: []string{"last_updated"},
			},
		},
	})
}

func TestAccContentPolicyResource_vulnerabilityManagementDelayHours(t *testing.T) {
	rName := acctest.RandomResourceName()
	resourceName := "crowdstrike_content_update_policy.test"

	resource.ParallelTest(t, resource.TestCase{
		PreCheck:                 func() { acctest.PreCheck(t) },
		ProtoV6ProviderFactories: acctest.ProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			{
				ConfigDirectory: config.StaticDirectory("testdata/content_update_policy"),
				ConfigVariables: config.Variables{
					"description":              config.StringVariable(rName),
					"name":                     config.StringVariable(rName),
					"rapid_response":           config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("ga")}),
					"sensor_operations":        config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("ga")}),
					"system_critical":          config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("ga")}),
					"vulnerability_management": config.ObjectVariable(map[string]config.Variable{"delay_hours": config.IntegerVariable(0), "ring_assignment": config.StringVariable("ga")}),
				},
				ConfigStateChecks: []statecheck.StateCheck{
					statecheck.ExpectKnownValue(resourceName, tfjsonpath.New("vulnerability_management").AtMapKey("delay_hours"), knownvalue.Int64Exact(0)),
				},
			},
			{
				ConfigDirectory: config.StaticDirectory("testdata/content_update_policy"),
				ConfigVariables: config.Variables{
					"description":              config.StringVariable(rName),
					"name":                     config.StringVariable(rName),
					"rapid_response":           config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("ga")}),
					"sensor_operations":        config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("ga")}),
					"system_critical":          config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("ga")}),
					"vulnerability_management": config.ObjectVariable(map[string]config.Variable{"delay_hours": config.IntegerVariable(1), "ring_assignment": config.StringVariable("ga")}),
				},
				ConfigPlanChecks: resource.ConfigPlanChecks{
					PreApply: []plancheck.PlanCheck{
						plancheck.ExpectResourceAction(resourceName, plancheck.ResourceActionUpdate),
					},
				},
				ConfigStateChecks: []statecheck.StateCheck{
					statecheck.ExpectKnownValue(resourceName, tfjsonpath.New("vulnerability_management").AtMapKey("delay_hours"), knownvalue.Int64Exact(1)),
				},
			},
			{
				ConfigDirectory: config.StaticDirectory("testdata/content_update_policy"),
				ConfigVariables: config.Variables{
					"description":              config.StringVariable(rName),
					"name":                     config.StringVariable(rName),
					"rapid_response":           config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("ga")}),
					"sensor_operations":        config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("ga")}),
					"system_critical":          config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("ga")}),
					"vulnerability_management": config.ObjectVariable(map[string]config.Variable{"delay_hours": config.IntegerVariable(2), "ring_assignment": config.StringVariable("ga")}),
				},
				ConfigPlanChecks: resource.ConfigPlanChecks{
					PreApply: []plancheck.PlanCheck{
						plancheck.ExpectResourceAction(resourceName, plancheck.ResourceActionUpdate),
					},
				},
				ConfigStateChecks: []statecheck.StateCheck{
					statecheck.ExpectKnownValue(resourceName, tfjsonpath.New("vulnerability_management").AtMapKey("delay_hours"), knownvalue.Int64Exact(2)),
				},
			},
			{
				ConfigDirectory: config.StaticDirectory("testdata/content_update_policy"),
				ConfigVariables: config.Variables{
					"description":              config.StringVariable(rName),
					"name":                     config.StringVariable(rName),
					"rapid_response":           config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("ga")}),
					"sensor_operations":        config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("ga")}),
					"system_critical":          config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("ga")}),
					"vulnerability_management": config.ObjectVariable(map[string]config.Variable{"delay_hours": config.IntegerVariable(4), "ring_assignment": config.StringVariable("ga")}),
				},
				ConfigPlanChecks: resource.ConfigPlanChecks{
					PreApply: []plancheck.PlanCheck{
						plancheck.ExpectResourceAction(resourceName, plancheck.ResourceActionUpdate),
					},
				},
				ConfigStateChecks: []statecheck.StateCheck{
					statecheck.ExpectKnownValue(resourceName, tfjsonpath.New("vulnerability_management").AtMapKey("delay_hours"), knownvalue.Int64Exact(4)),
				},
			},
			{
				ConfigDirectory: config.StaticDirectory("testdata/content_update_policy"),
				ConfigVariables: config.Variables{
					"description":              config.StringVariable(rName),
					"name":                     config.StringVariable(rName),
					"rapid_response":           config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("ga")}),
					"sensor_operations":        config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("ga")}),
					"system_critical":          config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("ga")}),
					"vulnerability_management": config.ObjectVariable(map[string]config.Variable{"delay_hours": config.IntegerVariable(8), "ring_assignment": config.StringVariable("ga")}),
				},
				ConfigPlanChecks: resource.ConfigPlanChecks{
					PreApply: []plancheck.PlanCheck{
						plancheck.ExpectResourceAction(resourceName, plancheck.ResourceActionUpdate),
					},
				},
				ConfigStateChecks: []statecheck.StateCheck{
					statecheck.ExpectKnownValue(resourceName, tfjsonpath.New("vulnerability_management").AtMapKey("delay_hours"), knownvalue.Int64Exact(8)),
				},
			},
			{
				ConfigDirectory: config.StaticDirectory("testdata/content_update_policy"),
				ConfigVariables: config.Variables{
					"description":              config.StringVariable(rName),
					"name":                     config.StringVariable(rName),
					"rapid_response":           config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("ga")}),
					"sensor_operations":        config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("ga")}),
					"system_critical":          config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("ga")}),
					"vulnerability_management": config.ObjectVariable(map[string]config.Variable{"delay_hours": config.IntegerVariable(12), "ring_assignment": config.StringVariable("ga")}),
				},
				ConfigPlanChecks: resource.ConfigPlanChecks{
					PreApply: []plancheck.PlanCheck{
						plancheck.ExpectResourceAction(resourceName, plancheck.ResourceActionUpdate),
					},
				},
				ConfigStateChecks: []statecheck.StateCheck{
					statecheck.ExpectKnownValue(resourceName, tfjsonpath.New("vulnerability_management").AtMapKey("delay_hours"), knownvalue.Int64Exact(12)),
				},
			},
			{
				ConfigDirectory: config.StaticDirectory("testdata/content_update_policy"),
				ConfigVariables: config.Variables{
					"description":              config.StringVariable(rName),
					"name":                     config.StringVariable(rName),
					"rapid_response":           config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("ga")}),
					"sensor_operations":        config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("ga")}),
					"system_critical":          config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("ga")}),
					"vulnerability_management": config.ObjectVariable(map[string]config.Variable{"delay_hours": config.IntegerVariable(24), "ring_assignment": config.StringVariable("ga")}),
				},
				ConfigPlanChecks: resource.ConfigPlanChecks{
					PreApply: []plancheck.PlanCheck{
						plancheck.ExpectResourceAction(resourceName, plancheck.ResourceActionUpdate),
					},
				},
				ConfigStateChecks: []statecheck.StateCheck{
					statecheck.ExpectKnownValue(resourceName, tfjsonpath.New("vulnerability_management").AtMapKey("delay_hours"), knownvalue.Int64Exact(24)),
				},
			},
			{
				ConfigDirectory: config.StaticDirectory("testdata/content_update_policy"),
				ConfigVariables: config.Variables{
					"description":              config.StringVariable(rName),
					"name":                     config.StringVariable(rName),
					"rapid_response":           config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("ga")}),
					"sensor_operations":        config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("ga")}),
					"system_critical":          config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("ga")}),
					"vulnerability_management": config.ObjectVariable(map[string]config.Variable{"delay_hours": config.IntegerVariable(48), "ring_assignment": config.StringVariable("ga")}),
				},
				ConfigPlanChecks: resource.ConfigPlanChecks{
					PreApply: []plancheck.PlanCheck{
						plancheck.ExpectResourceAction(resourceName, plancheck.ResourceActionUpdate),
					},
				},
				ConfigStateChecks: []statecheck.StateCheck{
					statecheck.ExpectKnownValue(resourceName, tfjsonpath.New("vulnerability_management").AtMapKey("delay_hours"), knownvalue.Int64Exact(48)),
				},
			},
			{
				ConfigDirectory: config.StaticDirectory("testdata/content_update_policy"),
				ConfigVariables: config.Variables{
					"description":              config.StringVariable(rName),
					"name":                     config.StringVariable(rName),
					"rapid_response":           config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("ga")}),
					"sensor_operations":        config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("ga")}),
					"system_critical":          config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("ga")}),
					"vulnerability_management": config.ObjectVariable(map[string]config.Variable{"delay_hours": config.IntegerVariable(72), "ring_assignment": config.StringVariable("ga")}),
				},
				ConfigPlanChecks: resource.ConfigPlanChecks{
					PreApply: []plancheck.PlanCheck{
						plancheck.ExpectResourceAction(resourceName, plancheck.ResourceActionUpdate),
					},
				},
				ConfigStateChecks: []statecheck.StateCheck{
					statecheck.ExpectKnownValue(resourceName, tfjsonpath.New("vulnerability_management").AtMapKey("delay_hours"), knownvalue.Int64Exact(72)),
				},
			},
			{
				ConfigDirectory: config.StaticDirectory("testdata/content_update_policy"),
				ConfigVariables: config.Variables{
					"description":              config.StringVariable(rName),
					"name":                     config.StringVariable(rName),
					"rapid_response":           config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("ga")}),
					"sensor_operations":        config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("ga")}),
					"system_critical":          config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("ga")}),
					"vulnerability_management": config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("ga")}),
				},
				ConfigPlanChecks: resource.ConfigPlanChecks{
					PreApply: []plancheck.PlanCheck{
						plancheck.ExpectResourceAction(resourceName, plancheck.ResourceActionUpdate),
					},
				},
				ConfigStateChecks: []statecheck.StateCheck{
					statecheck.ExpectKnownValue(resourceName, tfjsonpath.New("vulnerability_management").AtMapKey("delay_hours"), knownvalue.Null()),
				},
			},
			{
				ConfigDirectory: config.StaticDirectory("testdata/content_update_policy"),
				ConfigVariables: config.Variables{
					"description":              config.StringVariable(rName),
					"name":                     config.StringVariable(rName),
					"rapid_response":           config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("ga")}),
					"sensor_operations":        config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("ga")}),
					"system_critical":          config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("ga")}),
					"vulnerability_management": config.ObjectVariable(map[string]config.Variable{"ring_assignment": config.StringVariable("ga")}),
				},
				ResourceName:            resourceName,
				ImportState:             true,
				ImportStateVerify:       true,
				ImportStateVerifyIgnore: []string{"last_updated"},
			},
		},
	})
}

func TestAccContentPolicyResource_vulnerabilityManagementPinnedContentVersion(t *testing.T) {
	t.Skip("testgen: pinned content versions must exist in the tenant; values from the environment are not supported yet")
}
