---
issues:
  max-per-linter: 0
  max-same-issues: 0
  fix: true
linters:
  enable:
    - durationcheck
    - errcheck
    - forcetypeassert
    - godot
    - gofmt
    - gosimple
    - ineffassign
    - makezero
    - misspell
    - nilerr
    - predeclared
    - staticcheck
    - usetesting
    - unconvert
    - unparam
    - unused
    - govet
    - gocyclo
    - errchkjson
    - gocritic
    - goimports
    - contextcheck
    - importas
