repos:
  - repo: https://github.com/golangci/golangci-lint
    rev: 04aec4f787c25a737641f3d434059880d2af0f53  # v1.64.4
    hooks:
      - id: golangci-lint

  - repo: local
    hooks:
      - id: go-mod-tidy
        name: go mod tidy
        entry: sh -c 'cd "$(dirname "$1")" && go mod tidy' --
        language: system
        files: ^go\.(mod|sum)$
        pass_filenames: true

      - id: go-generate
        name: go generate
        entry: go generate ./...
        language: system
        files: ^(examples/.*|internal/.*\.go)$
        pass_filenames: false

  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: 9a790d2bbf52124eecb5a71a4bab4884804ffa2a  # v1.100.0
    hooks:
      - id: terraform_fmt
        args:
          - --args=-recursive
      - id: terraform_validate
        args:
          - --args=-json
        files: ^examples/resources/.*\.tf$
        exclude: ^examples/provider/

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: cef0300fd0fc4d2a87a85fa2093c6b283ea36f4b  # v5.0.0
    hooks:
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-merge-conflict
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: detect-private-key
      - id: detect-aws-credentials
