---
provider:
  name: crowdstrike
resources:
  cloud_azure_tenant:
    create:
      path: /cloud-security-registration-azure/entities/registrations/v1
      method: POST
    read:
      path: /cloud-security-registration-azure/entities/registrations/v1
      method: GET
    schema:
      attributes:
        aliases:
          registration_id: id
      ignores:
        - meta
        - errors
        - api_client_key_type
        - deployment_method
        - api_client_key_id
        - deployment_stack_host_id
        - deployment_stack_name
        - registration_status
        - template_version
        - deleted
        - created
        - updated
        - deployment_stack_host_url
