package main

import (
	"fmt"
	"go/format"
	"maps"
	"path"
	"slices"
	"sort"
	"strconv"
	"strings"

	"github.com/hashicorp/hcl/v2/hclwrite"
)

const (
	goHeader  = "// Code generated by testgen. DO NOT EDIT."
	hclHeader = "# Code generated by testgen. DO NOT EDIT."
)

// renderHCL returns the resource's shared testdata/<resource>/main.tf. Every
// settable attribute the generator supports is a variable defaulting to null,
// so a test step sets an attribute by passing its variable and omits it by
// leaving the variable out.
func renderHCL(r *resourceInfo) []byte {
	vars := configurable(r)
	var b strings.Builder
	b.WriteString(hclHeader + "\n\n")
	for _, a := range vars {
		fmt.Fprintf(&b, "variable %q {\n  type    = %s\n  default = null\n}\n\n", a.name, tfType(a))
	}
	fmt.Fprintf(&b, "resource %q \"test\" {\n", r.typeName)
	for _, a := range vars {
		fmt.Fprintf(&b, "  %s = var.%s\n", a.name, a.name)
	}
	b.WriteString("}\n")
	return hclwrite.Format([]byte(b.String()))
}

// configurable returns the top-level attributes a generated test can set.
func configurable(r *resourceInfo) []*attribute {
	var out []*attribute
	for _, a := range sortedAttrs(r.attrs) {
		if a.settable() && a.kind != kindUnsupported && !a.deprecated && !a.writeOnly {
			out = append(out, a)
		}
	}
	return out
}

// configDir is the resource's shared testdata directory, relative to its package.
func configDir(r *resourceInfo) string {
	return "testdata/" + strings.TrimPrefix(r.typeName, "crowdstrike_")
}

// tfType returns the Terraform variable type constraint for an attribute.
func tfType(a *attribute) string {
	switch a.kind {
	case kindString:
		return "string"
	case kindBool:
		return "bool"
	case kindInt64, kindInt32, kindFloat64, kindFloat32:
		return "number"
	case kindList:
		return "list(" + tfType(a.elem) + ")"
	case kindSet:
		return "set(" + tfType(a.elem) + ")"
	case kindObject:
		var fields []string
		for _, c := range a.sortedChildren() {
			if c.settable() && c.kind != kindUnsupported {
				fields = append(fields, fmt.Sprintf("%s = optional(%s)", c.name, tfType(c)))
			}
		}
		return "object({\n" + strings.Join(fields, "\n") + "\n})"
	}
	panic("tfType: unsupported attribute " + a.dotted())
}

// renderGo returns the generated _gen_test.go file for a resource.
func renderGo(r *resourceInfo, cases []testCase) ([]byte, error) {
	var body strings.Builder
	used := map[string]bool{"testing": true}

	for _, c := range cases {
		body.WriteString("\n")
		if c.note != "" {
			fmt.Fprintf(&body, "// %s\n", c.note)
		}
		fmt.Fprintf(&body, "func %s(t *testing.T) {\n", c.name)
		if c.skip != "" {
			fmt.Fprintf(&body, "\tt.Skip(%q)\n}\n", c.skip)
			continue
		}
		for _, k := range []string{"acctest", "config", "resource"} {
			used[k] = true
		}
		if usesRName(c) {
			body.WriteString("\trName := acctest.RandomResourceName()\n")
		}
		fmt.Fprintf(&body, "\tresourceName := %q\n\n", r.typeName+".test")
		runner := "ParallelTest"
		if r.spec.Serial {
			runner = "Test"
		}
		fmt.Fprintf(&body, "\tresource.%s(t, resource.TestCase{\n", runner)
		body.WriteString("\t\tPreCheck:                 func() { acctest.PreCheck(t) },\n")
		body.WriteString("\t\tProtoV6ProviderFactories: acctest.ProtoV6ProviderFactories,\n")
		body.WriteString("\t\tSteps: []resource.TestStep{\n")
		for i, s := range c.steps {
			body.WriteString("\t\t\t{\n")
			fmt.Fprintf(&body, "\t\t\t\tConfigDirectory: config.StaticDirectory(%q),\n", configDir(r))
			body.WriteString("\t\t\t\tConfigVariables: config.Variables{\n")
			for _, a := range c.vars {
				if v, ok := s.values[a.name]; ok {
					fmt.Fprintf(&body, "\t\t\t\t\t%q: %s,\n", a.name, goVariable(a, v))
				}
			}
			body.WriteString("\t\t\t\t},\n")
			if s.importState {
				body.WriteString("\t\t\t\tResourceName:      resourceName,\n")
				body.WriteString("\t\t\t\tImportState:       true,\n")
				body.WriteString("\t\t\t\tImportStateVerify: true,\n")
				if len(r.spec.ImportIgnore) > 0 {
					fmt.Fprintf(&body, "\t\t\t\tImportStateVerifyIgnore: %s,\n", goStrings(r.spec.ImportIgnore))
				}
				body.WriteString("\t\t\t},\n")
				continue
			}
			if s.disappears {
				used["plancheck"] = true
				used["self"] = true
				used["statecheck"] = true
				body.WriteString("\t\t\t\tConfigStateChecks: []statecheck.StateCheck{\n")
				fmt.Fprintf(&body, "\t\t\t\t\tacctest.ResourceDisappears(%s.%s, resourceName),\n", r.pkgName, r.constructor)
				body.WriteString("\t\t\t\t},\n")
				body.WriteString("\t\t\t\tExpectNonEmptyPlan: true,\n")
				body.WriteString("\t\t\t\tConfigPlanChecks: resource.ConfigPlanChecks{\n")
				body.WriteString("\t\t\t\t\tPostApplyPostRefresh: []plancheck.PlanCheck{\n")
				body.WriteString("\t\t\t\t\t\tplancheck.ExpectResourceAction(resourceName, plancheck.ResourceActionCreate),\n")
				body.WriteString("\t\t\t\t\t},\n")
				body.WriteString("\t\t\t\t},\n")
				body.WriteString("\t\t\t},\n")
				continue
			}
			if pc := planCheck(i, s.planned); pc != "" {
				used["plancheck"] = true
				body.WriteString("\t\t\t\tConfigPlanChecks: resource.ConfigPlanChecks{\n")
				body.WriteString("\t\t\t\t\tPreApply: []plancheck.PlanCheck{\n")
				fmt.Fprintf(&body, "\t\t\t\t\t\t%s,\n", pc)
				body.WriteString("\t\t\t\t\t},\n")
				body.WriteString("\t\t\t\t},\n")
			}
			if len(s.checks) > 0 {
				for _, k := range []string{"knownvalue", "statecheck", "tfjsonpath"} {
					used[k] = true
				}
				body.WriteString("\t\t\t\tConfigStateChecks: []statecheck.StateCheck{\n")
				for _, ch := range s.checks {
					fmt.Fprintf(&body, "\t\t\t\t\tstatecheck.ExpectKnownValue(resourceName, %s, %s),\n", goPath(ch.attr), goCheck(ch))
				}
				body.WriteString("\t\t\t\t},\n")
			}
			body.WriteString("\t\t\t},\n")
		}
		body.WriteString("\t\t},\n\t})\n}\n")
	}

	imports := map[string]string{
		"acctest":    "github.com/crowdstrike/terraform-provider-crowdstrike/internal/acctest",
		"config":     "github.com/hashicorp/terraform-plugin-testing/config",
		"resource":   "github.com/hashicorp/terraform-plugin-testing/helper/resource",
		"knownvalue": "github.com/hashicorp/terraform-plugin-testing/knownvalue",
		"plancheck":  "github.com/hashicorp/terraform-plugin-testing/plancheck",
		"statecheck": "github.com/hashicorp/terraform-plugin-testing/statecheck",
		"tfjsonpath": "github.com/hashicorp/terraform-plugin-testing/tfjsonpath",
	}
	var specs []string
	for k := range used {
		switch k {
		case "testing":
		case "self":
			// The package under test, aliased when its name differs from its
			// directory (internal/cid_group is package cidgroup).
			spec := strconv.Quote(modulePath + "/" + r.dir)
			if r.pkgName != path.Base(r.dir) {
				spec = r.pkgName + " " + spec
			}
			specs = append(specs, spec)
		default:
			specs = append(specs, strconv.Quote(imports[k]))
		}
	}
	sort.Strings(specs)

	var out strings.Builder
	out.WriteString(goHeader + "\n\n")
	fmt.Fprintf(&out, "package %s\n\nimport (\n\t\"testing\"\n\n", r.testPackage)
	for _, spec := range specs {
		fmt.Fprintf(&out, "\t%s\n", spec)
	}
	out.WriteString(")\n")
	out.WriteString(body.String())

	src, err := format.Source([]byte(out.String()))
	if err != nil {
		return nil, fmt.Errorf("%s: formatting generated Go: %w\n%s", r.typeName, err, out.String())
	}
	return src, nil
}

func planCheck(stepIndex int, a action) string {
	if stepIndex == 0 {
		return ""
	}
	switch a {
	case actionNone:
		return "plancheck.ExpectEmptyPlan()"
	case actionUpdate:
		return "plancheck.ExpectResourceAction(resourceName, plancheck.ResourceActionUpdate)"
	case actionReplace:
		return "plancheck.ExpectResourceAction(resourceName, plancheck.ResourceActionDestroyBeforeCreate)"
	}
	return ""
}

func usesRName(c testCase) bool {
	for _, s := range c.steps {
		for name, v := range s.values {
			if valueUsesRName(attrByName(c, name), v) {
				return true
			}
		}
	}
	return false
}

func attrByName(c testCase, name string) *attribute {
	for _, a := range c.vars {
		if a.name == name {
			return a
		}
	}
	panic("attrByName: no variable " + name)
}

func valueUsesRName(a *attribute, v value) bool {
	switch a.kind {
	case kindString:
		return v.rName
	case kindList, kindSet:
		for _, e := range v.elems {
			if valueUsesRName(a.elem, e) {
				return true
			}
		}
	case kindObject:
		for k, f := range v.fields {
			if valueUsesRName(a.children[k], f) {
				return true
			}
		}
	}
	return false
}

func goString(v value) string {
	switch {
	case v.rName && v.str == "":
		return "rName"
	case v.rName:
		return "rName + " + strconv.Quote(v.str)
	}
	return strconv.Quote(v.str)
}

func goNumber(v value) string {
	switch n := v.prim.(type) {
	case int64:
		return strconv.FormatInt(n, 10)
	case float64:
		// Keep a decimal point so the literal is a float constant for the
		// generic FloatVariable and Float64Exact helpers.
		f := strconv.FormatFloat(n, 'g', -1, 64)
		if !strings.ContainsAny(f, ".eE") {
			f += ".0"
		}
		return f
	}
	panic(fmt.Sprintf("goNumber: %T", v.prim))
}

func goVariable(a *attribute, v value) string {
	switch a.kind {
	case kindString:
		return "config.StringVariable(" + goString(v) + ")"
	case kindBool:
		return fmt.Sprintf("config.BoolVariable(%t)", v.prim)
	case kindInt64, kindInt32:
		return "config.IntegerVariable(" + goNumber(v) + ")"
	case kindFloat64, kindFloat32:
		return "config.FloatVariable(" + goNumber(v) + ")"
	case kindList, kindSet:
		fn := "config.ListVariable("
		if a.kind == kindSet {
			fn = "config.SetVariable("
		}
		if len(v.elems) == 0 {
			// With no arguments the variadic slice is nil, which plugin-testing
			// marshals as null rather than an empty collection.
			return fn + "[]config.Variable{}...)"
		}
		elems := make([]string, len(v.elems))
		for i, e := range v.elems {
			elems[i] = goVariable(a.elem, e)
		}
		return fn + strings.Join(elems, ", ") + ")"
	case kindObject:
		var fields []string
		for _, k := range sortedKeys(v.fields) {
			fields = append(fields, fmt.Sprintf("%q: %s", k, goVariable(a.children[k], v.fields[k])))
		}
		return "config.ObjectVariable(map[string]config.Variable{" + strings.Join(fields, ", ") + "})"
	}
	panic("goVariable: unsupported attribute " + a.dotted())
}

func goCheck(c check) string {
	switch c.kind {
	case checkNull:
		return "knownvalue.Null()"
	case checkNotNull:
		return "knownvalue.NotNull()"
	case checkEmpty:
		if c.attr.kind == kindSet {
			return "knownvalue.SetSizeExact(0)"
		}
		return "knownvalue.ListSizeExact(0)"
	}
	return goValueCheck(c.attr, c.v)
}

func goValueCheck(a *attribute, v value) string {
	switch a.kind {
	case kindString:
		return "knownvalue.StringExact(" + goString(v) + ")"
	case kindBool:
		return fmt.Sprintf("knownvalue.Bool(%t)", v.prim)
	case kindInt64:
		return "knownvalue.Int64Exact(" + goNumber(v) + ")"
	case kindInt32:
		return "knownvalue.Int32Exact(" + goNumber(v) + ")"
	case kindFloat64:
		return "knownvalue.Float64Exact(" + goNumber(v) + ")"
	case kindFloat32:
		return "knownvalue.Float32Exact(" + goNumber(v) + ")"
	case kindList, kindSet:
		fn := "knownvalue.ListExact"
		if a.kind == kindSet {
			fn = "knownvalue.SetExact"
		}
		elems := make([]string, len(v.elems))
		for i, e := range v.elems {
			elems[i] = goValueCheck(a.elem, e)
		}
		return fn + "([]knownvalue.Check{" + strings.Join(elems, ", ") + "})"
	case kindObject:
		var fields []string
		for _, k := range sortedKeys(v.fields) {
			fields = append(fields, fmt.Sprintf("%q: %s", k, goValueCheck(a.children[k], v.fields[k])))
		}
		return "knownvalue.ObjectPartial(map[string]knownvalue.Check{" + strings.Join(fields, ", ") + "})"
	}
	panic("goValueCheck: unsupported attribute " + a.dotted())
}

// goPath returns the tfjsonpath expression for an attribute path.
func goPath(a *attribute) string {
	out := fmt.Sprintf("tfjsonpath.New(%q)", a.path[0])
	for _, part := range a.path[1:] {
		out += fmt.Sprintf(".AtMapKey(%q)", part)
	}
	return out
}

func goStrings(ss []string) string {
	q := make([]string, len(ss))
	for i, s := range ss {
		q[i] = strconv.Quote(s)
	}
	return "[]string{" + strings.Join(q, ", ") + "}"
}

func sortedKeys(m map[string]value) []string { return slices.Sorted(maps.Keys(m)) }
