# Code generated by testgen. DO NOT EDIT.

variable "custom_scripts" {
  type    = bool
  default = null
}

variable "description" {
  type    = string
  default = null
}

variable "enabled" {
  type    = bool
  default = null
}

variable "exec_command" {
  type    = bool
  default = null
}

variable "falcon_scripts" {
  type    = bool
  default = null
}

variable "get_command" {
  type    = bool
  default = null
}

variable "host_groups" {
  type    = set(string)
  default = null
}

variable "memdump_command" {
  type    = bool
  default = null
}

variable "name" {
  type    = string
  default = null
}

variable "platform_name" {
  type    = string
  default = null
}

variable "put_and_run_command" {
  type    = bool
  default = null
}

variable "put_command" {
  type    = bool
  default = null
}

variable "real_time_response" {
  type    = bool
  default = null
}

variable "xmemdump_command" {
  type    = bool
  default = null
}

resource "crowdstrike_response_policy" "test" {
  custom_scripts      = var.custom_scripts
  description         = var.description
  enabled             = var.enabled
  exec_command        = var.exec_command
  falcon_scripts      = var.falcon_scripts
  get_command         = var.get_command
  host_groups         = var.host_groups
  memdump_command     = var.memdump_command
  name                = var.name
  platform_name       = var.platform_name
  put_and_run_command = var.put_and_run_command
  put_command         = var.put_command
  real_time_response  = var.real_time_response
  xmemdump_command    = var.xmemdump_command
}
