// Code generated by testgen. DO NOT EDIT.

package dataprotection_test

import (
	"testing"

	"github.com/crowdstrike/terraform-provider-crowdstrike/internal/acctest"
	dataprotection "github.com/crowdstrike/terraform-provider-crowdstrike/internal/data_protection"
	"github.com/hashicorp/terraform-plugin-testing/config"
	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
	"github.com/hashicorp/terraform-plugin-testing/knownvalue"
	"github.com/hashicorp/terraform-plugin-testing/plancheck"
	"github.com/hashicorp/terraform-plugin-testing/statecheck"
	"github.com/hashicorp/terraform-plugin-testing/tfjsonpath"
)

func TestAccDataProtectionContentPatternResource_disappears(t *testing.T) {
	rName := acctest.RandomResourceName()
	resourceName := "crowdstrike_data_protection_content_pattern.test"

	resource.ParallelTest(t, resource.TestCase{
		PreCheck:                 func() { acctest.PreCheck(t) },
		ProtoV6ProviderFactories: acctest.ProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			{
				ConfigDirectory: config.StaticDirectory("testdata/data_protection_content_pattern"),
				ConfigVariables: config.Variables{
					"min_match_threshold": config.IntegerVariable(1),
					"name":                config.StringVariable(rName),
					"regex":               config.StringVariable("testgen regex 1"),
				},
				ConfigStateChecks: []statecheck.StateCheck{
					acctest.ResourceDisappears(dataprotection.NewDataProtectionContentPatternResource, resourceName),
				},
				ExpectNonEmptyPlan: true,
				ConfigPlanChecks: resource.ConfigPlanChecks{
					PostApplyPostRefresh: []plancheck.PlanCheck{
						plancheck.ExpectResourceAction(resourceName, plancheck.ResourceActionCreate),
					},
				},
			},
		},
	})
}

func TestAccDataProtectionContentPatternResource_description(t *testing.T) {
	rName := acctest.RandomResourceName()
	resourceName := "crowdstrike_data_protection_content_pattern.test"

	resource.ParallelTest(t, resource.TestCase{
		PreCheck:                 func() { acctest.PreCheck(t) },
		ProtoV6ProviderFactories: acctest.ProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			{
				ConfigDirectory: config.StaticDirectory("testdata/data_protection_content_pattern"),
				ConfigVariables: config.Variables{
					"description":         config.StringVariable("testgen description 1"),
					"min_match_threshold": config.IntegerVariable(1),
					"name":                config.StringVariable(rName),
					"regex":               config.StringVariable("testgen regex 1"),
				},
				ConfigStateChecks: []statecheck.StateCheck{
					statecheck.ExpectKnownValue(resourceName, tfjsonpath.New("description"), knownvalue.StringExact("testgen description 1")),
				},
			},
			{
				ConfigDirectory: config.StaticDirectory("testdata/data_protection_content_pattern"),
				ConfigVariables: config.Variables{
					"description":         config.StringVariable("testgen description 2"),
					"min_match_threshold": config.IntegerVariable(1),
					"name":                config.StringVariable(rName),
					"regex":               config.StringVariable("testgen regex 1"),
				},
				ConfigStateChecks: []statecheck.StateCheck{
					statecheck.ExpectKnownValue(resourceName, tfjsonpath.New("description"), knownvalue.StringExact("testgen description 2")),
				},
			},
			{
				ConfigDirectory: config.StaticDirectory("testdata/data_protection_content_pattern"),
				ConfigVariables: config.Variables{
					"min_match_threshold": config.IntegerVariable(1),
					"name":                config.StringVariable(rName),
					"regex":               config.StringVariable("testgen regex 1"),
				},
				ConfigStateChecks: []statecheck.StateCheck{
					statecheck.ExpectKnownValue(resourceName, tfjsonpath.New("description"), knownvalue.Null()),
				},
			},
			{
				ConfigDirectory: config.StaticDirectory("testdata/data_protection_content_pattern"),
				ConfigVariables: config.Variables{
					"min_match_threshold": config.IntegerVariable(1),
					"name":                config.StringVariable(rName),
					"regex":               config.StringVariable("testgen regex 1"),
				},
				ResourceName:            resourceName,
				ImportState:             true,
				ImportStateVerify:       true,
				ImportStateVerifyIgnore: []string{"last_updated"},
			},
		},
	})
}

func TestAccDataProtectionContentPatternResource_minMatchThreshold(t *testing.T) {
	rName := acctest.RandomResourceName()
	resourceName := "crowdstrike_data_protection_content_pattern.test"

	resource.ParallelTest(t, resource.TestCase{
		PreCheck:                 func() { acctest.PreCheck(t) },
		ProtoV6ProviderFactories: acctest.ProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			{
				ConfigDirectory: config.StaticDirectory("testdata/data_protection_content_pattern"),
				ConfigVariables: config.Variables{
					"min_match_threshold": config.IntegerVariable(1),
					"name":                config.StringVariable(rName),
					"regex":               config.StringVariable("testgen regex 1"),
				},
				ConfigStateChecks: []statecheck.StateCheck{
					statecheck.ExpectKnownValue(resourceName, tfjsonpath.New("min_match_threshold"), knownvalue.Int32Exact(1)),
				},
			},
			{
				ConfigDirectory: config.StaticDirectory("testdata/data_protection_content_pattern"),
				ConfigVariables: config.Variables{
					"min_match_threshold": config.IntegerVariable(2),
					"name":                config.StringVariable(rName),
					"regex":               config.StringVariable("testgen regex 1"),
				},
				ConfigPlanChecks: resource.ConfigPlanChecks{
					PreApply: []plancheck.PlanCheck{
						plancheck.ExpectResourceAction(resourceName, plancheck.ResourceActionUpdate),
					},
				},
				ConfigStateChecks: []statecheck.StateCheck{
					statecheck.ExpectKnownValue(resourceName, tfjsonpath.New("min_match_threshold"), knownvalue.Int32Exact(2)),
				},
			},
			{
				ConfigDirectory: config.StaticDirectory("testdata/data_protection_content_pattern"),
				ConfigVariables: config.Variables{
					"min_match_threshold": config.IntegerVariable(2),
					"name":                config.StringVariable(rName),
					"regex":               config.StringVariable("testgen regex 1"),
				},
				ResourceName:            resourceName,
				ImportState:             true,
				ImportStateVerify:       true,
				ImportStateVerifyIgnore: []string{"last_updated"},
			},
		},
	})
}

func TestAccDataProtectionContentPatternResource_name(t *testing.T) {
	rName := acctest.RandomResourceName()
	resourceName := "crowdstrike_data_protection_content_pattern.test"

	resource.ParallelTest(t, resource.TestCase{
		PreCheck:                 func() { acctest.PreCheck(t) },
		ProtoV6ProviderFactories: acctest.ProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			{
				ConfigDirectory: config.StaticDirectory("testdata/data_protection_content_pattern"),
				ConfigVariables: config.Variables{
					"min_match_threshold": config.IntegerVariable(1),
					"name":                config.StringVariable(rName),
					"regex":               config.StringVariable("testgen regex 1"),
				},
				ConfigStateChecks: []statecheck.StateCheck{
					statecheck.ExpectKnownValue(resourceName, tfjsonpath.New("name"), knownvalue.StringExact(rName)),
				},
			},
			{
				ConfigDirectory: config.StaticDirectory("testdata/data_protection_content_pattern"),
				ConfigVariables: config.Variables{
					"min_match_threshold": config.IntegerVariable(1),
					"name":                config.StringVariable(rName + "-updated"),
					"regex":               config.StringVariable("testgen regex 1"),
				},
				ConfigPlanChecks: resource.ConfigPlanChecks{
					PreApply: []plancheck.PlanCheck{
						plancheck.ExpectResourceAction(resourceName, plancheck.ResourceActionUpdate),
					},
				},
				ConfigStateChecks: []statecheck.StateCheck{
					statecheck.ExpectKnownValue(resourceName, tfjsonpath.New("name"), knownvalue.StringExact(rName+"-updated")),
				},
			},
			{
				ConfigDirectory: config.StaticDirectory("testdata/data_protection_content_pattern"),
				ConfigVariables: config.Variables{
					"min_match_threshold": config.IntegerVariable(1),
					"name":                config.StringVariable(rName + "-updated"),
					"regex":               config.StringVariable("testgen regex 1"),
				},
				ResourceName:            resourceName,
				ImportState:             true,
				ImportStateVerify:       true,
				ImportStateVerifyIgnore: []string{"last_updated"},
			},
		},
	})
}

func TestAccDataProtectionContentPatternResource_regex(t *testing.T) {
	rName := acctest.RandomResourceName()
	resourceName := "crowdstrike_data_protection_content_pattern.test"

	resource.ParallelTest(t, resource.TestCase{
		PreCheck:                 func() { acctest.PreCheck(t) },
		ProtoV6ProviderFactories: acctest.ProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			{
				ConfigDirectory: config.StaticDirectory("testdata/data_protection_content_pattern"),
				ConfigVariables: config.Variables{
					"min_match_threshold": config.IntegerVariable(1),
					"name":                config.StringVariable(rName),
					"regex":               config.StringVariable("testgen regex 1"),
				},
				ConfigStateChecks: []statecheck.StateCheck{
					statecheck.ExpectKnownValue(resourceName, tfjsonpath.New("regex"), knownvalue.StringExact("testgen regex 1")),
				},
			},
			{
				ConfigDirectory: config.StaticDirectory("testdata/data_protection_content_pattern"),
				ConfigVariables: config.Variables{
					"min_match_threshold": config.IntegerVariable(1),
					"name":                config.StringVariable(rName),
					"regex":               config.StringVariable("testgen regex 2"),
				},
				ConfigPlanChecks: resource.ConfigPlanChecks{
					PreApply: []plancheck.PlanCheck{
						plancheck.ExpectResourceAction(resourceName, plancheck.ResourceActionUpdate),
					},
				},
				ConfigStateChecks: []statecheck.StateCheck{
					statecheck.ExpectKnownValue(resourceName, tfjsonpath.New("regex"), knownvalue.StringExact("testgen regex 2")),
				},
			},
			{
				ConfigDirectory: config.StaticDirectory("testdata/data_protection_content_pattern"),
				ConfigVariables: config.Variables{
					"min_match_threshold": config.IntegerVariable(1),
					"name":                config.StringVariable(rName),
					"regex":               config.StringVariable("testgen regex 2"),
				},
				ResourceName:            resourceName,
				ImportState:             true,
				ImportStateVerify:       true,
				ImportStateVerifyIgnore: []string{"last_updated"},
			},
		},
	})
}
