package ngsiem

import (
	"context"
	"fmt"
	"time"

	"github.com/crowdstrike/gofalcon/falcon/client"
	"github.com/crowdstrike/gofalcon/falcon/client/ngsiem"
	"github.com/crowdstrike/gofalcon/falcon/models"
	"github.com/crowdstrike/terraform-provider-crowdstrike/internal/config"
	"github.com/crowdstrike/terraform-provider-crowdstrike/internal/framework/flex"
	fwvalidators "github.com/crowdstrike/terraform-provider-crowdstrike/internal/framework/validators"
	"github.com/crowdstrike/terraform-provider-crowdstrike/internal/retry"
	"github.com/crowdstrike/terraform-provider-crowdstrike/internal/tferrors"
	"github.com/crowdstrike/terraform-provider-crowdstrike/internal/utils"
	"github.com/hashicorp/terraform-plugin-framework-timetypes/timetypes"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/mapplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

var (
	_ resource.Resource              = &dataConnectionTokenResource{}
	_ resource.ResourceWithConfigure = &dataConnectionTokenResource{}
)

const (
	dataConnectionTokenCreateTimeout  = 2 * time.Minute
	dataConnectionTokenCreateInterval = 5 * time.Second
)

// NewDataConnectionTokenResource creates a new NG-SIEM data connection token resource.
func NewDataConnectionTokenResource() resource.Resource {
	return &dataConnectionTokenResource{}
}

type dataConnectionTokenResource struct {
	client *client.CrowdStrikeAPISpecification
}

type dataConnectionTokenResourceModel struct {
	ConnectionID types.String      `tfsdk:"connection_id"`
	Triggers     types.Map         `tfsdk:"triggers"`
	Token        types.String      `tfsdk:"token"`
	IngestURL    types.String      `tfsdk:"ingest_url"`
	CreatedAt    timetypes.RFC3339 `tfsdk:"created_at"`
	ExpiresAt    timetypes.RFC3339 `tfsdk:"expires_at"`
}

func (r *dataConnectionTokenResource) Metadata(
	_ context.Context,
	req resource.MetadataRequest,
	resp *resource.MetadataResponse,
) {
	resp.TypeName = req.ProviderTypeName + "_ngsiem_data_connection_token"
}

func (r *dataConnectionTokenResource) Configure(
	_ context.Context,
	req resource.ConfigureRequest,
	resp *resource.ConfigureResponse,
) {
	if req.ProviderData == nil {
		return
	}

	providerConfig, ok := req.ProviderData.(config.ProviderConfig)
	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Resource Configure Type",
			fmt.Sprintf("Expected config.ProviderConfig, got: %T. Please report this issue to the provider developers.", req.ProviderData),
		)
		return
	}

	r.client = providerConfig.Client
}

func (r *dataConnectionTokenResource) Schema(
	_ context.Context,
	_ resource.SchemaRequest,
	resp *resource.SchemaResponse,
) {
	resp.Schema = schema.Schema{
		MarkdownDescription: utils.MarkdownDescription(
			"Next-Gen SIEM",
			"Generates and manages the HEC ingest token for a push `crowdstrike_ngsiem_data_connection`. The token is generated by the API and returned only at generation time; it is stored in Terraform state as a sensitive value and cannot be read back from the API afterward. Because the plaintext cannot be re-read, this resource does not support import. Rotate the token by changing `triggers`, which replaces the resource and generates a new token.",
			dataConnectionRequiredScopes,
		),
		Attributes: map[string]schema.Attribute{
			"connection_id": schema.StringAttribute{
				Required:            true,
				MarkdownDescription: "The ID of the push `crowdstrike_ngsiem_data_connection` to generate an ingest token for. Changing this forces a new resource to be created.",
				Validators: []validator.String{
					fwvalidators.StringNotWhitespace(),
				},
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"triggers": schema.MapAttribute{
				ElementType:         types.StringType,
				Optional:            true,
				MarkdownDescription: "A map of arbitrary strings that, when changed, will force the token to be regenerated, invalidating the previous one. Use this to rotate the token on demand (e.g. set a date or version string).",
				PlanModifiers: []planmodifier.Map{
					mapplanmodifier.RequiresReplace(),
				},
			},
			"token": schema.StringAttribute{
				Computed:            true,
				Sensitive:           true,
				MarkdownDescription: "The HEC ingest token. Returned only when generated and stored in state as sensitive; it cannot be read back from the API. Regenerated when `triggers` changes or the resource is replaced.",
			},
			"ingest_url": schema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "The HEC ingest URL for the connection. External sources send events here using the `token`.",
			},
			"created_at": schema.StringAttribute{
				Computed:            true,
				CustomType:          timetypes.RFC3339Type{},
				MarkdownDescription: "Timestamp (RFC3339) when the token was generated.",
			},
			"expires_at": schema.StringAttribute{
				Computed:            true,
				CustomType:          timetypes.RFC3339Type{},
				MarkdownDescription: "Timestamp (RFC3339) when the token expires.",
			},
		},
	}
}

func (r *dataConnectionTokenResource) Create(
	ctx context.Context,
	req resource.CreateRequest,
	resp *resource.CreateResponse,
) {
	var plan dataConnectionTokenResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	token, diags := r.regenerateTokenWithRetry(ctx, plan.ConnectionID.ValueString())
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(plan.wrap(*token)...)
	if resp.Diagnostics.HasError() {
		return
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *dataConnectionTokenResource) Read(
	ctx context.Context,
	req resource.ReadRequest,
	resp *resource.ReadResponse,
) {
	var state dataConnectionTokenResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	// The token endpoints cannot be read without consuming/rotating the token,
	// so Read only verifies the underlying connection still exists. If it is
	// gone, the token is meaningless and the resource is removed from state.
	params := ngsiem.NewExternalGetDataConnectionByIDParams().
		WithContext(ctx).
		WithIds([]string{state.ConnectionID.ValueString()})

	res, err := r.client.Ngsiem.ExternalGetDataConnectionByID(params)
	if err != nil {
		diag := tferrors.NewDiagnosticFromAPIError(
			tferrors.Read,
			err,
			dataConnectionRequiredScopes,
		)
		if diag.Summary() == tferrors.NotFoundErrorSummary {
			resp.Diagnostics.Append(tferrors.NewResourceNotFoundWarningDiagnostic())
			resp.State.RemoveResource(ctx)
			return
		}
		resp.Diagnostics.Append(diag)
		return
	}

	if res == nil || res.Payload == nil || len(res.Payload.Resources) == 0 || res.Payload.Resources[0] == nil {
		resp.Diagnostics.Append(tferrors.NewResourceNotFoundWarningDiagnostic())
		resp.State.RemoveResource(ctx)
		return
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *dataConnectionTokenResource) Update(
	ctx context.Context,
	req resource.UpdateRequest,
	resp *resource.UpdateResponse,
) {
	// All configurable attributes (connection_id, triggers) force
	// replacement, so Update never runs with a real change. Carry the prior
	// computed values forward.
	var plan dataConnectionTokenResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *dataConnectionTokenResource) Delete(
	_ context.Context,
	_ resource.DeleteRequest,
	_ *resource.DeleteResponse,
) {
	// There is no API to delete or revoke an ingest token independently. The
	// token remains valid server-side until the connection is deleted or the
	// token is regenerated. Removing the resource only drops it from state.
}

// regenerateTokenWithRetry calls the regenerate token endpoint, polling through
// the 202 ConnectionNotReady state until the connection is provisioned and a
// token is minted.
func (r *dataConnectionTokenResource) regenerateTokenWithRetry(
	ctx context.Context,
	connectionID string,
) (*models.DataconnectionmanagementConnectionToken, diag.Diagnostics) {
	var diags diag.Diagnostics
	var token *models.DataconnectionmanagementConnectionToken

	err := retry.RetryUntilNoError(
		ctx,
		dataConnectionTokenCreateTimeout,
		dataConnectionTokenCreateInterval,
		func() error {
			t, notReady, callDiags := r.regenerateToken(ctx, connectionID)
			if callDiags.HasError() {
				diags = callDiags
				return nil // stop retrying on hard error
			}
			if notReady {
				return fmt.Errorf("connection %s is not ready", connectionID)
			}
			token = t
			return nil
		},
	)
	if err != nil {
		diags.AddError(
			"Error generating data connection token",
			fmt.Sprintf("generating token for connection (%s): %s", connectionID, err),
		)
		return nil, diags
	}
	if diags.HasError() {
		return nil, diags
	}

	return token, diags
}

// regenerateToken performs a single call to the regenerate token endpoint. It
// returns notReady=true when the API responds 202 ConnectionNotReady.
func (r *dataConnectionTokenResource) regenerateToken(
	ctx context.Context,
	connectionID string,
) (*models.DataconnectionmanagementConnectionToken, bool, diag.Diagnostics) {
	var diags diag.Diagnostics

	params := ngsiem.NewExternalRegenerateDataConnectionTokenParams().
		WithContext(ctx).
		WithIds(connectionID)

	reader := &regenerateTokenReader{}
	_, accepted, err := r.client.Ngsiem.ExternalRegenerateDataConnectionToken(
		params,
		withRegenerateTokenReader(reader),
	)
	if err != nil {
		diags.Append(tferrors.NewDiagnosticFromAPIError(
			tferrors.Create,
			err,
			dataConnectionRequiredScopes,
		))
		return nil, false, diags
	}

	if accepted != nil {
		return nil, true, diags
	}

	if reader.response == nil {
		diags.Append(tferrors.NewEmptyResponseError(tferrors.Create))
		return nil, false, diags
	}

	if diag := tferrors.NewDiagnosticFromPayloadErrors(tferrors.Create, reader.response.Errors); diag != nil {
		diags.Append(diag)
		return nil, false, diags
	}

	if reader.response.Resources == nil || reader.response.Resources.Token == nil {
		diags.Append(tferrors.NewEmptyResponseError(tferrors.Create))
		return nil, false, diags
	}

	return reader.response.Resources, false, diags
}

// wrap maps the API token response onto the Terraform model. connection_id and
// triggers are plan-owned and left untouched.
func (m *dataConnectionTokenResourceModel) wrap(
	token models.DataconnectionmanagementConnectionToken,
) diag.Diagnostics {
	var diags diag.Diagnostics

	m.Token = flex.StringPointerToFramework(token.Token)
	m.IngestURL = flex.StringPointerToFramework(token.IngestURL)
	m.CreatedAt, diags = rfc3339FromPointer(token.CreatedAt)
	expiresAt, expiresDiags := rfc3339FromPointer(token.ExpiresAt)
	diags.Append(expiresDiags...)
	m.ExpiresAt = expiresAt

	return diags
}

// rfc3339FromPointer converts an API RFC3339 timestamp string into a
// timetypes.RFC3339, returning null for a nil or empty value.
func rfc3339FromPointer(value *string) (timetypes.RFC3339, diag.Diagnostics) {
	if value == nil || *value == "" {
		return timetypes.NewRFC3339Null(), nil
	}
	return timetypes.NewRFC3339Value(*value)
}
