// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package provider_crowdstrike

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/provider/schema"
)

func CrowdstrikeProviderSchema(ctx context.Context) schema.Schema {
	return schema.Schema{}
}

type CrowdstrikeModel struct {
}
