package preventionpolicy

type PreventionPoliciesDataSource = preventionPoliciesDataSource
type PreventionPoliciesDataSourceModel = preventionPoliciesDataSourceModel

var FilterPoliciesByIDs = filterPoliciesByIDs
var FilterPoliciesByAttributes = filterPoliciesByAttributes
