package preventionpolicy

type PreventionPoliciesDataSource = preventionPoliciesDataSource
type PreventionPoliciesDataSourceModel = preventionPoliciesDataSourceModel

var BuildFQLFromAttributesWithClientFiltering = (*preventionPoliciesDataSource).buildFQLFromAttributesWithClientFiltering
var ApplyClientSideFiltering = (*preventionPoliciesDataSource).applyClientSideFiltering
