# Code generated by testgen. DO NOT EDIT.

variable "assignment_rule" {
  type    = string
  default = null
}

variable "description" {
  type    = string
  default = null
}

variable "host_ids" {
  type    = set(string)
  default = null
}

variable "hostnames" {
  type    = set(string)
  default = null
}

variable "name" {
  type    = string
  default = null
}

variable "type" {
  type    = string
  default = null
}

resource "crowdstrike_host_group" "test" {
  assignment_rule = var.assignment_rule
  description     = var.description
  host_ids        = var.host_ids
  hostnames       = var.hostnames
  name            = var.name
  type            = var.type
}
