# Code generated by testgen. DO NOT EDIT.

variable "description" {
  type    = string
  default = null
}

variable "enabled" {
  type    = bool
  default = null
}

variable "host_groups" {
  type    = set(string)
  default = null
}

variable "name" {
  type    = string
  default = null
}

variable "rapid_response" {
  type = object({
    delay_hours            = optional(number)
    pinned_content_version = optional(string)
    ring_assignment        = optional(string)
  })
  default = null
}

variable "sensor_operations" {
  type = object({
    delay_hours            = optional(number)
    pinned_content_version = optional(string)
    ring_assignment        = optional(string)
  })
  default = null
}

variable "system_critical" {
  type = object({
    delay_hours            = optional(number)
    pinned_content_version = optional(string)
    ring_assignment        = optional(string)
  })
  default = null
}

variable "vulnerability_management" {
  type = object({
    delay_hours            = optional(number)
    pinned_content_version = optional(string)
    ring_assignment        = optional(string)
  })
  default = null
}

resource "crowdstrike_content_update_policy" "test" {
  description              = var.description
  enabled                  = var.enabled
  host_groups              = var.host_groups
  name                     = var.name
  rapid_response           = var.rapid_response
  sensor_operations        = var.sensor_operations
  system_critical          = var.system_critical
  vulnerability_management = var.vulnerability_management
}
