// Code generated by testgen. DO NOT EDIT.

package responsepolicy_test

import (
	"testing"

	"github.com/crowdstrike/terraform-provider-crowdstrike/internal/acctest"
	responsepolicy "github.com/crowdstrike/terraform-provider-crowdstrike/internal/response_policy"
	"github.com/hashicorp/terraform-plugin-testing/config"
	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
	"github.com/hashicorp/terraform-plugin-testing/knownvalue"
	"github.com/hashicorp/terraform-plugin-testing/plancheck"
	"github.com/hashicorp/terraform-plugin-testing/statecheck"
	"github.com/hashicorp/terraform-plugin-testing/tfjsonpath"
)

func TestAccResponsePolicyResource_basic(t *testing.T) {
	rName := acctest.RandomResourceName()
	resourceName := "crowdstrike_response_policy.test"

	resource.ParallelTest(t, resource.TestCase{
		PreCheck:                 func() { acctest.PreCheck(t) },
		ProtoV6ProviderFactories: acctest.ProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			{
				ConfigDirectory: config.StaticDirectory("testdata/response_policy"),
				ConfigVariables: config.Variables{
					"name":          config.StringVariable(rName),
					"platform_name": config.StringVariable("Windows"),
				},
				ConfigStateChecks: []statecheck.StateCheck{
					statecheck.ExpectKnownValue(resourceName, tfjsonpath.New("id"), knownvalue.NotNull()),
					statecheck.ExpectKnownValue(resourceName, tfjsonpath.New("last_updated"), knownvalue.NotNull()),
				},
			},
			{
				ConfigDirectory: config.StaticDirectory("testdata/response_policy"),
				ConfigVariables: config.Variables{
					"name":          config.StringVariable(rName),
					"platform_name": config.StringVariable("Windows"),
				},
				ResourceName:            resourceName,
				ImportState:             true,
				ImportStateVerify:       true,
				ImportStateVerifyIgnore: []string{"last_updated"},
			},
		},
	})
}

func TestAccResponsePolicyResource_disappears(t *testing.T) {
	rName := acctest.RandomResourceName()
	resourceName := "crowdstrike_response_policy.test"

	resource.ParallelTest(t, resource.TestCase{
		PreCheck:                 func() { acctest.PreCheck(t) },
		ProtoV6ProviderFactories: acctest.ProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			{
				ConfigDirectory: config.StaticDirectory("testdata/response_policy"),
				ConfigVariables: config.Variables{
					"name":          config.StringVariable(rName),
					"platform_name": config.StringVariable("Windows"),
				},
				ConfigStateChecks: []statecheck.StateCheck{
					acctest.ResourceDisappears(responsepolicy.NewResponsePolicyResource, resourceName),
				},
				ExpectNonEmptyPlan: true,
				ConfigPlanChecks: resource.ConfigPlanChecks{
					PostApplyPostRefresh: []plancheck.PlanCheck{
						plancheck.ExpectResourceAction(resourceName, plancheck.ResourceActionCreate),
					},
				},
			},
		},
	})
}

func TestAccResponsePolicyResource_customScripts(t *testing.T) {
	rName := acctest.RandomResourceName()
	resourceName := "crowdstrike_response_policy.test"

	resource.ParallelTest(t, resource.TestCase{
		PreCheck:                 func() { acctest.PreCheck(t) },
		ProtoV6ProviderFactories: acctest.ProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			{
				ConfigDirectory: config.StaticDirectory("testdata/response_policy"),
				ConfigVariables: config.Variables{
					"custom_scripts": config.BoolVariable(true),
					"name":           config.StringVariable(rName),
					"platform_name":  config.StringVariable("Windows"),
				},
				ConfigStateChecks: []statecheck.StateCheck{
					statecheck.ExpectKnownValue(resourceName, tfjsonpath.New("custom_scripts"), knownvalue.Bool(true)),
				},
			},
			{
				ConfigDirectory: config.StaticDirectory("testdata/response_policy"),
				ConfigVariables: config.Variables{
					"custom_scripts": config.BoolVariable(false),
					"name":           config.StringVariable(rName),
					"platform_name":  config.StringVariable("Windows"),
				},
				ConfigPlanChecks: resource.ConfigPlanChecks{
					PreApply: []plancheck.PlanCheck{
						plancheck.ExpectResourceAction(resourceName, plancheck.ResourceActionUpdate),
					},
				},
				ConfigStateChecks: []statecheck.StateCheck{
					statecheck.ExpectKnownValue(resourceName, tfjsonpath.New("custom_scripts"), knownvalue.Bool(false)),
				},
			},
			{
				ConfigDirectory: config.StaticDirectory("testdata/response_policy"),
				ConfigVariables: config.Variables{
					"name":          config.StringVariable(rName),
					"platform_name": config.StringVariable("Windows"),
				},
				ConfigPlanChecks: resource.ConfigPlanChecks{
					PreApply: []plancheck.PlanCheck{
						plancheck.ExpectEmptyPlan(),
					},
				},
				ConfigStateChecks: []statecheck.StateCheck{
					statecheck.ExpectKnownValue(resourceName, tfjsonpath.New("custom_scripts"), knownvalue.Bool(false)),
				},
			},
			{
				ConfigDirectory: config.StaticDirectory("testdata/response_policy"),
				ConfigVariables: config.Variables{
					"name":          config.StringVariable(rName),
					"platform_name": config.StringVariable("Windows"),
				},
				ResourceName:            resourceName,
				ImportState:             true,
				ImportStateVerify:       true,
				ImportStateVerifyIgnore: []string{"last_updated"},
			},
		},
	})
}

func TestAccResponsePolicyResource_description(t *testing.T) {
	rName := acctest.RandomResourceName()
	resourceName := "crowdstrike_response_policy.test"

	resource.ParallelTest(t, resource.TestCase{
		PreCheck:                 func() { acctest.PreCheck(t) },
		ProtoV6ProviderFactories: acctest.ProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			{
				ConfigDirectory: config.StaticDirectory("testdata/response_policy"),
				ConfigVariables: config.Variables{
					"description":   config.StringVariable(rName),
					"name":          config.StringVariable(rName),
					"platform_name": config.StringVariable("Windows"),
				},
				ConfigStateChecks: []statecheck.StateCheck{
					statecheck.ExpectKnownValue(resourceName, tfjsonpath.New("description"), knownvalue.StringExact(rName)),
				},
			},
			{
				ConfigDirectory: config.StaticDirectory("testdata/response_policy"),
				ConfigVariables: config.Variables{
					"description":   config.StringVariable(rName + "-updated"),
					"name":          config.StringVariable(rName),
					"platform_name": config.StringVariable("Windows"),
				},
				ConfigPlanChecks: resource.ConfigPlanChecks{
					PreApply: []plancheck.PlanCheck{
						plancheck.ExpectResourceAction(resourceName, plancheck.ResourceActionUpdate),
					},
				},
				ConfigStateChecks: []statecheck.StateCheck{
					statecheck.ExpectKnownValue(resourceName, tfjsonpath.New("description"), knownvalue.StringExact(rName+"-updated")),
				},
			},
			{
				ConfigDirectory: config.StaticDirectory("testdata/response_policy"),
				ConfigVariables: config.Variables{
					"name":          config.StringVariable(rName),
					"platform_name": config.StringVariable("Windows"),
				},
				ConfigPlanChecks: resource.ConfigPlanChecks{
					PreApply: []plancheck.PlanCheck{
						plancheck.ExpectResourceAction(resourceName, plancheck.ResourceActionUpdate),
					},
				},
				ConfigStateChecks: []statecheck.StateCheck{
					statecheck.ExpectKnownValue(resourceName, tfjsonpath.New("description"), knownvalue.Null()),
				},
			},
			{
				ConfigDirectory: config.StaticDirectory("testdata/response_policy"),
				ConfigVariables: config.Variables{
					"name":          config.StringVariable(rName),
					"platform_name": config.StringVariable("Windows"),
				},
				ResourceName:            resourceName,
				ImportState:             true,
				ImportStateVerify:       true,
				ImportStateVerifyIgnore: []string{"last_updated"},
			},
		},
	})
}

func TestAccResponsePolicyResource_enabled(t *testing.T) {
	rName := acctest.RandomResourceName()
	resourceName := "crowdstrike_response_policy.test"

	resource.ParallelTest(t, resource.TestCase{
		PreCheck:                 func() { acctest.PreCheck(t) },
		ProtoV6ProviderFactories: acctest.ProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			{
				ConfigDirectory: config.StaticDirectory("testdata/response_policy"),
				ConfigVariables: config.Variables{
					"enabled":       config.BoolVariable(true),
					"name":          config.StringVariable(rName),
					"platform_name": config.StringVariable("Windows"),
				},
				ConfigStateChecks: []statecheck.StateCheck{
					statecheck.ExpectKnownValue(resourceName, tfjsonpath.New("enabled"), knownvalue.Bool(true)),
				},
			},
			{
				ConfigDirectory: config.StaticDirectory("testdata/response_policy"),
				ConfigVariables: config.Variables{
					"enabled":       config.BoolVariable(false),
					"name":          config.StringVariable(rName),
					"platform_name": config.StringVariable("Windows"),
				},
				ConfigPlanChecks: resource.ConfigPlanChecks{
					PreApply: []plancheck.PlanCheck{
						plancheck.ExpectResourceAction(resourceName, plancheck.ResourceActionUpdate),
					},
				},
				ConfigStateChecks: []statecheck.StateCheck{
					statecheck.ExpectKnownValue(resourceName, tfjsonpath.New("enabled"), knownvalue.Bool(false)),
				},
			},
			{
				ConfigDirectory: config.StaticDirectory("testdata/response_policy"),
				ConfigVariables: config.Variables{
					"name":          config.StringVariable(rName),
					"platform_name": config.StringVariable("Windows"),
				},
				ConfigPlanChecks: resource.ConfigPlanChecks{
					PreApply: []plancheck.PlanCheck{
						plancheck.ExpectEmptyPlan(),
					},
				},
				ConfigStateChecks: []statecheck.StateCheck{
					statecheck.ExpectKnownValue(resourceName, tfjsonpath.New("enabled"), knownvalue.Bool(false)),
				},
			},
			{
				ConfigDirectory: config.StaticDirectory("testdata/response_policy"),
				ConfigVariables: config.Variables{
					"name":          config.StringVariable(rName),
					"platform_name": config.StringVariable("Windows"),
				},
				ResourceName:            resourceName,
				ImportState:             true,
				ImportStateVerify:       true,
				ImportStateVerifyIgnore: []string{"last_updated"},
			},
		},
	})
}

func TestAccResponsePolicyResource_execCommand(t *testing.T) {
	rName := acctest.RandomResourceName()
	resourceName := "crowdstrike_response_policy.test"

	resource.ParallelTest(t, resource.TestCase{
		PreCheck:                 func() { acctest.PreCheck(t) },
		ProtoV6ProviderFactories: acctest.ProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			{
				ConfigDirectory: config.StaticDirectory("testdata/response_policy"),
				ConfigVariables: config.Variables{
					"exec_command":  config.BoolVariable(true),
					"name":          config.StringVariable(rName),
					"platform_name": config.StringVariable("Windows"),
				},
				ConfigStateChecks: []statecheck.StateCheck{
					statecheck.ExpectKnownValue(resourceName, tfjsonpath.New("exec_command"), knownvalue.Bool(true)),
				},
			},
			{
				ConfigDirectory: config.StaticDirectory("testdata/response_policy"),
				ConfigVariables: config.Variables{
					"exec_command":  config.BoolVariable(false),
					"name":          config.StringVariable(rName),
					"platform_name": config.StringVariable("Windows"),
				},
				ConfigPlanChecks: resource.ConfigPlanChecks{
					PreApply: []plancheck.PlanCheck{
						plancheck.ExpectResourceAction(resourceName, plancheck.ResourceActionUpdate),
					},
				},
				ConfigStateChecks: []statecheck.StateCheck{
					statecheck.ExpectKnownValue(resourceName, tfjsonpath.New("exec_command"), knownvalue.Bool(false)),
				},
			},
			{
				ConfigDirectory: config.StaticDirectory("testdata/response_policy"),
				ConfigVariables: config.Variables{
					"name":          config.StringVariable(rName),
					"platform_name": config.StringVariable("Windows"),
				},
				ConfigPlanChecks: resource.ConfigPlanChecks{
					PreApply: []plancheck.PlanCheck{
						plancheck.ExpectEmptyPlan(),
					},
				},
				ConfigStateChecks: []statecheck.StateCheck{
					statecheck.ExpectKnownValue(resourceName, tfjsonpath.New("exec_command"), knownvalue.Bool(false)),
				},
			},
			{
				ConfigDirectory: config.StaticDirectory("testdata/response_policy"),
				ConfigVariables: config.Variables{
					"name":          config.StringVariable(rName),
					"platform_name": config.StringVariable("Windows"),
				},
				ResourceName:            resourceName,
				ImportState:             true,
				ImportStateVerify:       true,
				ImportStateVerifyIgnore: []string{"last_updated"},
			},
		},
	})
}

func TestAccResponsePolicyResource_falconScripts(t *testing.T) {
	rName := acctest.RandomResourceName()
	resourceName := "crowdstrike_response_policy.test"

	resource.ParallelTest(t, resource.TestCase{
		PreCheck:                 func() { acctest.PreCheck(t) },
		ProtoV6ProviderFactories: acctest.ProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			{
				ConfigDirectory: config.StaticDirectory("testdata/response_policy"),
				ConfigVariables: config.Variables{
					"falcon_scripts": config.BoolVariable(true),
					"name":           config.StringVariable(rName),
					"platform_name":  config.StringVariable("Windows"),
				},
				ConfigStateChecks: []statecheck.StateCheck{
					statecheck.ExpectKnownValue(resourceName, tfjsonpath.New("falcon_scripts"), knownvalue.Bool(true)),
				},
			},
			{
				ConfigDirectory: config.StaticDirectory("testdata/response_policy"),
				ConfigVariables: config.Variables{
					"falcon_scripts": config.BoolVariable(false),
					"name":           config.StringVariable(rName),
					"platform_name":  config.StringVariable("Windows"),
				},
				ConfigPlanChecks: resource.ConfigPlanChecks{
					PreApply: []plancheck.PlanCheck{
						plancheck.ExpectResourceAction(resourceName, plancheck.ResourceActionUpdate),
					},
				},
				ConfigStateChecks: []statecheck.StateCheck{
					statecheck.ExpectKnownValue(resourceName, tfjsonpath.New("falcon_scripts"), knownvalue.Bool(false)),
				},
			},
			{
				ConfigDirectory: config.StaticDirectory("testdata/response_policy"),
				ConfigVariables: config.Variables{
					"name":          config.StringVariable(rName),
					"platform_name": config.StringVariable("Windows"),
				},
				ConfigPlanChecks: resource.ConfigPlanChecks{
					PreApply: []plancheck.PlanCheck{
						plancheck.ExpectEmptyPlan(),
					},
				},
				ConfigStateChecks: []statecheck.StateCheck{
					statecheck.ExpectKnownValue(resourceName, tfjsonpath.New("falcon_scripts"), knownvalue.Bool(false)),
				},
			},
			{
				ConfigDirectory: config.StaticDirectory("testdata/response_policy"),
				ConfigVariables: config.Variables{
					"name":          config.StringVariable(rName),
					"platform_name": config.StringVariable("Windows"),
				},
				ResourceName:            resourceName,
				ImportState:             true,
				ImportStateVerify:       true,
				ImportStateVerifyIgnore: []string{"last_updated"},
			},
		},
	})
}

func TestAccResponsePolicyResource_getCommand(t *testing.T) {
	rName := acctest.RandomResourceName()
	resourceName := "crowdstrike_response_policy.test"

	resource.ParallelTest(t, resource.TestCase{
		PreCheck:                 func() { acctest.PreCheck(t) },
		ProtoV6ProviderFactories: acctest.ProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			{
				ConfigDirectory: config.StaticDirectory("testdata/response_policy"),
				ConfigVariables: config.Variables{
					"get_command":   config.BoolVariable(true),
					"name":          config.StringVariable(rName),
					"platform_name": config.StringVariable("Windows"),
				},
				ConfigStateChecks: []statecheck.StateCheck{
					statecheck.ExpectKnownValue(resourceName, tfjsonpath.New("get_command"), knownvalue.Bool(true)),
				},
			},
			{
				ConfigDirectory: config.StaticDirectory("testdata/response_policy"),
				ConfigVariables: config.Variables{
					"get_command":   config.BoolVariable(false),
					"name":          config.StringVariable(rName),
					"platform_name": config.StringVariable("Windows"),
				},
				ConfigPlanChecks: resource.ConfigPlanChecks{
					PreApply: []plancheck.PlanCheck{
						plancheck.ExpectResourceAction(resourceName, plancheck.ResourceActionUpdate),
					},
				},
				ConfigStateChecks: []statecheck.StateCheck{
					statecheck.ExpectKnownValue(resourceName, tfjsonpath.New("get_command"), knownvalue.Bool(false)),
				},
			},
			{
				ConfigDirectory: config.StaticDirectory("testdata/response_policy"),
				ConfigVariables: config.Variables{
					"name":          config.StringVariable(rName),
					"platform_name": config.StringVariable("Windows"),
				},
				ConfigPlanChecks: resource.ConfigPlanChecks{
					PreApply: []plancheck.PlanCheck{
						plancheck.ExpectEmptyPlan(),
					},
				},
				ConfigStateChecks: []statecheck.StateCheck{
					statecheck.ExpectKnownValue(resourceName, tfjsonpath.New("get_command"), knownvalue.Bool(false)),
				},
			},
			{
				ConfigDirectory: config.StaticDirectory("testdata/response_policy"),
				ConfigVariables: config.Variables{
					"name":          config.StringVariable(rName),
					"platform_name": config.StringVariable("Windows"),
				},
				ResourceName:            resourceName,
				ImportState:             true,
				ImportStateVerify:       true,
				ImportStateVerifyIgnore: []string{"last_updated"},
			},
		},
	})
}

func TestAccResponsePolicyResource_hostGroups(t *testing.T) {
	t.Skip("testgen: references to other resources are not supported yet")
}

func TestAccResponsePolicyResource_memdumpCommand(t *testing.T) {
	rName := acctest.RandomResourceName()
	resourceName := "crowdstrike_response_policy.test"

	resource.ParallelTest(t, resource.TestCase{
		PreCheck:                 func() { acctest.PreCheck(t) },
		ProtoV6ProviderFactories: acctest.ProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			{
				ConfigDirectory: config.StaticDirectory("testdata/response_policy"),
				ConfigVariables: config.Variables{
					"memdump_command": config.BoolVariable(true),
					"name":            config.StringVariable(rName),
					"platform_name":   config.StringVariable("Windows"),
				},
				ConfigStateChecks: []statecheck.StateCheck{
					statecheck.ExpectKnownValue(resourceName, tfjsonpath.New("memdump_command"), knownvalue.Bool(true)),
				},
			},
			{
				ConfigDirectory: config.StaticDirectory("testdata/response_policy"),
				ConfigVariables: config.Variables{
					"memdump_command": config.BoolVariable(false),
					"name":            config.StringVariable(rName),
					"platform_name":   config.StringVariable("Windows"),
				},
				ConfigPlanChecks: resource.ConfigPlanChecks{
					PreApply: []plancheck.PlanCheck{
						plancheck.ExpectResourceAction(resourceName, plancheck.ResourceActionUpdate),
					},
				},
				ConfigStateChecks: []statecheck.StateCheck{
					statecheck.ExpectKnownValue(resourceName, tfjsonpath.New("memdump_command"), knownvalue.Bool(false)),
				},
			},
			{
				ConfigDirectory: config.StaticDirectory("testdata/response_policy"),
				ConfigVariables: config.Variables{
					"name":          config.StringVariable(rName),
					"platform_name": config.StringVariable("Windows"),
				},
				ConfigPlanChecks: resource.ConfigPlanChecks{
					PreApply: []plancheck.PlanCheck{
						plancheck.ExpectEmptyPlan(),
					},
				},
				ConfigStateChecks: []statecheck.StateCheck{
					statecheck.ExpectKnownValue(resourceName, tfjsonpath.New("memdump_command"), knownvalue.Bool(false)),
				},
			},
			{
				ConfigDirectory: config.StaticDirectory("testdata/response_policy"),
				ConfigVariables: config.Variables{
					"name":          config.StringVariable(rName),
					"platform_name": config.StringVariable("Windows"),
				},
				ResourceName:            resourceName,
				ImportState:             true,
				ImportStateVerify:       true,
				ImportStateVerifyIgnore: []string{"last_updated"},
			},
		},
	})
}

func TestAccResponsePolicyResource_name(t *testing.T) {
	rName := acctest.RandomResourceName()
	resourceName := "crowdstrike_response_policy.test"

	resource.ParallelTest(t, resource.TestCase{
		PreCheck:                 func() { acctest.PreCheck(t) },
		ProtoV6ProviderFactories: acctest.ProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			{
				ConfigDirectory: config.StaticDirectory("testdata/response_policy"),
				ConfigVariables: config.Variables{
					"name":          config.StringVariable(rName),
					"platform_name": config.StringVariable("Windows"),
				},
				ConfigStateChecks: []statecheck.StateCheck{
					statecheck.ExpectKnownValue(resourceName, tfjsonpath.New("name"), knownvalue.StringExact(rName)),
				},
			},
			{
				ConfigDirectory: config.StaticDirectory("testdata/response_policy"),
				ConfigVariables: config.Variables{
					"name":          config.StringVariable(rName + "-updated"),
					"platform_name": config.StringVariable("Windows"),
				},
				ConfigPlanChecks: resource.ConfigPlanChecks{
					PreApply: []plancheck.PlanCheck{
						plancheck.ExpectResourceAction(resourceName, plancheck.ResourceActionUpdate),
					},
				},
				ConfigStateChecks: []statecheck.StateCheck{
					statecheck.ExpectKnownValue(resourceName, tfjsonpath.New("name"), knownvalue.StringExact(rName+"-updated")),
				},
			},
			{
				ConfigDirectory: config.StaticDirectory("testdata/response_policy"),
				ConfigVariables: config.Variables{
					"name":          config.StringVariable(rName + "-updated"),
					"platform_name": config.StringVariable("Windows"),
				},
				ResourceName:            resourceName,
				ImportState:             true,
				ImportStateVerify:       true,
				ImportStateVerifyIgnore: []string{"last_updated"},
			},
		},
	})
}

func TestAccResponsePolicyResource_platformName(t *testing.T) {
	rName := acctest.RandomResourceName()
	resourceName := "crowdstrike_response_policy.test"

	resource.ParallelTest(t, resource.TestCase{
		PreCheck:                 func() { acctest.PreCheck(t) },
		ProtoV6ProviderFactories: acctest.ProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			{
				ConfigDirectory: config.StaticDirectory("testdata/response_policy"),
				ConfigVariables: config.Variables{
					"name":          config.StringVariable(rName),
					"platform_name": config.StringVariable("Windows"),
				},
				ConfigStateChecks: []statecheck.StateCheck{
					statecheck.ExpectKnownValue(resourceName, tfjsonpath.New("platform_name"), knownvalue.StringExact("Windows")),
				},
			},
			{
				ConfigDirectory: config.StaticDirectory("testdata/response_policy"),
				ConfigVariables: config.Variables{
					"name":          config.StringVariable(rName),
					"platform_name": config.StringVariable("Mac"),
				},
				ConfigPlanChecks: resource.ConfigPlanChecks{
					PreApply: []plancheck.PlanCheck{
						plancheck.ExpectResourceAction(resourceName, plancheck.ResourceActionDestroyBeforeCreate),
					},
				},
				ConfigStateChecks: []statecheck.StateCheck{
					statecheck.ExpectKnownValue(resourceName, tfjsonpath.New("platform_name"), knownvalue.StringExact("Mac")),
				},
			},
			{
				ConfigDirectory: config.StaticDirectory("testdata/response_policy"),
				ConfigVariables: config.Variables{
					"name":          config.StringVariable(rName),
					"platform_name": config.StringVariable("Linux"),
				},
				ConfigPlanChecks: resource.ConfigPlanChecks{
					PreApply: []plancheck.PlanCheck{
						plancheck.ExpectResourceAction(resourceName, plancheck.ResourceActionDestroyBeforeCreate),
					},
				},
				ConfigStateChecks: []statecheck.StateCheck{
					statecheck.ExpectKnownValue(resourceName, tfjsonpath.New("platform_name"), knownvalue.StringExact("Linux")),
				},
			},
			{
				ConfigDirectory: config.StaticDirectory("testdata/response_policy"),
				ConfigVariables: config.Variables{
					"name":          config.StringVariable(rName),
					"platform_name": config.StringVariable("Linux"),
				},
				ResourceName:            resourceName,
				ImportState:             true,
				ImportStateVerify:       true,
				ImportStateVerifyIgnore: []string{"last_updated"},
			},
		},
	})
}

func TestAccResponsePolicyResource_putAndRunCommand(t *testing.T) {
	rName := acctest.RandomResourceName()
	resourceName := "crowdstrike_response_policy.test"

	resource.ParallelTest(t, resource.TestCase{
		PreCheck:                 func() { acctest.PreCheck(t) },
		ProtoV6ProviderFactories: acctest.ProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			{
				ConfigDirectory: config.StaticDirectory("testdata/response_policy"),
				ConfigVariables: config.Variables{
					"name":                config.StringVariable(rName),
					"platform_name":       config.StringVariable("Windows"),
					"put_and_run_command": config.BoolVariable(true),
				},
				ConfigStateChecks: []statecheck.StateCheck{
					statecheck.ExpectKnownValue(resourceName, tfjsonpath.New("put_and_run_command"), knownvalue.Bool(true)),
				},
			},
			{
				ConfigDirectory: config.StaticDirectory("testdata/response_policy"),
				ConfigVariables: config.Variables{
					"name":                config.StringVariable(rName),
					"platform_name":       config.StringVariable("Windows"),
					"put_and_run_command": config.BoolVariable(false),
				},
				ConfigPlanChecks: resource.ConfigPlanChecks{
					PreApply: []plancheck.PlanCheck{
						plancheck.ExpectResourceAction(resourceName, plancheck.ResourceActionUpdate),
					},
				},
				ConfigStateChecks: []statecheck.StateCheck{
					statecheck.ExpectKnownValue(resourceName, tfjsonpath.New("put_and_run_command"), knownvalue.Bool(false)),
				},
			},
			{
				ConfigDirectory: config.StaticDirectory("testdata/response_policy"),
				ConfigVariables: config.Variables{
					"name":          config.StringVariable(rName),
					"platform_name": config.StringVariable("Windows"),
				},
				ConfigPlanChecks: resource.ConfigPlanChecks{
					PreApply: []plancheck.PlanCheck{
						plancheck.ExpectEmptyPlan(),
					},
				},
				ConfigStateChecks: []statecheck.StateCheck{
					statecheck.ExpectKnownValue(resourceName, tfjsonpath.New("put_and_run_command"), knownvalue.Bool(false)),
				},
			},
			{
				ConfigDirectory: config.StaticDirectory("testdata/response_policy"),
				ConfigVariables: config.Variables{
					"name":          config.StringVariable(rName),
					"platform_name": config.StringVariable("Windows"),
				},
				ResourceName:            resourceName,
				ImportState:             true,
				ImportStateVerify:       true,
				ImportStateVerifyIgnore: []string{"last_updated"},
			},
		},
	})
}

func TestAccResponsePolicyResource_putCommand(t *testing.T) {
	rName := acctest.RandomResourceName()
	resourceName := "crowdstrike_response_policy.test"

	resource.ParallelTest(t, resource.TestCase{
		PreCheck:                 func() { acctest.PreCheck(t) },
		ProtoV6ProviderFactories: acctest.ProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			{
				ConfigDirectory: config.StaticDirectory("testdata/response_policy"),
				ConfigVariables: config.Variables{
					"name":          config.StringVariable(rName),
					"platform_name": config.StringVariable("Windows"),
					"put_command":   config.BoolVariable(true),
				},
				ConfigStateChecks: []statecheck.StateCheck{
					statecheck.ExpectKnownValue(resourceName, tfjsonpath.New("put_command"), knownvalue.Bool(true)),
				},
			},
			{
				ConfigDirectory: config.StaticDirectory("testdata/response_policy"),
				ConfigVariables: config.Variables{
					"name":          config.StringVariable(rName),
					"platform_name": config.StringVariable("Windows"),
					"put_command":   config.BoolVariable(false),
				},
				ConfigPlanChecks: resource.ConfigPlanChecks{
					PreApply: []plancheck.PlanCheck{
						plancheck.ExpectResourceAction(resourceName, plancheck.ResourceActionUpdate),
					},
				},
				ConfigStateChecks: []statecheck.StateCheck{
					statecheck.ExpectKnownValue(resourceName, tfjsonpath.New("put_command"), knownvalue.Bool(false)),
				},
			},
			{
				ConfigDirectory: config.StaticDirectory("testdata/response_policy"),
				ConfigVariables: config.Variables{
					"name":          config.StringVariable(rName),
					"platform_name": config.StringVariable("Windows"),
				},
				ConfigPlanChecks: resource.ConfigPlanChecks{
					PreApply: []plancheck.PlanCheck{
						plancheck.ExpectEmptyPlan(),
					},
				},
				ConfigStateChecks: []statecheck.StateCheck{
					statecheck.ExpectKnownValue(resourceName, tfjsonpath.New("put_command"), knownvalue.Bool(false)),
				},
			},
			{
				ConfigDirectory: config.StaticDirectory("testdata/response_policy"),
				ConfigVariables: config.Variables{
					"name":          config.StringVariable(rName),
					"platform_name": config.StringVariable("Windows"),
				},
				ResourceName:            resourceName,
				ImportState:             true,
				ImportStateVerify:       true,
				ImportStateVerifyIgnore: []string{"last_updated"},
			},
		},
	})
}

func TestAccResponsePolicyResource_realTimeResponse(t *testing.T) {
	rName := acctest.RandomResourceName()
	resourceName := "crowdstrike_response_policy.test"

	resource.ParallelTest(t, resource.TestCase{
		PreCheck:                 func() { acctest.PreCheck(t) },
		ProtoV6ProviderFactories: acctest.ProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			{
				ConfigDirectory: config.StaticDirectory("testdata/response_policy"),
				ConfigVariables: config.Variables{
					"name":               config.StringVariable(rName),
					"platform_name":      config.StringVariable("Windows"),
					"real_time_response": config.BoolVariable(true),
				},
				ConfigStateChecks: []statecheck.StateCheck{
					statecheck.ExpectKnownValue(resourceName, tfjsonpath.New("real_time_response"), knownvalue.Bool(true)),
				},
			},
			{
				ConfigDirectory: config.StaticDirectory("testdata/response_policy"),
				ConfigVariables: config.Variables{
					"name":               config.StringVariable(rName),
					"platform_name":      config.StringVariable("Windows"),
					"real_time_response": config.BoolVariable(false),
				},
				ConfigPlanChecks: resource.ConfigPlanChecks{
					PreApply: []plancheck.PlanCheck{
						plancheck.ExpectResourceAction(resourceName, plancheck.ResourceActionUpdate),
					},
				},
				ConfigStateChecks: []statecheck.StateCheck{
					statecheck.ExpectKnownValue(resourceName, tfjsonpath.New("real_time_response"), knownvalue.Bool(false)),
				},
			},
			{
				ConfigDirectory: config.StaticDirectory("testdata/response_policy"),
				ConfigVariables: config.Variables{
					"name":          config.StringVariable(rName),
					"platform_name": config.StringVariable("Windows"),
				},
				ConfigPlanChecks: resource.ConfigPlanChecks{
					PreApply: []plancheck.PlanCheck{
						plancheck.ExpectEmptyPlan(),
					},
				},
				ConfigStateChecks: []statecheck.StateCheck{
					statecheck.ExpectKnownValue(resourceName, tfjsonpath.New("real_time_response"), knownvalue.Bool(false)),
				},
			},
			{
				ConfigDirectory: config.StaticDirectory("testdata/response_policy"),
				ConfigVariables: config.Variables{
					"name":          config.StringVariable(rName),
					"platform_name": config.StringVariable("Windows"),
				},
				ResourceName:            resourceName,
				ImportState:             true,
				ImportStateVerify:       true,
				ImportStateVerifyIgnore: []string{"last_updated"},
			},
		},
	})
}

func TestAccResponsePolicyResource_xmemdumpCommand(t *testing.T) {
	rName := acctest.RandomResourceName()
	resourceName := "crowdstrike_response_policy.test"

	resource.ParallelTest(t, resource.TestCase{
		PreCheck:                 func() { acctest.PreCheck(t) },
		ProtoV6ProviderFactories: acctest.ProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			{
				ConfigDirectory: config.StaticDirectory("testdata/response_policy"),
				ConfigVariables: config.Variables{
					"name":             config.StringVariable(rName),
					"platform_name":    config.StringVariable("Windows"),
					"xmemdump_command": config.BoolVariable(true),
				},
				ConfigStateChecks: []statecheck.StateCheck{
					statecheck.ExpectKnownValue(resourceName, tfjsonpath.New("xmemdump_command"), knownvalue.Bool(true)),
				},
			},
			{
				ConfigDirectory: config.StaticDirectory("testdata/response_policy"),
				ConfigVariables: config.Variables{
					"name":             config.StringVariable(rName),
					"platform_name":    config.StringVariable("Windows"),
					"xmemdump_command": config.BoolVariable(false),
				},
				ConfigPlanChecks: resource.ConfigPlanChecks{
					PreApply: []plancheck.PlanCheck{
						plancheck.ExpectResourceAction(resourceName, plancheck.ResourceActionUpdate),
					},
				},
				ConfigStateChecks: []statecheck.StateCheck{
					statecheck.ExpectKnownValue(resourceName, tfjsonpath.New("xmemdump_command"), knownvalue.Bool(false)),
				},
			},
			{
				ConfigDirectory: config.StaticDirectory("testdata/response_policy"),
				ConfigVariables: config.Variables{
					"name":          config.StringVariable(rName),
					"platform_name": config.StringVariable("Windows"),
				},
				ConfigPlanChecks: resource.ConfigPlanChecks{
					PreApply: []plancheck.PlanCheck{
						plancheck.ExpectEmptyPlan(),
					},
				},
				ConfigStateChecks: []statecheck.StateCheck{
					statecheck.ExpectKnownValue(resourceName, tfjsonpath.New("xmemdump_command"), knownvalue.Bool(false)),
				},
			},
			{
				ConfigDirectory: config.StaticDirectory("testdata/response_policy"),
				ConfigVariables: config.Variables{
					"name":          config.StringVariable(rName),
					"platform_name": config.StringVariable("Windows"),
				},
				ResourceName:            resourceName,
				ImportState:             true,
				ImportStateVerify:       true,
				ImportStateVerifyIgnore: []string{"last_updated"},
			},
		},
	})
}
