# Code generated by testgen. DO NOT EDIT.

variable "description" {
  type    = string
  default = null
}

variable "min_match_threshold" {
  type    = number
  default = null
}

variable "name" {
  type    = string
  default = null
}

variable "regex" {
  type    = string
  default = null
}

resource "crowdstrike_data_protection_content_pattern" "test" {
  description         = var.description
  min_match_threshold = var.min_match_threshold
  name                = var.name
  regex               = var.regex
}
