# Code generated by testgen. DO NOT EDIT.

variable "be_custom_splash_message" {
  type    = string
  default = null
}

variable "be_exclude_domains" {
  type    = set(string)
  default = null
}

variable "be_paste_clipboard_block_over_max_size" {
  type    = bool
  default = null
}

variable "be_paste_clipboard_max_size" {
  type    = number
  default = null
}

variable "be_paste_clipboard_max_size_unit" {
  type    = string
  default = null
}

variable "be_paste_clipboard_min_size" {
  type    = number
  default = null
}

variable "be_paste_clipboard_min_size_unit" {
  type    = string
  default = null
}

variable "be_paste_timeout_milliseconds" {
  type    = number
  default = null
}

variable "be_paste_timeout_response" {
  type    = string
  default = null
}

variable "be_splash_screen" {
  type    = bool
  default = null
}

variable "be_upload_timeout_response" {
  type    = string
  default = null
}

variable "be_upload_timeout_seconds" {
  type    = number
  default = null
}

variable "block_all_data_access" {
  type    = bool
  default = null
}

variable "browsers_without_active_extension" {
  type    = string
  default = null
}

variable "classifications" {
  type    = set(string)
  default = null
}

variable "clipboard_inspection" {
  type    = bool
  default = null
}

variable "clipboard_web_origin" {
  type    = bool
  default = null
}

variable "content_inspection" {
  type    = bool
  default = null
}

variable "context_inspection" {
  type    = bool
  default = null
}

variable "custom_allowed_action_notification" {
  type    = string
  default = null
}

variable "custom_blocked_action_notification" {
  type    = string
  default = null
}

variable "description" {
  type    = string
  default = null
}

variable "enable_ocr" {
  type    = bool
  default = null
}

variable "enabled" {
  type    = bool
  default = null
}

variable "end_user_encryption_activity" {
  type    = bool
  default = null
}

variable "euj_business_purposes_enabled" {
  type    = bool
  default = null
}

variable "euj_company_logo" {
  type    = string
  default = null
}

variable "euj_custom_dropdown_options" {
  type    = list(string)
  default = null
}

variable "euj_custom_header_text" {
  type    = string
  default = null
}

variable "euj_dialog_timeout" {
  type    = number
  default = null
}

variable "euj_personal_use_enabled" {
  type    = bool
  default = null
}

variable "euj_require_additional_details" {
  type    = bool
  default = null
}

variable "evidence_storage" {
  type    = bool
  default = null
}

variable "evidence_storage_max_free_space_percent" {
  type    = number
  default = null
}

variable "evidence_storage_max_size_gib" {
  type    = number
  default = null
}

variable "host_groups" {
  type    = set(string)
  default = null
}

variable "inspection_confidence" {
  type    = string
  default = null
}

variable "inspection_depth" {
  type    = string
  default = null
}

variable "max_file_size" {
  type    = number
  default = null
}

variable "max_file_size_unit" {
  type    = string
  default = null
}

variable "minimum_similarity_threshold" {
  type    = string
  default = null
}

variable "name" {
  type    = string
  default = null
}

variable "network_inspection" {
  type    = bool
  default = null
}

variable "network_inspection_files_exceeding_size_limit" {
  type    = string
  default = null
}

variable "platform_name" {
  type    = string
  default = null
}

variable "screen_capture" {
  type    = bool
  default = null
}

variable "screen_capture_post_event_seconds" {
  type    = string
  default = null
}

variable "screen_capture_pre_event_seconds" {
  type    = string
  default = null
}

variable "similarity_detection" {
  type    = bool
  default = null
}

resource "crowdstrike_data_protection_policy" "test" {
  be_custom_splash_message                      = var.be_custom_splash_message
  be_exclude_domains                            = var.be_exclude_domains
  be_paste_clipboard_block_over_max_size        = var.be_paste_clipboard_block_over_max_size
  be_paste_clipboard_max_size                   = var.be_paste_clipboard_max_size
  be_paste_clipboard_max_size_unit              = var.be_paste_clipboard_max_size_unit
  be_paste_clipboard_min_size                   = var.be_paste_clipboard_min_size
  be_paste_clipboard_min_size_unit              = var.be_paste_clipboard_min_size_unit
  be_paste_timeout_milliseconds                 = var.be_paste_timeout_milliseconds
  be_paste_timeout_response                     = var.be_paste_timeout_response
  be_splash_screen                              = var.be_splash_screen
  be_upload_timeout_response                    = var.be_upload_timeout_response
  be_upload_timeout_seconds                     = var.be_upload_timeout_seconds
  block_all_data_access                         = var.block_all_data_access
  browsers_without_active_extension             = var.browsers_without_active_extension
  classifications                               = var.classifications
  clipboard_inspection                          = var.clipboard_inspection
  clipboard_web_origin                          = var.clipboard_web_origin
  content_inspection                            = var.content_inspection
  context_inspection                            = var.context_inspection
  custom_allowed_action_notification            = var.custom_allowed_action_notification
  custom_blocked_action_notification            = var.custom_blocked_action_notification
  description                                   = var.description
  enable_ocr                                    = var.enable_ocr
  enabled                                       = var.enabled
  end_user_encryption_activity                  = var.end_user_encryption_activity
  euj_business_purposes_enabled                 = var.euj_business_purposes_enabled
  euj_company_logo                              = var.euj_company_logo
  euj_custom_dropdown_options                   = var.euj_custom_dropdown_options
  euj_custom_header_text                        = var.euj_custom_header_text
  euj_dialog_timeout                            = var.euj_dialog_timeout
  euj_personal_use_enabled                      = var.euj_personal_use_enabled
  euj_require_additional_details                = var.euj_require_additional_details
  evidence_storage                              = var.evidence_storage
  evidence_storage_max_free_space_percent       = var.evidence_storage_max_free_space_percent
  evidence_storage_max_size_gib                 = var.evidence_storage_max_size_gib
  host_groups                                   = var.host_groups
  inspection_confidence                         = var.inspection_confidence
  inspection_depth                              = var.inspection_depth
  max_file_size                                 = var.max_file_size
  max_file_size_unit                            = var.max_file_size_unit
  minimum_similarity_threshold                  = var.minimum_similarity_threshold
  name                                          = var.name
  network_inspection                            = var.network_inspection
  network_inspection_files_exceeding_size_limit = var.network_inspection_files_exceeding_size_limit
  platform_name                                 = var.platform_name
  screen_capture                                = var.screen_capture
  screen_capture_post_event_seconds             = var.screen_capture_post_event_seconds
  screen_capture_pre_event_seconds              = var.screen_capture_pre_event_seconds
  similarity_detection                          = var.similarity_detection
}
