// Code generated by testgen. DO NOT EDIT.

package hostgroups_test

import (
	"testing"

	"github.com/crowdstrike/terraform-provider-crowdstrike/internal/acctest"
	hostgroups "github.com/crowdstrike/terraform-provider-crowdstrike/internal/host_groups"
	"github.com/hashicorp/terraform-plugin-testing/config"
	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
	"github.com/hashicorp/terraform-plugin-testing/knownvalue"
	"github.com/hashicorp/terraform-plugin-testing/plancheck"
	"github.com/hashicorp/terraform-plugin-testing/statecheck"
	"github.com/hashicorp/terraform-plugin-testing/tfjsonpath"
)

func TestAccHostGroupResource_basic(t *testing.T) {
	rName := acctest.RandomResourceName()
	resourceName := "crowdstrike_host_group.test"

	resource.ParallelTest(t, resource.TestCase{
		PreCheck:                 func() { acctest.PreCheck(t) },
		ProtoV6ProviderFactories: acctest.ProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			{
				ConfigDirectory: config.StaticDirectory("testdata/host_group"),
				ConfigVariables: config.Variables{
					"assignment_rule": config.StringVariable("hostname:'tf-acc-test-a'"),
					"description":     config.StringVariable(rName),
					"name":            config.StringVariable(rName),
					"type":            config.StringVariable("dynamic"),
				},
				ConfigStateChecks: []statecheck.StateCheck{
					statecheck.ExpectKnownValue(resourceName, tfjsonpath.New("id"), knownvalue.NotNull()),
					statecheck.ExpectKnownValue(resourceName, tfjsonpath.New("last_updated"), knownvalue.NotNull()),
				},
			},
			{
				ConfigDirectory: config.StaticDirectory("testdata/host_group"),
				ConfigVariables: config.Variables{
					"assignment_rule": config.StringVariable("hostname:'tf-acc-test-a'"),
					"description":     config.StringVariable(rName),
					"name":            config.StringVariable(rName),
					"type":            config.StringVariable("dynamic"),
				},
				ResourceName:            resourceName,
				ImportState:             true,
				ImportStateVerify:       true,
				ImportStateVerifyIgnore: []string{"last_updated"},
			},
		},
	})
}

func TestAccHostGroupResource_disappears(t *testing.T) {
	rName := acctest.RandomResourceName()
	resourceName := "crowdstrike_host_group.test"

	resource.ParallelTest(t, resource.TestCase{
		PreCheck:                 func() { acctest.PreCheck(t) },
		ProtoV6ProviderFactories: acctest.ProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			{
				ConfigDirectory: config.StaticDirectory("testdata/host_group"),
				ConfigVariables: config.Variables{
					"assignment_rule": config.StringVariable("hostname:'tf-acc-test-a'"),
					"description":     config.StringVariable(rName),
					"name":            config.StringVariable(rName),
					"type":            config.StringVariable("dynamic"),
				},
				Check:              acctest.CheckResourceDisappears(hostgroups.NewHostGroupResource, resourceName),
				ExpectNonEmptyPlan: true,
				ConfigPlanChecks: resource.ConfigPlanChecks{
					PostApplyPostRefresh: []plancheck.PlanCheck{
						plancheck.ExpectResourceAction(resourceName, plancheck.ResourceActionCreate),
					},
				},
			},
		},
	})
}

// TestAccHostGroupResource_assignmentRule has no omit step because provider validation rejects omitting assignment_rule in this configuration: AttributeName("assignment_rule"): Error validating host group: The assignment_rule attribute is required for dynamic host groups.
func TestAccHostGroupResource_assignmentRule(t *testing.T) {
	rName := acctest.RandomResourceName()
	resourceName := "crowdstrike_host_group.test"

	resource.ParallelTest(t, resource.TestCase{
		PreCheck:                 func() { acctest.PreCheck(t) },
		ProtoV6ProviderFactories: acctest.ProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			{
				ConfigDirectory: config.StaticDirectory("testdata/host_group"),
				ConfigVariables: config.Variables{
					"assignment_rule": config.StringVariable("hostname:'tf-acc-test-a'"),
					"description":     config.StringVariable(rName),
					"name":            config.StringVariable(rName),
					"type":            config.StringVariable("dynamic"),
				},
				ConfigStateChecks: []statecheck.StateCheck{
					statecheck.ExpectKnownValue(resourceName, tfjsonpath.New("assignment_rule"), knownvalue.StringExact("hostname:'tf-acc-test-a'")),
				},
			},
			{
				ConfigDirectory: config.StaticDirectory("testdata/host_group"),
				ConfigVariables: config.Variables{
					"assignment_rule": config.StringVariable("hostname:'tf-acc-test-b'"),
					"description":     config.StringVariable(rName),
					"name":            config.StringVariable(rName),
					"type":            config.StringVariable("dynamic"),
				},
				ConfigPlanChecks: resource.ConfigPlanChecks{
					PreApply: []plancheck.PlanCheck{
						plancheck.ExpectResourceAction(resourceName, plancheck.ResourceActionUpdate),
					},
				},
				ConfigStateChecks: []statecheck.StateCheck{
					statecheck.ExpectKnownValue(resourceName, tfjsonpath.New("assignment_rule"), knownvalue.StringExact("hostname:'tf-acc-test-b'")),
				},
			},
			{
				ConfigDirectory: config.StaticDirectory("testdata/host_group"),
				ConfigVariables: config.Variables{
					"assignment_rule": config.StringVariable("hostname:'tf-acc-test-b'"),
					"description":     config.StringVariable(rName),
					"name":            config.StringVariable(rName),
					"type":            config.StringVariable("dynamic"),
				},
				ResourceName:            resourceName,
				ImportState:             true,
				ImportStateVerify:       true,
				ImportStateVerifyIgnore: []string{"last_updated"},
			},
		},
	})
}

func TestAccHostGroupResource_description(t *testing.T) {
	rName := acctest.RandomResourceName()
	resourceName := "crowdstrike_host_group.test"

	resource.ParallelTest(t, resource.TestCase{
		PreCheck:                 func() { acctest.PreCheck(t) },
		ProtoV6ProviderFactories: acctest.ProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			{
				ConfigDirectory: config.StaticDirectory("testdata/host_group"),
				ConfigVariables: config.Variables{
					"assignment_rule": config.StringVariable("hostname:'tf-acc-test-a'"),
					"description":     config.StringVariable(rName),
					"name":            config.StringVariable(rName),
					"type":            config.StringVariable("dynamic"),
				},
				ConfigStateChecks: []statecheck.StateCheck{
					statecheck.ExpectKnownValue(resourceName, tfjsonpath.New("description"), knownvalue.StringExact(rName)),
				},
			},
			{
				ConfigDirectory: config.StaticDirectory("testdata/host_group"),
				ConfigVariables: config.Variables{
					"assignment_rule": config.StringVariable("hostname:'tf-acc-test-a'"),
					"description":     config.StringVariable(rName + "-updated"),
					"name":            config.StringVariable(rName),
					"type":            config.StringVariable("dynamic"),
				},
				ConfigPlanChecks: resource.ConfigPlanChecks{
					PreApply: []plancheck.PlanCheck{
						plancheck.ExpectResourceAction(resourceName, plancheck.ResourceActionUpdate),
					},
				},
				ConfigStateChecks: []statecheck.StateCheck{
					statecheck.ExpectKnownValue(resourceName, tfjsonpath.New("description"), knownvalue.StringExact(rName+"-updated")),
				},
			},
			{
				ConfigDirectory: config.StaticDirectory("testdata/host_group"),
				ConfigVariables: config.Variables{
					"assignment_rule": config.StringVariable("hostname:'tf-acc-test-a'"),
					"description":     config.StringVariable(rName + "-updated"),
					"name":            config.StringVariable(rName),
					"type":            config.StringVariable("dynamic"),
				},
				ResourceName:            resourceName,
				ImportState:             true,
				ImportStateVerify:       true,
				ImportStateVerifyIgnore: []string{"last_updated"},
			},
		},
	})
}

func TestAccHostGroupResource_hostIds(t *testing.T) {
	t.Skip("testgen: host IDs must reference real hosts in the tenant")
}

// TestAccHostGroupResource_hostnames has no omit step because provider validation rejects omitting hostnames in this configuration: AttributeName("hostnames"): Error validating host group: The hostnames attribute is required for static host groups.
func TestAccHostGroupResource_hostnames(t *testing.T) {
	rName := acctest.RandomResourceName()
	resourceName := "crowdstrike_host_group.test"

	resource.ParallelTest(t, resource.TestCase{
		PreCheck:                 func() { acctest.PreCheck(t) },
		ProtoV6ProviderFactories: acctest.ProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			{
				ConfigDirectory: config.StaticDirectory("testdata/host_group"),
				ConfigVariables: config.Variables{
					"description": config.StringVariable(rName),
					"hostnames":   config.SetVariable(config.StringVariable("TF-ACC-HOST-1"), config.StringVariable("TF-ACC-HOST-2")),
					"name":        config.StringVariable(rName),
					"type":        config.StringVariable("static"),
				},
				ConfigStateChecks: []statecheck.StateCheck{
					statecheck.ExpectKnownValue(resourceName, tfjsonpath.New("hostnames"), knownvalue.SetExact([]knownvalue.Check{knownvalue.StringExact("TF-ACC-HOST-1"), knownvalue.StringExact("TF-ACC-HOST-2")})),
				},
			},
			{
				ConfigDirectory: config.StaticDirectory("testdata/host_group"),
				ConfigVariables: config.Variables{
					"description": config.StringVariable(rName),
					"hostnames":   config.SetVariable(config.StringVariable("TF-ACC-HOST-1"), config.StringVariable("TF-ACC-HOST-2"), config.StringVariable("TF-ACC-HOST-3")),
					"name":        config.StringVariable(rName),
					"type":        config.StringVariable("static"),
				},
				ConfigPlanChecks: resource.ConfigPlanChecks{
					PreApply: []plancheck.PlanCheck{
						plancheck.ExpectResourceAction(resourceName, plancheck.ResourceActionUpdate),
					},
				},
				ConfigStateChecks: []statecheck.StateCheck{
					statecheck.ExpectKnownValue(resourceName, tfjsonpath.New("hostnames"), knownvalue.SetExact([]knownvalue.Check{knownvalue.StringExact("TF-ACC-HOST-1"), knownvalue.StringExact("TF-ACC-HOST-2"), knownvalue.StringExact("TF-ACC-HOST-3")})),
				},
			},
			{
				ConfigDirectory: config.StaticDirectory("testdata/host_group"),
				ConfigVariables: config.Variables{
					"description": config.StringVariable(rName),
					"hostnames":   config.SetVariable(config.StringVariable("TF-ACC-HOST-3"), config.StringVariable("TF-ACC-HOST-1"), config.StringVariable("TF-ACC-HOST-2")),
					"name":        config.StringVariable(rName),
					"type":        config.StringVariable("static"),
				},
				ConfigPlanChecks: resource.ConfigPlanChecks{
					PreApply: []plancheck.PlanCheck{
						plancheck.ExpectEmptyPlan(),
					},
				},
				ConfigStateChecks: []statecheck.StateCheck{
					statecheck.ExpectKnownValue(resourceName, tfjsonpath.New("hostnames"), knownvalue.SetExact([]knownvalue.Check{knownvalue.StringExact("TF-ACC-HOST-3"), knownvalue.StringExact("TF-ACC-HOST-1"), knownvalue.StringExact("TF-ACC-HOST-2")})),
				},
			},
			{
				ConfigDirectory: config.StaticDirectory("testdata/host_group"),
				ConfigVariables: config.Variables{
					"description": config.StringVariable(rName),
					"hostnames":   config.SetVariable(config.StringVariable("TF-ACC-HOST-3"), config.StringVariable("TF-ACC-HOST-2")),
					"name":        config.StringVariable(rName),
					"type":        config.StringVariable("static"),
				},
				ConfigPlanChecks: resource.ConfigPlanChecks{
					PreApply: []plancheck.PlanCheck{
						plancheck.ExpectResourceAction(resourceName, plancheck.ResourceActionUpdate),
					},
				},
				ConfigStateChecks: []statecheck.StateCheck{
					statecheck.ExpectKnownValue(resourceName, tfjsonpath.New("hostnames"), knownvalue.SetExact([]knownvalue.Check{knownvalue.StringExact("TF-ACC-HOST-3"), knownvalue.StringExact("TF-ACC-HOST-2")})),
				},
			},
			{
				ConfigDirectory: config.StaticDirectory("testdata/host_group"),
				ConfigVariables: config.Variables{
					"description": config.StringVariable(rName),
					"hostnames":   config.SetVariable([]config.Variable{}...),
					"name":        config.StringVariable(rName),
					"type":        config.StringVariable("static"),
				},
				ConfigPlanChecks: resource.ConfigPlanChecks{
					PreApply: []plancheck.PlanCheck{
						plancheck.ExpectResourceAction(resourceName, plancheck.ResourceActionUpdate),
					},
				},
				ConfigStateChecks: []statecheck.StateCheck{
					statecheck.ExpectKnownValue(resourceName, tfjsonpath.New("hostnames"), knownvalue.SetSizeExact(0)),
				},
			},
			{
				ConfigDirectory: config.StaticDirectory("testdata/host_group"),
				ConfigVariables: config.Variables{
					"description": config.StringVariable(rName),
					"hostnames":   config.SetVariable([]config.Variable{}...),
					"name":        config.StringVariable(rName),
					"type":        config.StringVariable("static"),
				},
				ResourceName:            resourceName,
				ImportState:             true,
				ImportStateVerify:       true,
				ImportStateVerifyIgnore: []string{"last_updated"},
			},
		},
	})
}

func TestAccHostGroupResource_name(t *testing.T) {
	rName := acctest.RandomResourceName()
	resourceName := "crowdstrike_host_group.test"

	resource.ParallelTest(t, resource.TestCase{
		PreCheck:                 func() { acctest.PreCheck(t) },
		ProtoV6ProviderFactories: acctest.ProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			{
				ConfigDirectory: config.StaticDirectory("testdata/host_group"),
				ConfigVariables: config.Variables{
					"assignment_rule": config.StringVariable("hostname:'tf-acc-test-a'"),
					"description":     config.StringVariable(rName),
					"name":            config.StringVariable(rName),
					"type":            config.StringVariable("dynamic"),
				},
				ConfigStateChecks: []statecheck.StateCheck{
					statecheck.ExpectKnownValue(resourceName, tfjsonpath.New("name"), knownvalue.StringExact(rName)),
				},
			},
			{
				ConfigDirectory: config.StaticDirectory("testdata/host_group"),
				ConfigVariables: config.Variables{
					"assignment_rule": config.StringVariable("hostname:'tf-acc-test-a'"),
					"description":     config.StringVariable(rName),
					"name":            config.StringVariable(rName + "-updated"),
					"type":            config.StringVariable("dynamic"),
				},
				ConfigPlanChecks: resource.ConfigPlanChecks{
					PreApply: []plancheck.PlanCheck{
						plancheck.ExpectResourceAction(resourceName, plancheck.ResourceActionUpdate),
					},
				},
				ConfigStateChecks: []statecheck.StateCheck{
					statecheck.ExpectKnownValue(resourceName, tfjsonpath.New("name"), knownvalue.StringExact(rName+"-updated")),
				},
			},
			{
				ConfigDirectory: config.StaticDirectory("testdata/host_group"),
				ConfigVariables: config.Variables{
					"assignment_rule": config.StringVariable("hostname:'tf-acc-test-a'"),
					"description":     config.StringVariable(rName),
					"name":            config.StringVariable(rName + "-updated"),
					"type":            config.StringVariable("dynamic"),
				},
				ResourceName:            resourceName,
				ImportState:             true,
				ImportStateVerify:       true,
				ImportStateVerifyIgnore: []string{"last_updated"},
			},
		},
	})
}

func TestAccHostGroupResource_type(t *testing.T) {
	t.Skip("testgen: each type requires a different membership attribute; covered by the assignmentRule and hostnames tests")
}
