# Code generated by testgen. DO NOT EDIT.

variable "description" {
  type    = string
  default = null
}

variable "enabled" {
  type    = bool
  default = null
}

variable "limit" {
  type    = number
  default = null
}

variable "name" {
  type    = string
  default = null
}

variable "platform" {
  type    = string
  default = null
}

variable "ratio" {
  type    = number
  default = null
}

variable "schedule" {
  type = object({
    interval = optional(string)
    timezone = optional(string)
  })
  default = null
}

variable "steps" {
  type    = list(string)
  default = null
}

variable "tags" {
  type    = set(string)
  default = null
}

resource "crowdstrike_widget" "test" {
  description = var.description
  enabled     = var.enabled
  limit       = var.limit
  name        = var.name
  platform    = var.platform
  ratio       = var.ratio
  schedule    = var.schedule
  steps       = var.steps
  tags        = var.tags
}
