// Code generated by testgen. DO NOT EDIT.

package widget_test

import (
	"testing"

	"github.com/crowdstrike/terraform-provider-crowdstrike/internal/acctest"
	"github.com/crowdstrike/terraform-provider-crowdstrike/internal/widget"
	"github.com/hashicorp/terraform-plugin-testing/config"
	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
	"github.com/hashicorp/terraform-plugin-testing/knownvalue"
	"github.com/hashicorp/terraform-plugin-testing/plancheck"
	"github.com/hashicorp/terraform-plugin-testing/statecheck"
	"github.com/hashicorp/terraform-plugin-testing/tfjsonpath"
)

func TestAccWidgetResource_basic(t *testing.T) {
	rName := acctest.RandomResourceName()
	resourceName := "crowdstrike_widget.test"

	resource.ParallelTest(t, resource.TestCase{
		PreCheck:                 func() { acctest.PreCheck(t) },
		ProtoV6ProviderFactories: acctest.ProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			{
				ConfigDirectory: config.StaticDirectory("testdata/widget"),
				ConfigVariables: config.Variables{
					"name":     config.StringVariable(rName),
					"platform": config.StringVariable("Windows"),
				},
				ConfigStateChecks: []statecheck.StateCheck{
					statecheck.ExpectKnownValue(resourceName, tfjsonpath.New("id"), knownvalue.NotNull()),
					statecheck.ExpectKnownValue(resourceName, tfjsonpath.New("last_updated"), knownvalue.NotNull()),
				},
			},
			{
				ConfigDirectory: config.StaticDirectory("testdata/widget"),
				ConfigVariables: config.Variables{
					"name":     config.StringVariable(rName),
					"platform": config.StringVariable("Windows"),
				},
				ResourceName:            resourceName,
				ImportState:             true,
				ImportStateVerify:       true,
				ImportStateVerifyIgnore: []string{"last_updated"},
			},
		},
	})
}

func TestAccWidgetResource_disappears(t *testing.T) {
	rName := acctest.RandomResourceName()
	resourceName := "crowdstrike_widget.test"

	resource.ParallelTest(t, resource.TestCase{
		PreCheck:                 func() { acctest.PreCheck(t) },
		ProtoV6ProviderFactories: acctest.ProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			{
				ConfigDirectory: config.StaticDirectory("testdata/widget"),
				ConfigVariables: config.Variables{
					"name":     config.StringVariable(rName),
					"platform": config.StringVariable("Windows"),
				},
				ConfigStateChecks: []statecheck.StateCheck{
					acctest.ResourceDisappears(widget.NewWidgetResource, resourceName),
				},
				ExpectNonEmptyPlan: true,
				ConfigPlanChecks: resource.ConfigPlanChecks{
					PostApplyPostRefresh: []plancheck.PlanCheck{
						plancheck.ExpectResourceAction(resourceName, plancheck.ResourceActionCreate),
					},
				},
			},
		},
	})
}

func TestAccWidgetResource_description(t *testing.T) {
	rName := acctest.RandomResourceName()
	resourceName := "crowdstrike_widget.test"

	resource.ParallelTest(t, resource.TestCase{
		PreCheck:                 func() { acctest.PreCheck(t) },
		ProtoV6ProviderFactories: acctest.ProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			{
				ConfigDirectory: config.StaticDirectory("testdata/widget"),
				ConfigVariables: config.Variables{
					"description": config.StringVariable(rName),
					"name":        config.StringVariable(rName),
					"platform":    config.StringVariable("Windows"),
				},
				ConfigStateChecks: []statecheck.StateCheck{
					statecheck.ExpectKnownValue(resourceName, tfjsonpath.New("description"), knownvalue.StringExact(rName)),
				},
			},
			{
				ConfigDirectory: config.StaticDirectory("testdata/widget"),
				ConfigVariables: config.Variables{
					"description": config.StringVariable(rName + "-updated"),
					"name":        config.StringVariable(rName),
					"platform":    config.StringVariable("Windows"),
				},
				ConfigPlanChecks: resource.ConfigPlanChecks{
					PreApply: []plancheck.PlanCheck{
						plancheck.ExpectResourceAction(resourceName, plancheck.ResourceActionUpdate),
					},
				},
				ConfigStateChecks: []statecheck.StateCheck{
					statecheck.ExpectKnownValue(resourceName, tfjsonpath.New("description"), knownvalue.StringExact(rName+"-updated")),
				},
			},
			{
				ConfigDirectory: config.StaticDirectory("testdata/widget"),
				ConfigVariables: config.Variables{
					"name":     config.StringVariable(rName),
					"platform": config.StringVariable("Windows"),
				},
				ConfigPlanChecks: resource.ConfigPlanChecks{
					PreApply: []plancheck.PlanCheck{
						plancheck.ExpectResourceAction(resourceName, plancheck.ResourceActionUpdate),
					},
				},
				ConfigStateChecks: []statecheck.StateCheck{
					statecheck.ExpectKnownValue(resourceName, tfjsonpath.New("description"), knownvalue.Null()),
				},
			},
			{
				ConfigDirectory: config.StaticDirectory("testdata/widget"),
				ConfigVariables: config.Variables{
					"name":     config.StringVariable(rName),
					"platform": config.StringVariable("Windows"),
				},
				ResourceName:            resourceName,
				ImportState:             true,
				ImportStateVerify:       true,
				ImportStateVerifyIgnore: []string{"last_updated"},
			},
		},
	})
}

func TestAccWidgetResource_enabled(t *testing.T) {
	rName := acctest.RandomResourceName()
	resourceName := "crowdstrike_widget.test"

	resource.ParallelTest(t, resource.TestCase{
		PreCheck:                 func() { acctest.PreCheck(t) },
		ProtoV6ProviderFactories: acctest.ProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			{
				ConfigDirectory: config.StaticDirectory("testdata/widget"),
				ConfigVariables: config.Variables{
					"enabled":  config.BoolVariable(true),
					"name":     config.StringVariable(rName),
					"platform": config.StringVariable("Windows"),
				},
				ConfigStateChecks: []statecheck.StateCheck{
					statecheck.ExpectKnownValue(resourceName, tfjsonpath.New("enabled"), knownvalue.Bool(true)),
				},
			},
			{
				ConfigDirectory: config.StaticDirectory("testdata/widget"),
				ConfigVariables: config.Variables{
					"enabled":  config.BoolVariable(false),
					"name":     config.StringVariable(rName),
					"platform": config.StringVariable("Windows"),
				},
				ConfigPlanChecks: resource.ConfigPlanChecks{
					PreApply: []plancheck.PlanCheck{
						plancheck.ExpectResourceAction(resourceName, plancheck.ResourceActionUpdate),
					},
				},
				ConfigStateChecks: []statecheck.StateCheck{
					statecheck.ExpectKnownValue(resourceName, tfjsonpath.New("enabled"), knownvalue.Bool(false)),
				},
			},
			{
				ConfigDirectory: config.StaticDirectory("testdata/widget"),
				ConfigVariables: config.Variables{
					"name":     config.StringVariable(rName),
					"platform": config.StringVariable("Windows"),
				},
				ConfigPlanChecks: resource.ConfigPlanChecks{
					PreApply: []plancheck.PlanCheck{
						plancheck.ExpectEmptyPlan(),
					},
				},
				ConfigStateChecks: []statecheck.StateCheck{
					statecheck.ExpectKnownValue(resourceName, tfjsonpath.New("enabled"), knownvalue.Bool(false)),
				},
			},
			{
				ConfigDirectory: config.StaticDirectory("testdata/widget"),
				ConfigVariables: config.Variables{
					"name":     config.StringVariable(rName),
					"platform": config.StringVariable("Windows"),
				},
				ResourceName:            resourceName,
				ImportState:             true,
				ImportStateVerify:       true,
				ImportStateVerifyIgnore: []string{"last_updated"},
			},
		},
	})
}

func TestAccWidgetResource_labels(t *testing.T) {
	t.Skip("testgen: maps are not supported yet")
}

func TestAccWidgetResource_limit(t *testing.T) {
	rName := acctest.RandomResourceName()
	resourceName := "crowdstrike_widget.test"

	resource.ParallelTest(t, resource.TestCase{
		PreCheck:                 func() { acctest.PreCheck(t) },
		ProtoV6ProviderFactories: acctest.ProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			{
				ConfigDirectory: config.StaticDirectory("testdata/widget"),
				ConfigVariables: config.Variables{
					"limit":    config.IntegerVariable(1),
					"name":     config.StringVariable(rName),
					"platform": config.StringVariable("Windows"),
				},
				ConfigStateChecks: []statecheck.StateCheck{
					statecheck.ExpectKnownValue(resourceName, tfjsonpath.New("limit"), knownvalue.Int64Exact(1)),
				},
			},
			{
				ConfigDirectory: config.StaticDirectory("testdata/widget"),
				ConfigVariables: config.Variables{
					"limit":    config.IntegerVariable(10),
					"name":     config.StringVariable(rName),
					"platform": config.StringVariable("Windows"),
				},
				ConfigPlanChecks: resource.ConfigPlanChecks{
					PreApply: []plancheck.PlanCheck{
						plancheck.ExpectResourceAction(resourceName, plancheck.ResourceActionUpdate),
					},
				},
				ConfigStateChecks: []statecheck.StateCheck{
					statecheck.ExpectKnownValue(resourceName, tfjsonpath.New("limit"), knownvalue.Int64Exact(10)),
				},
			},
			{
				ConfigDirectory: config.StaticDirectory("testdata/widget"),
				ConfigVariables: config.Variables{
					"name":     config.StringVariable(rName),
					"platform": config.StringVariable("Windows"),
				},
				ConfigPlanChecks: resource.ConfigPlanChecks{
					PreApply: []plancheck.PlanCheck{
						plancheck.ExpectResourceAction(resourceName, plancheck.ResourceActionUpdate),
					},
				},
				ConfigStateChecks: []statecheck.StateCheck{
					statecheck.ExpectKnownValue(resourceName, tfjsonpath.New("limit"), knownvalue.Null()),
				},
			},
			{
				ConfigDirectory: config.StaticDirectory("testdata/widget"),
				ConfigVariables: config.Variables{
					"name":     config.StringVariable(rName),
					"platform": config.StringVariable("Windows"),
				},
				ResourceName:            resourceName,
				ImportState:             true,
				ImportStateVerify:       true,
				ImportStateVerifyIgnore: []string{"last_updated"},
			},
		},
	})
}

func TestAccWidgetResource_name(t *testing.T) {
	rName := acctest.RandomResourceName()
	resourceName := "crowdstrike_widget.test"

	resource.ParallelTest(t, resource.TestCase{
		PreCheck:                 func() { acctest.PreCheck(t) },
		ProtoV6ProviderFactories: acctest.ProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			{
				ConfigDirectory: config.StaticDirectory("testdata/widget"),
				ConfigVariables: config.Variables{
					"name":     config.StringVariable(rName),
					"platform": config.StringVariable("Windows"),
				},
				ConfigStateChecks: []statecheck.StateCheck{
					statecheck.ExpectKnownValue(resourceName, tfjsonpath.New("name"), knownvalue.StringExact(rName)),
				},
			},
			{
				ConfigDirectory: config.StaticDirectory("testdata/widget"),
				ConfigVariables: config.Variables{
					"name":     config.StringVariable(rName + "-updated"),
					"platform": config.StringVariable("Windows"),
				},
				ConfigPlanChecks: resource.ConfigPlanChecks{
					PreApply: []plancheck.PlanCheck{
						plancheck.ExpectResourceAction(resourceName, plancheck.ResourceActionUpdate),
					},
				},
				ConfigStateChecks: []statecheck.StateCheck{
					statecheck.ExpectKnownValue(resourceName, tfjsonpath.New("name"), knownvalue.StringExact(rName+"-updated")),
				},
			},
			{
				ConfigDirectory: config.StaticDirectory("testdata/widget"),
				ConfigVariables: config.Variables{
					"name":     config.StringVariable(rName + "-updated"),
					"platform": config.StringVariable("Windows"),
				},
				ResourceName:            resourceName,
				ImportState:             true,
				ImportStateVerify:       true,
				ImportStateVerifyIgnore: []string{"last_updated"},
			},
		},
	})
}

func TestAccWidgetResource_platform(t *testing.T) {
	rName := acctest.RandomResourceName()
	resourceName := "crowdstrike_widget.test"

	resource.ParallelTest(t, resource.TestCase{
		PreCheck:                 func() { acctest.PreCheck(t) },
		ProtoV6ProviderFactories: acctest.ProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			{
				ConfigDirectory: config.StaticDirectory("testdata/widget"),
				ConfigVariables: config.Variables{
					"name":     config.StringVariable(rName),
					"platform": config.StringVariable("Windows"),
				},
				ConfigStateChecks: []statecheck.StateCheck{
					statecheck.ExpectKnownValue(resourceName, tfjsonpath.New("platform"), knownvalue.StringExact("Windows")),
				},
			},
			{
				ConfigDirectory: config.StaticDirectory("testdata/widget"),
				ConfigVariables: config.Variables{
					"name":     config.StringVariable(rName),
					"platform": config.StringVariable("Linux"),
				},
				ConfigPlanChecks: resource.ConfigPlanChecks{
					PreApply: []plancheck.PlanCheck{
						plancheck.ExpectResourceAction(resourceName, plancheck.ResourceActionDestroyBeforeCreate),
					},
				},
				ConfigStateChecks: []statecheck.StateCheck{
					statecheck.ExpectKnownValue(resourceName, tfjsonpath.New("platform"), knownvalue.StringExact("Linux")),
				},
			},
			{
				ConfigDirectory: config.StaticDirectory("testdata/widget"),
				ConfigVariables: config.Variables{
					"name":     config.StringVariable(rName),
					"platform": config.StringVariable("Linux"),
				},
				ResourceName:            resourceName,
				ImportState:             true,
				ImportStateVerify:       true,
				ImportStateVerifyIgnore: []string{"last_updated"},
			},
		},
	})
}

func TestAccWidgetResource_ratio(t *testing.T) {
	rName := acctest.RandomResourceName()
	resourceName := "crowdstrike_widget.test"

	resource.ParallelTest(t, resource.TestCase{
		PreCheck:                 func() { acctest.PreCheck(t) },
		ProtoV6ProviderFactories: acctest.ProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			{
				ConfigDirectory: config.StaticDirectory("testdata/widget"),
				ConfigVariables: config.Variables{
					"name":     config.StringVariable(rName),
					"platform": config.StringVariable("Windows"),
					"ratio":    config.FloatVariable(1.0),
				},
				ConfigStateChecks: []statecheck.StateCheck{
					statecheck.ExpectKnownValue(resourceName, tfjsonpath.New("ratio"), knownvalue.Float64Exact(1.0)),
				},
			},
			{
				ConfigDirectory: config.StaticDirectory("testdata/widget"),
				ConfigVariables: config.Variables{
					"name":     config.StringVariable(rName),
					"platform": config.StringVariable("Windows"),
				},
				ConfigPlanChecks: resource.ConfigPlanChecks{
					PreApply: []plancheck.PlanCheck{
						plancheck.ExpectResourceAction(resourceName, plancheck.ResourceActionUpdate),
					},
				},
				ConfigStateChecks: []statecheck.StateCheck{
					statecheck.ExpectKnownValue(resourceName, tfjsonpath.New("ratio"), knownvalue.Null()),
				},
			},
			{
				ConfigDirectory: config.StaticDirectory("testdata/widget"),
				ConfigVariables: config.Variables{
					"name":     config.StringVariable(rName),
					"platform": config.StringVariable("Windows"),
				},
				ResourceName:            resourceName,
				ImportState:             true,
				ImportStateVerify:       true,
				ImportStateVerifyIgnore: []string{"last_updated"},
			},
		},
	})
}

func TestAccWidgetResource_schedule(t *testing.T) {
	rName := acctest.RandomResourceName()
	resourceName := "crowdstrike_widget.test"

	resource.ParallelTest(t, resource.TestCase{
		PreCheck:                 func() { acctest.PreCheck(t) },
		ProtoV6ProviderFactories: acctest.ProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			{
				ConfigDirectory: config.StaticDirectory("testdata/widget"),
				ConfigVariables: config.Variables{
					"name":     config.StringVariable(rName),
					"platform": config.StringVariable("Windows"),
					"schedule": config.ObjectVariable(map[string]config.Variable{"interval": config.StringVariable("hourly")}),
				},
				ConfigStateChecks: []statecheck.StateCheck{
					statecheck.ExpectKnownValue(resourceName, tfjsonpath.New("schedule"), knownvalue.ObjectPartial(map[string]knownvalue.Check{"interval": knownvalue.StringExact("hourly")})),
				},
			},
			{
				ConfigDirectory: config.StaticDirectory("testdata/widget"),
				ConfigVariables: config.Variables{
					"name":     config.StringVariable(rName),
					"platform": config.StringVariable("Windows"),
					"schedule": config.ObjectVariable(map[string]config.Variable{"interval": config.StringVariable("daily")}),
				},
				ConfigPlanChecks: resource.ConfigPlanChecks{
					PreApply: []plancheck.PlanCheck{
						plancheck.ExpectResourceAction(resourceName, plancheck.ResourceActionUpdate),
					},
				},
				ConfigStateChecks: []statecheck.StateCheck{
					statecheck.ExpectKnownValue(resourceName, tfjsonpath.New("schedule"), knownvalue.ObjectPartial(map[string]knownvalue.Check{"interval": knownvalue.StringExact("daily")})),
				},
			},
			{
				ConfigDirectory: config.StaticDirectory("testdata/widget"),
				ConfigVariables: config.Variables{
					"name":     config.StringVariable(rName),
					"platform": config.StringVariable("Windows"),
				},
				ConfigPlanChecks: resource.ConfigPlanChecks{
					PreApply: []plancheck.PlanCheck{
						plancheck.ExpectResourceAction(resourceName, plancheck.ResourceActionUpdate),
					},
				},
				ConfigStateChecks: []statecheck.StateCheck{
					statecheck.ExpectKnownValue(resourceName, tfjsonpath.New("schedule"), knownvalue.Null()),
				},
			},
			{
				ConfigDirectory: config.StaticDirectory("testdata/widget"),
				ConfigVariables: config.Variables{
					"name":     config.StringVariable(rName),
					"platform": config.StringVariable("Windows"),
				},
				ResourceName:            resourceName,
				ImportState:             true,
				ImportStateVerify:       true,
				ImportStateVerifyIgnore: []string{"last_updated"},
			},
		},
	})
}

func TestAccWidgetResource_scheduleTimezone(t *testing.T) {
	rName := acctest.RandomResourceName()
	resourceName := "crowdstrike_widget.test"

	resource.ParallelTest(t, resource.TestCase{
		PreCheck:                 func() { acctest.PreCheck(t) },
		ProtoV6ProviderFactories: acctest.ProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			{
				ConfigDirectory: config.StaticDirectory("testdata/widget"),
				ConfigVariables: config.Variables{
					"name":     config.StringVariable(rName),
					"platform": config.StringVariable("Windows"),
					"schedule": config.ObjectVariable(map[string]config.Variable{"interval": config.StringVariable("hourly"), "timezone": config.StringVariable("UTC")}),
				},
				ConfigStateChecks: []statecheck.StateCheck{
					statecheck.ExpectKnownValue(resourceName, tfjsonpath.New("schedule").AtMapKey("timezone"), knownvalue.StringExact("UTC")),
				},
			},
			{
				ConfigDirectory: config.StaticDirectory("testdata/widget"),
				ConfigVariables: config.Variables{
					"name":     config.StringVariable(rName),
					"platform": config.StringVariable("Windows"),
					"schedule": config.ObjectVariable(map[string]config.Variable{"interval": config.StringVariable("hourly"), "timezone": config.StringVariable("EST")}),
				},
				ConfigPlanChecks: resource.ConfigPlanChecks{
					PreApply: []plancheck.PlanCheck{
						plancheck.ExpectResourceAction(resourceName, plancheck.ResourceActionUpdate),
					},
				},
				ConfigStateChecks: []statecheck.StateCheck{
					statecheck.ExpectKnownValue(resourceName, tfjsonpath.New("schedule").AtMapKey("timezone"), knownvalue.StringExact("EST")),
				},
			},
			{
				ConfigDirectory: config.StaticDirectory("testdata/widget"),
				ConfigVariables: config.Variables{
					"name":     config.StringVariable(rName),
					"platform": config.StringVariable("Windows"),
					"schedule": config.ObjectVariable(map[string]config.Variable{"interval": config.StringVariable("hourly")}),
				},
				ConfigPlanChecks: resource.ConfigPlanChecks{
					PreApply: []plancheck.PlanCheck{
						plancheck.ExpectResourceAction(resourceName, plancheck.ResourceActionUpdate),
					},
				},
				ConfigStateChecks: []statecheck.StateCheck{
					statecheck.ExpectKnownValue(resourceName, tfjsonpath.New("schedule").AtMapKey("timezone"), knownvalue.Null()),
				},
			},
			{
				ConfigDirectory: config.StaticDirectory("testdata/widget"),
				ConfigVariables: config.Variables{
					"name":     config.StringVariable(rName),
					"platform": config.StringVariable("Windows"),
					"schedule": config.ObjectVariable(map[string]config.Variable{"interval": config.StringVariable("hourly")}),
				},
				ResourceName:            resourceName,
				ImportState:             true,
				ImportStateVerify:       true,
				ImportStateVerifyIgnore: []string{"last_updated"},
			},
		},
	})
}

func TestAccWidgetResource_steps(t *testing.T) {
	rName := acctest.RandomResourceName()
	resourceName := "crowdstrike_widget.test"

	resource.ParallelTest(t, resource.TestCase{
		PreCheck:                 func() { acctest.PreCheck(t) },
		ProtoV6ProviderFactories: acctest.ProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			{
				ConfigDirectory: config.StaticDirectory("testdata/widget"),
				ConfigVariables: config.Variables{
					"name":     config.StringVariable(rName),
					"platform": config.StringVariable("Windows"),
					"steps":    config.ListVariable(config.StringVariable("first"), config.StringVariable("second")),
				},
				ConfigStateChecks: []statecheck.StateCheck{
					statecheck.ExpectKnownValue(resourceName, tfjsonpath.New("steps"), knownvalue.ListExact([]knownvalue.Check{knownvalue.StringExact("first"), knownvalue.StringExact("second")})),
				},
			},
			{
				ConfigDirectory: config.StaticDirectory("testdata/widget"),
				ConfigVariables: config.Variables{
					"name":     config.StringVariable(rName),
					"platform": config.StringVariable("Windows"),
					"steps":    config.ListVariable(config.StringVariable("first"), config.StringVariable("second"), config.StringVariable("third")),
				},
				ConfigPlanChecks: resource.ConfigPlanChecks{
					PreApply: []plancheck.PlanCheck{
						plancheck.ExpectResourceAction(resourceName, plancheck.ResourceActionUpdate),
					},
				},
				ConfigStateChecks: []statecheck.StateCheck{
					statecheck.ExpectKnownValue(resourceName, tfjsonpath.New("steps"), knownvalue.ListExact([]knownvalue.Check{knownvalue.StringExact("first"), knownvalue.StringExact("second"), knownvalue.StringExact("third")})),
				},
			},
			{
				ConfigDirectory: config.StaticDirectory("testdata/widget"),
				ConfigVariables: config.Variables{
					"name":     config.StringVariable(rName),
					"platform": config.StringVariable("Windows"),
					"steps":    config.ListVariable(config.StringVariable("third"), config.StringVariable("first"), config.StringVariable("second")),
				},
				ConfigPlanChecks: resource.ConfigPlanChecks{
					PreApply: []plancheck.PlanCheck{
						plancheck.ExpectResourceAction(resourceName, plancheck.ResourceActionUpdate),
					},
				},
				ConfigStateChecks: []statecheck.StateCheck{
					statecheck.ExpectKnownValue(resourceName, tfjsonpath.New("steps"), knownvalue.ListExact([]knownvalue.Check{knownvalue.StringExact("third"), knownvalue.StringExact("first"), knownvalue.StringExact("second")})),
				},
			},
			{
				ConfigDirectory: config.StaticDirectory("testdata/widget"),
				ConfigVariables: config.Variables{
					"name":     config.StringVariable(rName),
					"platform": config.StringVariable("Windows"),
					"steps":    config.ListVariable(config.StringVariable("third"), config.StringVariable("second")),
				},
				ConfigPlanChecks: resource.ConfigPlanChecks{
					PreApply: []plancheck.PlanCheck{
						plancheck.ExpectResourceAction(resourceName, plancheck.ResourceActionUpdate),
					},
				},
				ConfigStateChecks: []statecheck.StateCheck{
					statecheck.ExpectKnownValue(resourceName, tfjsonpath.New("steps"), knownvalue.ListExact([]knownvalue.Check{knownvalue.StringExact("third"), knownvalue.StringExact("second")})),
				},
			},
			{
				ConfigDirectory: config.StaticDirectory("testdata/widget"),
				ConfigVariables: config.Variables{
					"name":     config.StringVariable(rName),
					"platform": config.StringVariable("Windows"),
				},
				ConfigPlanChecks: resource.ConfigPlanChecks{
					PreApply: []plancheck.PlanCheck{
						plancheck.ExpectResourceAction(resourceName, plancheck.ResourceActionUpdate),
					},
				},
				ConfigStateChecks: []statecheck.StateCheck{
					statecheck.ExpectKnownValue(resourceName, tfjsonpath.New("steps"), knownvalue.Null()),
				},
			},
			{
				ConfigDirectory: config.StaticDirectory("testdata/widget"),
				ConfigVariables: config.Variables{
					"name":     config.StringVariable(rName),
					"platform": config.StringVariable("Windows"),
				},
				ResourceName:            resourceName,
				ImportState:             true,
				ImportStateVerify:       true,
				ImportStateVerifyIgnore: []string{"last_updated"},
			},
		},
	})
}

func TestAccWidgetResource_tags(t *testing.T) {
	rName := acctest.RandomResourceName()
	resourceName := "crowdstrike_widget.test"

	resource.ParallelTest(t, resource.TestCase{
		PreCheck:                 func() { acctest.PreCheck(t) },
		ProtoV6ProviderFactories: acctest.ProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			{
				ConfigDirectory: config.StaticDirectory("testdata/widget"),
				ConfigVariables: config.Variables{
					"name":     config.StringVariable(rName),
					"platform": config.StringVariable("Windows"),
					"tags":     config.SetVariable(config.StringVariable("a"), config.StringVariable("b")),
				},
				ConfigStateChecks: []statecheck.StateCheck{
					statecheck.ExpectKnownValue(resourceName, tfjsonpath.New("tags"), knownvalue.SetExact([]knownvalue.Check{knownvalue.StringExact("a"), knownvalue.StringExact("b")})),
				},
			},
			{
				ConfigDirectory: config.StaticDirectory("testdata/widget"),
				ConfigVariables: config.Variables{
					"name":     config.StringVariable(rName),
					"platform": config.StringVariable("Windows"),
					"tags":     config.SetVariable(config.StringVariable("a"), config.StringVariable("b"), config.StringVariable("c")),
				},
				ConfigPlanChecks: resource.ConfigPlanChecks{
					PreApply: []plancheck.PlanCheck{
						plancheck.ExpectResourceAction(resourceName, plancheck.ResourceActionUpdate),
					},
				},
				ConfigStateChecks: []statecheck.StateCheck{
					statecheck.ExpectKnownValue(resourceName, tfjsonpath.New("tags"), knownvalue.SetExact([]knownvalue.Check{knownvalue.StringExact("a"), knownvalue.StringExact("b"), knownvalue.StringExact("c")})),
				},
			},
			{
				ConfigDirectory: config.StaticDirectory("testdata/widget"),
				ConfigVariables: config.Variables{
					"name":     config.StringVariable(rName),
					"platform": config.StringVariable("Windows"),
					"tags":     config.SetVariable(config.StringVariable("c"), config.StringVariable("a"), config.StringVariable("b")),
				},
				ConfigPlanChecks: resource.ConfigPlanChecks{
					PreApply: []plancheck.PlanCheck{
						plancheck.ExpectEmptyPlan(),
					},
				},
				ConfigStateChecks: []statecheck.StateCheck{
					statecheck.ExpectKnownValue(resourceName, tfjsonpath.New("tags"), knownvalue.SetExact([]knownvalue.Check{knownvalue.StringExact("c"), knownvalue.StringExact("a"), knownvalue.StringExact("b")})),
				},
			},
			{
				ConfigDirectory: config.StaticDirectory("testdata/widget"),
				ConfigVariables: config.Variables{
					"name":     config.StringVariable(rName),
					"platform": config.StringVariable("Windows"),
					"tags":     config.SetVariable(config.StringVariable("c"), config.StringVariable("b")),
				},
				ConfigPlanChecks: resource.ConfigPlanChecks{
					PreApply: []plancheck.PlanCheck{
						plancheck.ExpectResourceAction(resourceName, plancheck.ResourceActionUpdate),
					},
				},
				ConfigStateChecks: []statecheck.StateCheck{
					statecheck.ExpectKnownValue(resourceName, tfjsonpath.New("tags"), knownvalue.SetExact([]knownvalue.Check{knownvalue.StringExact("c"), knownvalue.StringExact("b")})),
				},
			},
			{
				ConfigDirectory: config.StaticDirectory("testdata/widget"),
				ConfigVariables: config.Variables{
					"name":     config.StringVariable(rName),
					"platform": config.StringVariable("Windows"),
					"tags":     config.SetVariable([]config.Variable{}...),
				},
				ConfigPlanChecks: resource.ConfigPlanChecks{
					PreApply: []plancheck.PlanCheck{
						plancheck.ExpectResourceAction(resourceName, plancheck.ResourceActionUpdate),
					},
				},
				ConfigStateChecks: []statecheck.StateCheck{
					statecheck.ExpectKnownValue(resourceName, tfjsonpath.New("tags"), knownvalue.SetSizeExact(0)),
				},
			},
			{
				ConfigDirectory: config.StaticDirectory("testdata/widget"),
				ConfigVariables: config.Variables{
					"name":     config.StringVariable(rName),
					"platform": config.StringVariable("Windows"),
				},
				ConfigPlanChecks: resource.ConfigPlanChecks{
					PreApply: []plancheck.PlanCheck{
						plancheck.ExpectResourceAction(resourceName, plancheck.ResourceActionUpdate),
					},
				},
				ConfigStateChecks: []statecheck.StateCheck{
					statecheck.ExpectKnownValue(resourceName, tfjsonpath.New("tags"), knownvalue.Null()),
				},
			},
			{
				ConfigDirectory: config.StaticDirectory("testdata/widget"),
				ConfigVariables: config.Variables{
					"name":     config.StringVariable(rName),
					"platform": config.StringVariable("Windows"),
				},
				ResourceName:            resourceName,
				ImportState:             true,
				ImportStateVerify:       true,
				ImportStateVerifyIgnore: []string{"last_updated"},
			},
		},
	})
}
