// Code generated by testgen. DO NOT EDIT.

package cidgroup_test

import (
	"testing"

	"github.com/crowdstrike/terraform-provider-crowdstrike/internal/acctest"
	cidgroup "github.com/crowdstrike/terraform-provider-crowdstrike/internal/cid_group"
	"github.com/hashicorp/terraform-plugin-testing/config"
	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
	"github.com/hashicorp/terraform-plugin-testing/knownvalue"
	"github.com/hashicorp/terraform-plugin-testing/plancheck"
	"github.com/hashicorp/terraform-plugin-testing/statecheck"
	"github.com/hashicorp/terraform-plugin-testing/tfjsonpath"
)

func TestAccCIDGroupResource_disappears(t *testing.T) {
	rName := acctest.RandomResourceName()
	resourceName := "crowdstrike_cid_group.test"

	resource.ParallelTest(t, resource.TestCase{
		PreCheck:                 func() { acctest.PreCheck(t) },
		ProtoV6ProviderFactories: acctest.ProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			{
				ConfigDirectory: config.StaticDirectory("testdata/cid_group"),
				ConfigVariables: config.Variables{
					"name": config.StringVariable(rName),
				},
				ConfigStateChecks: []statecheck.StateCheck{
					acctest.ResourceDisappears(cidgroup.NewCIDGroupResource, resourceName),
				},
				ExpectNonEmptyPlan: true,
				ConfigPlanChecks: resource.ConfigPlanChecks{
					PostApplyPostRefresh: []plancheck.PlanCheck{
						plancheck.ExpectResourceAction(resourceName, plancheck.ResourceActionCreate),
					},
				},
			},
		},
	})
}

func TestAccCIDGroupResource_cids(t *testing.T) {
	t.Skip("testgen: child CIDs come from TF_ACC_CID_GROUP_CHILD_CIDS; values from the environment are not supported yet")
}

func TestAccCIDGroupResource_description(t *testing.T) {
	rName := acctest.RandomResourceName()
	resourceName := "crowdstrike_cid_group.test"

	resource.ParallelTest(t, resource.TestCase{
		PreCheck:                 func() { acctest.PreCheck(t) },
		ProtoV6ProviderFactories: acctest.ProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			{
				ConfigDirectory: config.StaticDirectory("testdata/cid_group"),
				ConfigVariables: config.Variables{
					"description": config.StringVariable(rName),
					"name":        config.StringVariable(rName),
				},
				ConfigStateChecks: []statecheck.StateCheck{
					statecheck.ExpectKnownValue(resourceName, tfjsonpath.New("description"), knownvalue.StringExact(rName)),
				},
			},
			{
				ConfigDirectory: config.StaticDirectory("testdata/cid_group"),
				ConfigVariables: config.Variables{
					"description": config.StringVariable(rName + "-updated"),
					"name":        config.StringVariable(rName),
				},
				ConfigPlanChecks: resource.ConfigPlanChecks{
					PreApply: []plancheck.PlanCheck{
						plancheck.ExpectResourceAction(resourceName, plancheck.ResourceActionUpdate),
					},
				},
				ConfigStateChecks: []statecheck.StateCheck{
					statecheck.ExpectKnownValue(resourceName, tfjsonpath.New("description"), knownvalue.StringExact(rName+"-updated")),
				},
			},
			{
				ConfigDirectory: config.StaticDirectory("testdata/cid_group"),
				ConfigVariables: config.Variables{
					"name": config.StringVariable(rName),
				},
				ConfigPlanChecks: resource.ConfigPlanChecks{
					PreApply: []plancheck.PlanCheck{
						plancheck.ExpectResourceAction(resourceName, plancheck.ResourceActionUpdate),
					},
				},
				ConfigStateChecks: []statecheck.StateCheck{
					statecheck.ExpectKnownValue(resourceName, tfjsonpath.New("description"), knownvalue.Null()),
				},
			},
			{
				ConfigDirectory: config.StaticDirectory("testdata/cid_group"),
				ConfigVariables: config.Variables{
					"name": config.StringVariable(rName),
				},
				ResourceName:      resourceName,
				ImportState:       true,
				ImportStateVerify: true,
			},
		},
	})
}

func TestAccCIDGroupResource_name(t *testing.T) {
	rName := acctest.RandomResourceName()
	resourceName := "crowdstrike_cid_group.test"

	resource.ParallelTest(t, resource.TestCase{
		PreCheck:                 func() { acctest.PreCheck(t) },
		ProtoV6ProviderFactories: acctest.ProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			{
				ConfigDirectory: config.StaticDirectory("testdata/cid_group"),
				ConfigVariables: config.Variables{
					"name": config.StringVariable(rName),
				},
				ConfigStateChecks: []statecheck.StateCheck{
					statecheck.ExpectKnownValue(resourceName, tfjsonpath.New("name"), knownvalue.StringExact(rName)),
				},
			},
			{
				ConfigDirectory: config.StaticDirectory("testdata/cid_group"),
				ConfigVariables: config.Variables{
					"name": config.StringVariable(rName + "-updated"),
				},
				ConfigPlanChecks: resource.ConfigPlanChecks{
					PreApply: []plancheck.PlanCheck{
						plancheck.ExpectResourceAction(resourceName, plancheck.ResourceActionUpdate),
					},
				},
				ConfigStateChecks: []statecheck.StateCheck{
					statecheck.ExpectKnownValue(resourceName, tfjsonpath.New("name"), knownvalue.StringExact(rName+"-updated")),
				},
			},
			{
				ConfigDirectory: config.StaticDirectory("testdata/cid_group"),
				ConfigVariables: config.Variables{
					"name": config.StringVariable(rName + "-updated"),
				},
				ResourceName:      resourceName,
				ImportState:       true,
				ImportStateVerify: true,
			},
		},
	})
}
